/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject AuthProvider
 */
@XStreamAlias("AuthProvider")
public class AuthProvider extends AbstractSObjectBase {

    // ProviderType
    @XStreamConverter(PicklistEnumConverter.class)
    private ProviderTypeEnum ProviderType;

    @JsonProperty("ProviderType")
    public ProviderTypeEnum getProviderType() {
        return this.ProviderType;
    }

    @JsonProperty("ProviderType")
    public void setProviderType(ProviderTypeEnum ProviderType) {
        this.ProviderType = ProviderType;
    }

    // FriendlyName
    private String FriendlyName;

    @JsonProperty("FriendlyName")
    public String getFriendlyName() {
        return this.FriendlyName;
    }

    @JsonProperty("FriendlyName")
    public void setFriendlyName(String FriendlyName) {
        this.FriendlyName = FriendlyName;
    }

    // DeveloperName
    private String DeveloperName;

    @JsonProperty("DeveloperName")
    public String getDeveloperName() {
        return this.DeveloperName;
    }

    @JsonProperty("DeveloperName")
    public void setDeveloperName(String DeveloperName) {
        this.DeveloperName = DeveloperName;
    }

    // RegistrationHandlerId
    private String RegistrationHandlerId;

    @JsonProperty("RegistrationHandlerId")
    public String getRegistrationHandlerId() {
        return this.RegistrationHandlerId;
    }

    @JsonProperty("RegistrationHandlerId")
    public void setRegistrationHandlerId(String RegistrationHandlerId) {
        this.RegistrationHandlerId = RegistrationHandlerId;
    }

    // ExecutionUserId
    private String ExecutionUserId;

    @JsonProperty("ExecutionUserId")
    public String getExecutionUserId() {
        return this.ExecutionUserId;
    }

    @JsonProperty("ExecutionUserId")
    public void setExecutionUserId(String ExecutionUserId) {
        this.ExecutionUserId = ExecutionUserId;
    }

    // ConsumerKey
    private String ConsumerKey;

    @JsonProperty("ConsumerKey")
    public String getConsumerKey() {
        return this.ConsumerKey;
    }

    @JsonProperty("ConsumerKey")
    public void setConsumerKey(String ConsumerKey) {
        this.ConsumerKey = ConsumerKey;
    }

    // ConsumerSecret
    private String ConsumerSecret;

    @JsonProperty("ConsumerSecret")
    public String getConsumerSecret() {
        return this.ConsumerSecret;
    }

    @JsonProperty("ConsumerSecret")
    public void setConsumerSecret(String ConsumerSecret) {
        this.ConsumerSecret = ConsumerSecret;
    }

    // ErrorUrl
    private String ErrorUrl;

    @JsonProperty("ErrorUrl")
    public String getErrorUrl() {
        return this.ErrorUrl;
    }

    @JsonProperty("ErrorUrl")
    public void setErrorUrl(String ErrorUrl) {
        this.ErrorUrl = ErrorUrl;
    }

    // AuthorizeUrl
    private String AuthorizeUrl;

    @JsonProperty("AuthorizeUrl")
    public String getAuthorizeUrl() {
        return this.AuthorizeUrl;
    }

    @JsonProperty("AuthorizeUrl")
    public void setAuthorizeUrl(String AuthorizeUrl) {
        this.AuthorizeUrl = AuthorizeUrl;
    }

    // TokenUrl
    private String TokenUrl;

    @JsonProperty("TokenUrl")
    public String getTokenUrl() {
        return this.TokenUrl;
    }

    @JsonProperty("TokenUrl")
    public void setTokenUrl(String TokenUrl) {
        this.TokenUrl = TokenUrl;
    }

    // UserInfoUrl
    private String UserInfoUrl;

    @JsonProperty("UserInfoUrl")
    public String getUserInfoUrl() {
        return this.UserInfoUrl;
    }

    @JsonProperty("UserInfoUrl")
    public void setUserInfoUrl(String UserInfoUrl) {
        this.UserInfoUrl = UserInfoUrl;
    }

    // DefaultScopes
    private String DefaultScopes;

    @JsonProperty("DefaultScopes")
    public String getDefaultScopes() {
        return this.DefaultScopes;
    }

    @JsonProperty("DefaultScopes")
    public void setDefaultScopes(String DefaultScopes) {
        this.DefaultScopes = DefaultScopes;
    }

    // IdTokenIssuer
    private String IdTokenIssuer;

    @JsonProperty("IdTokenIssuer")
    public String getIdTokenIssuer() {
        return this.IdTokenIssuer;
    }

    @JsonProperty("IdTokenIssuer")
    public void setIdTokenIssuer(String IdTokenIssuer) {
        this.IdTokenIssuer = IdTokenIssuer;
    }

    // OptionsSendAccessTokenInHeader
    private Boolean OptionsSendAccessTokenInHeader;

    @JsonProperty("OptionsSendAccessTokenInHeader")
    public Boolean getOptionsSendAccessTokenInHeader() {
        return this.OptionsSendAccessTokenInHeader;
    }

    @JsonProperty("OptionsSendAccessTokenInHeader")
    public void setOptionsSendAccessTokenInHeader(Boolean OptionsSendAccessTokenInHeader) {
        this.OptionsSendAccessTokenInHeader = OptionsSendAccessTokenInHeader;
    }

    // OptionsSendClientCredentialsInHeader
    private Boolean OptionsSendClientCredentialsInHeader;

    @JsonProperty("OptionsSendClientCredentialsInHeader")
    public Boolean getOptionsSendClientCredentialsInHeader() {
        return this.OptionsSendClientCredentialsInHeader;
    }

    @JsonProperty("OptionsSendClientCredentialsInHeader")
    public void setOptionsSendClientCredentialsInHeader(Boolean OptionsSendClientCredentialsInHeader) {
        this.OptionsSendClientCredentialsInHeader = OptionsSendClientCredentialsInHeader;
    }

    // OptionsIncludeOrgIdInId
    private Boolean OptionsIncludeOrgIdInId;

    @JsonProperty("OptionsIncludeOrgIdInId")
    public Boolean getOptionsIncludeOrgIdInId() {
        return this.OptionsIncludeOrgIdInId;
    }

    @JsonProperty("OptionsIncludeOrgIdInId")
    public void setOptionsIncludeOrgIdInId(Boolean OptionsIncludeOrgIdInId) {
        this.OptionsIncludeOrgIdInId = OptionsIncludeOrgIdInId;
    }

    // IconUrl
    private String IconUrl;

    @JsonProperty("IconUrl")
    public String getIconUrl() {
        return this.IconUrl;
    }

    @JsonProperty("IconUrl")
    public void setIconUrl(String IconUrl) {
        this.IconUrl = IconUrl;
    }

    // LogoutUrl
    private String LogoutUrl;

    @JsonProperty("LogoutUrl")
    public String getLogoutUrl() {
        return this.LogoutUrl;
    }

    @JsonProperty("LogoutUrl")
    public void setLogoutUrl(String LogoutUrl) {
        this.LogoutUrl = LogoutUrl;
    }

}
