/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject AuthSession
 */
@XStreamAlias("AuthSession")
public class AuthSession extends AbstractSObjectBase {

    // UsersId
    private String UsersId;

    @JsonProperty("UsersId")
    public String getUsersId() {
        return this.UsersId;
    }

    @JsonProperty("UsersId")
    public void setUsersId(String UsersId) {
        this.UsersId = UsersId;
    }

    // NumSecondsValid
    private Integer NumSecondsValid;

    @JsonProperty("NumSecondsValid")
    public Integer getNumSecondsValid() {
        return this.NumSecondsValid;
    }

    @JsonProperty("NumSecondsValid")
    public void setNumSecondsValid(Integer NumSecondsValid) {
        this.NumSecondsValid = NumSecondsValid;
    }

    // UserType
    @XStreamConverter(PicklistEnumConverter.class)
    private UserTypeEnum UserType;

    @JsonProperty("UserType")
    public UserTypeEnum getUserType() {
        return this.UserType;
    }

    @JsonProperty("UserType")
    public void setUserType(UserTypeEnum UserType) {
        this.UserType = UserType;
    }

    // SourceIp
    private String SourceIp;

    @JsonProperty("SourceIp")
    public String getSourceIp() {
        return this.SourceIp;
    }

    @JsonProperty("SourceIp")
    public void setSourceIp(String SourceIp) {
        this.SourceIp = SourceIp;
    }

    // LoginType
    @XStreamConverter(PicklistEnumConverter.class)
    private LoginTypeEnum LoginType;

    @JsonProperty("LoginType")
    public LoginTypeEnum getLoginType() {
        return this.LoginType;
    }

    @JsonProperty("LoginType")
    public void setLoginType(LoginTypeEnum LoginType) {
        this.LoginType = LoginType;
    }

    // SessionType
    @XStreamConverter(PicklistEnumConverter.class)
    private SessionTypeEnum SessionType;

    @JsonProperty("SessionType")
    public SessionTypeEnum getSessionType() {
        return this.SessionType;
    }

    @JsonProperty("SessionType")
    public void setSessionType(SessionTypeEnum SessionType) {
        this.SessionType = SessionType;
    }

    // SessionSecurityLevel
    @XStreamConverter(PicklistEnumConverter.class)
    private SessionSecurityLevelEnum SessionSecurityLevel;

    @JsonProperty("SessionSecurityLevel")
    public SessionSecurityLevelEnum getSessionSecurityLevel() {
        return this.SessionSecurityLevel;
    }

    @JsonProperty("SessionSecurityLevel")
    public void setSessionSecurityLevel(SessionSecurityLevelEnum SessionSecurityLevel) {
        this.SessionSecurityLevel = SessionSecurityLevel;
    }

    // LogoutUrl
    private String LogoutUrl;

    @JsonProperty("LogoutUrl")
    public String getLogoutUrl() {
        return this.LogoutUrl;
    }

    @JsonProperty("LogoutUrl")
    public void setLogoutUrl(String LogoutUrl) {
        this.LogoutUrl = LogoutUrl;
    }

    // ParentId
    private String ParentId;

    @JsonProperty("ParentId")
    public String getParentId() {
        return this.ParentId;
    }

    @JsonProperty("ParentId")
    public void setParentId(String ParentId) {
        this.ParentId = ParentId;
    }

    // LoginHistoryId
    private String LoginHistoryId;

    @JsonProperty("LoginHistoryId")
    public String getLoginHistoryId() {
        return this.LoginHistoryId;
    }

    @JsonProperty("LoginHistoryId")
    public void setLoginHistoryId(String LoginHistoryId) {
        this.LoginHistoryId = LoginHistoryId;
    }

}
