/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject AuthConfig
 */
@XStreamAlias("AuthConfig")
public class AuthConfig extends AbstractSObjectBase {

    // DeveloperName
    private String DeveloperName;

    @JsonProperty("DeveloperName")
    public String getDeveloperName() {
        return this.DeveloperName;
    }

    @JsonProperty("DeveloperName")
    public void setDeveloperName(String DeveloperName) {
        this.DeveloperName = DeveloperName;
    }

    // Language
    @XStreamConverter(PicklistEnumConverter.class)
    private LanguageEnum Language;

    @JsonProperty("Language")
    public LanguageEnum getLanguage() {
        return this.Language;
    }

    @JsonProperty("Language")
    public void setLanguage(LanguageEnum Language) {
        this.Language = Language;
    }

    // MasterLabel
    private String MasterLabel;

    @JsonProperty("MasterLabel")
    public String getMasterLabel() {
        return this.MasterLabel;
    }

    @JsonProperty("MasterLabel")
    public void setMasterLabel(String MasterLabel) {
        this.MasterLabel = MasterLabel;
    }

    // NamespacePrefix
    private String NamespacePrefix;

    @JsonProperty("NamespacePrefix")
    public String getNamespacePrefix() {
        return this.NamespacePrefix;
    }

    @JsonProperty("NamespacePrefix")
    public void setNamespacePrefix(String NamespacePrefix) {
        this.NamespacePrefix = NamespacePrefix;
    }

    // Url
    private String Url;

    @JsonProperty("Url")
    public String getUrl() {
        return this.Url;
    }

    @JsonProperty("Url")
    public void setUrl(String Url) {
        this.Url = Url;
    }

    // AuthOptionsUsernamePassword
    private Boolean AuthOptionsUsernamePassword;

    @JsonProperty("AuthOptionsUsernamePassword")
    public Boolean getAuthOptionsUsernamePassword() {
        return this.AuthOptionsUsernamePassword;
    }

    @JsonProperty("AuthOptionsUsernamePassword")
    public void setAuthOptionsUsernamePassword(Boolean AuthOptionsUsernamePassword) {
        this.AuthOptionsUsernamePassword = AuthOptionsUsernamePassword;
    }

    // AuthOptionsSaml
    private Boolean AuthOptionsSaml;

    @JsonProperty("AuthOptionsSaml")
    public Boolean getAuthOptionsSaml() {
        return this.AuthOptionsSaml;
    }

    @JsonProperty("AuthOptionsSaml")
    public void setAuthOptionsSaml(Boolean AuthOptionsSaml) {
        this.AuthOptionsSaml = AuthOptionsSaml;
    }

    // AuthOptionsAuthProvider
    private Boolean AuthOptionsAuthProvider;

    @JsonProperty("AuthOptionsAuthProvider")
    public Boolean getAuthOptionsAuthProvider() {
        return this.AuthOptionsAuthProvider;
    }

    @JsonProperty("AuthOptionsAuthProvider")
    public void setAuthOptionsAuthProvider(Boolean AuthOptionsAuthProvider) {
        this.AuthOptionsAuthProvider = AuthOptionsAuthProvider;
    }

    // IsActive
    private Boolean IsActive;

    @JsonProperty("IsActive")
    public Boolean getIsActive() {
        return this.IsActive;
    }

    @JsonProperty("IsActive")
    public void setIsActive(Boolean IsActive) {
        this.IsActive = IsActive;
    }

    // Type
    @XStreamConverter(PicklistEnumConverter.class)
    private TypeEnum Type;

    @JsonProperty("Type")
    public TypeEnum getType() {
        return this.Type;
    }

    @JsonProperty("Type")
    public void setType(TypeEnum Type) {
        this.Type = Type;
    }

}
