/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BlankValueBehavior
 */
public enum BlankValueBehaviorEnum {

    // MatchBlanks
    MATCHBLANKS("MatchBlanks"),
    // NullNotAllowed
    NULLNOTALLOWED("NullNotAllowed");

    final String value;

    private BlankValueBehaviorEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BlankValueBehaviorEnum fromValue(String value) {
        for (BlankValueBehaviorEnum e : BlankValueBehaviorEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
