/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject ContentDistribution
 */
@XStreamAlias("ContentDistribution")
public class ContentDistribution extends AbstractSObjectBase {

    // ContentVersionId
    private String ContentVersionId;

    @JsonProperty("ContentVersionId")
    public String getContentVersionId() {
        return this.ContentVersionId;
    }

    @JsonProperty("ContentVersionId")
    public void setContentVersionId(String ContentVersionId) {
        this.ContentVersionId = ContentVersionId;
    }

    // ContentDocumentId
    private String ContentDocumentId;

    @JsonProperty("ContentDocumentId")
    public String getContentDocumentId() {
        return this.ContentDocumentId;
    }

    @JsonProperty("ContentDocumentId")
    public void setContentDocumentId(String ContentDocumentId) {
        this.ContentDocumentId = ContentDocumentId;
    }

    // RelatedRecordId
    private String RelatedRecordId;

    @JsonProperty("RelatedRecordId")
    public String getRelatedRecordId() {
        return this.RelatedRecordId;
    }

    @JsonProperty("RelatedRecordId")
    public void setRelatedRecordId(String RelatedRecordId) {
        this.RelatedRecordId = RelatedRecordId;
    }

    // PreferencesAllowPDFDownload
    private Boolean PreferencesAllowPDFDownload;

    @JsonProperty("PreferencesAllowPDFDownload")
    public Boolean getPreferencesAllowPDFDownload() {
        return this.PreferencesAllowPDFDownload;
    }

    @JsonProperty("PreferencesAllowPDFDownload")
    public void setPreferencesAllowPDFDownload(Boolean PreferencesAllowPDFDownload) {
        this.PreferencesAllowPDFDownload = PreferencesAllowPDFDownload;
    }

    // PreferencesAllowOriginalDownload
    private Boolean PreferencesAllowOriginalDownload;

    @JsonProperty("PreferencesAllowOriginalDownload")
    public Boolean getPreferencesAllowOriginalDownload() {
        return this.PreferencesAllowOriginalDownload;
    }

    @JsonProperty("PreferencesAllowOriginalDownload")
    public void setPreferencesAllowOriginalDownload(Boolean PreferencesAllowOriginalDownload) {
        this.PreferencesAllowOriginalDownload = PreferencesAllowOriginalDownload;
    }

    // PreferencesPasswordRequired
    private Boolean PreferencesPasswordRequired;

    @JsonProperty("PreferencesPasswordRequired")
    public Boolean getPreferencesPasswordRequired() {
        return this.PreferencesPasswordRequired;
    }

    @JsonProperty("PreferencesPasswordRequired")
    public void setPreferencesPasswordRequired(Boolean PreferencesPasswordRequired) {
        this.PreferencesPasswordRequired = PreferencesPasswordRequired;
    }

    // PreferencesNotifyOnVisit
    private Boolean PreferencesNotifyOnVisit;

    @JsonProperty("PreferencesNotifyOnVisit")
    public Boolean getPreferencesNotifyOnVisit() {
        return this.PreferencesNotifyOnVisit;
    }

    @JsonProperty("PreferencesNotifyOnVisit")
    public void setPreferencesNotifyOnVisit(Boolean PreferencesNotifyOnVisit) {
        this.PreferencesNotifyOnVisit = PreferencesNotifyOnVisit;
    }

    // PreferencesLinkLatestVersion
    private Boolean PreferencesLinkLatestVersion;

    @JsonProperty("PreferencesLinkLatestVersion")
    public Boolean getPreferencesLinkLatestVersion() {
        return this.PreferencesLinkLatestVersion;
    }

    @JsonProperty("PreferencesLinkLatestVersion")
    public void setPreferencesLinkLatestVersion(Boolean PreferencesLinkLatestVersion) {
        this.PreferencesLinkLatestVersion = PreferencesLinkLatestVersion;
    }

    // PreferencesAllowViewInBrowser
    private Boolean PreferencesAllowViewInBrowser;

    @JsonProperty("PreferencesAllowViewInBrowser")
    public Boolean getPreferencesAllowViewInBrowser() {
        return this.PreferencesAllowViewInBrowser;
    }

    @JsonProperty("PreferencesAllowViewInBrowser")
    public void setPreferencesAllowViewInBrowser(Boolean PreferencesAllowViewInBrowser) {
        this.PreferencesAllowViewInBrowser = PreferencesAllowViewInBrowser;
    }

    // PreferencesExpires
    private Boolean PreferencesExpires;

    @JsonProperty("PreferencesExpires")
    public Boolean getPreferencesExpires() {
        return this.PreferencesExpires;
    }

    @JsonProperty("PreferencesExpires")
    public void setPreferencesExpires(Boolean PreferencesExpires) {
        this.PreferencesExpires = PreferencesExpires;
    }

    // PreferencesNotifyRndtnComplete
    private Boolean PreferencesNotifyRndtnComplete;

    @JsonProperty("PreferencesNotifyRndtnComplete")
    public Boolean getPreferencesNotifyRndtnComplete() {
        return this.PreferencesNotifyRndtnComplete;
    }

    @JsonProperty("PreferencesNotifyRndtnComplete")
    public void setPreferencesNotifyRndtnComplete(Boolean PreferencesNotifyRndtnComplete) {
        this.PreferencesNotifyRndtnComplete = PreferencesNotifyRndtnComplete;
    }

    // ExpiryDate
    private org.joda.time.DateTime ExpiryDate;

    @JsonProperty("ExpiryDate")
    public org.joda.time.DateTime getExpiryDate() {
        return this.ExpiryDate;
    }

    @JsonProperty("ExpiryDate")
    public void setExpiryDate(org.joda.time.DateTime ExpiryDate) {
        this.ExpiryDate = ExpiryDate;
    }

    // Password
    private String Password;

    @JsonProperty("Password")
    public String getPassword() {
        return this.Password;
    }

    @JsonProperty("Password")
    public void setPassword(String Password) {
        this.Password = Password;
    }

    // ViewCount
    private Integer ViewCount;

    @JsonProperty("ViewCount")
    public Integer getViewCount() {
        return this.ViewCount;
    }

    @JsonProperty("ViewCount")
    public void setViewCount(Integer ViewCount) {
        this.ViewCount = ViewCount;
    }

    // FirstViewDate
    private org.joda.time.DateTime FirstViewDate;

    @JsonProperty("FirstViewDate")
    public org.joda.time.DateTime getFirstViewDate() {
        return this.FirstViewDate;
    }

    @JsonProperty("FirstViewDate")
    public void setFirstViewDate(org.joda.time.DateTime FirstViewDate) {
        this.FirstViewDate = FirstViewDate;
    }

    // LastViewDate
    private org.joda.time.DateTime LastViewDate;

    @JsonProperty("LastViewDate")
    public org.joda.time.DateTime getLastViewDate() {
        return this.LastViewDate;
    }

    @JsonProperty("LastViewDate")
    public void setLastViewDate(org.joda.time.DateTime LastViewDate) {
        this.LastViewDate = LastViewDate;
    }

    // DistributionPublicUrl
    private String DistributionPublicUrl;

    @JsonProperty("DistributionPublicUrl")
    public String getDistributionPublicUrl() {
        return this.DistributionPublicUrl;
    }

    @JsonProperty("DistributionPublicUrl")
    public void setDistributionPublicUrl(String DistributionPublicUrl) {
        this.DistributionPublicUrl = DistributionPublicUrl;
    }

}
