/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject DatacloudOwnedEntity
 */
@XStreamAlias("DatacloudOwnedEntity")
public class DatacloudOwnedEntity extends AbstractSObjectBase {

    // DataDotComKey
    private String DataDotComKey;

    @JsonProperty("DataDotComKey")
    public String getDataDotComKey() {
        return this.DataDotComKey;
    }

    @JsonProperty("DataDotComKey")
    public void setDataDotComKey(String DataDotComKey) {
        this.DataDotComKey = DataDotComKey;
    }

    // DatacloudEntityType
    @XStreamConverter(PicklistEnumConverter.class)
    private DatacloudEntityTypeEnum DatacloudEntityType;

    @JsonProperty("DatacloudEntityType")
    public DatacloudEntityTypeEnum getDatacloudEntityType() {
        return this.DatacloudEntityType;
    }

    @JsonProperty("DatacloudEntityType")
    public void setDatacloudEntityType(DatacloudEntityTypeEnum DatacloudEntityType) {
        this.DatacloudEntityType = DatacloudEntityType;
    }

    // UserId
    private String UserId;

    @JsonProperty("UserId")
    public String getUserId() {
        return this.UserId;
    }

    @JsonProperty("UserId")
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    // PurchaseUsageId
    private String PurchaseUsageId;

    @JsonProperty("PurchaseUsageId")
    public String getPurchaseUsageId() {
        return this.PurchaseUsageId;
    }

    @JsonProperty("PurchaseUsageId")
    public void setPurchaseUsageId(String PurchaseUsageId) {
        this.PurchaseUsageId = PurchaseUsageId;
    }

    // PurchaseType
    @XStreamConverter(PicklistEnumConverter.class)
    private PurchaseTypeEnum PurchaseType;

    @JsonProperty("PurchaseType")
    public PurchaseTypeEnum getPurchaseType() {
        return this.PurchaseType;
    }

    @JsonProperty("PurchaseType")
    public void setPurchaseType(PurchaseTypeEnum PurchaseType) {
        this.PurchaseType = PurchaseType;
    }

}
