/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist JobType
 */
public enum JobTypeEnum {

    // 1
    _1("1"),
    // 3
    _3("3"),
    // 4
    _4("4"),
    // 7
    _7("7"),
    // 8
    _8("8"),
    // 9
    _9("9"),
    // A
    A("A");

    final String value;

    private JobTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static JobTypeEnum fromValue(String value) {
        for (JobTypeEnum e : JobTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
