/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri May 27 17:39:27 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject PermissionSetLicense
 */
@XStreamAlias("PermissionSetLicense")
public class PermissionSetLicense extends AbstractSObjectBase {

    // DeveloperName
    private String DeveloperName;

    @JsonProperty("DeveloperName")
    public String getDeveloperName() {
        return this.DeveloperName;
    }

    @JsonProperty("DeveloperName")
    public void setDeveloperName(String DeveloperName) {
        this.DeveloperName = DeveloperName;
    }

    // Language
    @XStreamConverter(PicklistEnumConverter.class)
    private LanguageEnum Language;

    @JsonProperty("Language")
    public LanguageEnum getLanguage() {
        return this.Language;
    }

    @JsonProperty("Language")
    public void setLanguage(LanguageEnum Language) {
        this.Language = Language;
    }

    // MasterLabel
    private String MasterLabel;

    @JsonProperty("MasterLabel")
    public String getMasterLabel() {
        return this.MasterLabel;
    }

    @JsonProperty("MasterLabel")
    public void setMasterLabel(String MasterLabel) {
        this.MasterLabel = MasterLabel;
    }

    // PermissionSetLicenseKey
    private String PermissionSetLicenseKey;

    @JsonProperty("PermissionSetLicenseKey")
    public String getPermissionSetLicenseKey() {
        return this.PermissionSetLicenseKey;
    }

    @JsonProperty("PermissionSetLicenseKey")
    public void setPermissionSetLicenseKey(String PermissionSetLicenseKey) {
        this.PermissionSetLicenseKey = PermissionSetLicenseKey;
    }

    // TotalLicenses
    private Integer TotalLicenses;

    @JsonProperty("TotalLicenses")
    public Integer getTotalLicenses() {
        return this.TotalLicenses;
    }

    @JsonProperty("TotalLicenses")
    public void setTotalLicenses(Integer TotalLicenses) {
        this.TotalLicenses = TotalLicenses;
    }

    // Status
    @XStreamConverter(PicklistEnumConverter.class)
    private StatusEnum Status;

    @JsonProperty("Status")
    public StatusEnum getStatus() {
        return this.Status;
    }

    @JsonProperty("Status")
    public void setStatus(StatusEnum Status) {
        this.Status = Status;
    }

    // ExpirationDate
    private org.joda.time.DateTime ExpirationDate;

    @JsonProperty("ExpirationDate")
    public org.joda.time.DateTime getExpirationDate() {
        return this.ExpirationDate;
    }

    @JsonProperty("ExpirationDate")
    public void setExpirationDate(org.joda.time.DateTime ExpirationDate) {
        this.ExpirationDate = ExpirationDate;
    }

    // MaximumPermissionsEmailSingle
    private Boolean MaximumPermissionsEmailSingle;

    @JsonProperty("MaximumPermissionsEmailSingle")
    public Boolean getMaximumPermissionsEmailSingle() {
        return this.MaximumPermissionsEmailSingle;
    }

    @JsonProperty("MaximumPermissionsEmailSingle")
    public void setMaximumPermissionsEmailSingle(Boolean MaximumPermissionsEmailSingle) {
        this.MaximumPermissionsEmailSingle = MaximumPermissionsEmailSingle;
    }

    // MaximumPermissionsEmailMass
    private Boolean MaximumPermissionsEmailMass;

    @JsonProperty("MaximumPermissionsEmailMass")
    public Boolean getMaximumPermissionsEmailMass() {
        return this.MaximumPermissionsEmailMass;
    }

    @JsonProperty("MaximumPermissionsEmailMass")
    public void setMaximumPermissionsEmailMass(Boolean MaximumPermissionsEmailMass) {
        this.MaximumPermissionsEmailMass = MaximumPermissionsEmailMass;
    }

    // MaximumPermissionsEditTask
    private Boolean MaximumPermissionsEditTask;

    @JsonProperty("MaximumPermissionsEditTask")
    public Boolean getMaximumPermissionsEditTask() {
        return this.MaximumPermissionsEditTask;
    }

    @JsonProperty("MaximumPermissionsEditTask")
    public void setMaximumPermissionsEditTask(Boolean MaximumPermissionsEditTask) {
        this.MaximumPermissionsEditTask = MaximumPermissionsEditTask;
    }

    // MaximumPermissionsEditEvent
    private Boolean MaximumPermissionsEditEvent;

    @JsonProperty("MaximumPermissionsEditEvent")
    public Boolean getMaximumPermissionsEditEvent() {
        return this.MaximumPermissionsEditEvent;
    }

    @JsonProperty("MaximumPermissionsEditEvent")
    public void setMaximumPermissionsEditEvent(Boolean MaximumPermissionsEditEvent) {
        this.MaximumPermissionsEditEvent = MaximumPermissionsEditEvent;
    }

    // MaximumPermissionsExportReport
    private Boolean MaximumPermissionsExportReport;

    @JsonProperty("MaximumPermissionsExportReport")
    public Boolean getMaximumPermissionsExportReport() {
        return this.MaximumPermissionsExportReport;
    }

    @JsonProperty("MaximumPermissionsExportReport")
    public void setMaximumPermissionsExportReport(Boolean MaximumPermissionsExportReport) {
        this.MaximumPermissionsExportReport = MaximumPermissionsExportReport;
    }

    // MaximumPermissionsImportPersonal
    private Boolean MaximumPermissionsImportPersonal;

    @JsonProperty("MaximumPermissionsImportPersonal")
    public Boolean getMaximumPermissionsImportPersonal() {
        return this.MaximumPermissionsImportPersonal;
    }

    @JsonProperty("MaximumPermissionsImportPersonal")
    public void setMaximumPermissionsImportPersonal(Boolean MaximumPermissionsImportPersonal) {
        this.MaximumPermissionsImportPersonal = MaximumPermissionsImportPersonal;
    }

    // MaximumPermissionsManageUsers
    private Boolean MaximumPermissionsManageUsers;

    @JsonProperty("MaximumPermissionsManageUsers")
    public Boolean getMaximumPermissionsManageUsers() {
        return this.MaximumPermissionsManageUsers;
    }

    @JsonProperty("MaximumPermissionsManageUsers")
    public void setMaximumPermissionsManageUsers(Boolean MaximumPermissionsManageUsers) {
        this.MaximumPermissionsManageUsers = MaximumPermissionsManageUsers;
    }

    // MaximumPermissionsEditPublicTemplates
    private Boolean MaximumPermissionsEditPublicTemplates;

    @JsonProperty("MaximumPermissionsEditPublicTemplates")
    public Boolean getMaximumPermissionsEditPublicTemplates() {
        return this.MaximumPermissionsEditPublicTemplates;
    }

    @JsonProperty("MaximumPermissionsEditPublicTemplates")
    public void setMaximumPermissionsEditPublicTemplates(Boolean MaximumPermissionsEditPublicTemplates) {
        this.MaximumPermissionsEditPublicTemplates = MaximumPermissionsEditPublicTemplates;
    }

    // MaximumPermissionsModifyAllData
    private Boolean MaximumPermissionsModifyAllData;

    @JsonProperty("MaximumPermissionsModifyAllData")
    public Boolean getMaximumPermissionsModifyAllData() {
        return this.MaximumPermissionsModifyAllData;
    }

    @JsonProperty("MaximumPermissionsModifyAllData")
    public void setMaximumPermissionsModifyAllData(Boolean MaximumPermissionsModifyAllData) {
        this.MaximumPermissionsModifyAllData = MaximumPermissionsModifyAllData;
    }

    // MaximumPermissionsManageCases
    private Boolean MaximumPermissionsManageCases;

    @JsonProperty("MaximumPermissionsManageCases")
    public Boolean getMaximumPermissionsManageCases() {
        return this.MaximumPermissionsManageCases;
    }

    @JsonProperty("MaximumPermissionsManageCases")
    public void setMaximumPermissionsManageCases(Boolean MaximumPermissionsManageCases) {
        this.MaximumPermissionsManageCases = MaximumPermissionsManageCases;
    }

    // MaximumPermissionsMassInlineEdit
    private Boolean MaximumPermissionsMassInlineEdit;

    @JsonProperty("MaximumPermissionsMassInlineEdit")
    public Boolean getMaximumPermissionsMassInlineEdit() {
        return this.MaximumPermissionsMassInlineEdit;
    }

    @JsonProperty("MaximumPermissionsMassInlineEdit")
    public void setMaximumPermissionsMassInlineEdit(Boolean MaximumPermissionsMassInlineEdit) {
        this.MaximumPermissionsMassInlineEdit = MaximumPermissionsMassInlineEdit;
    }

    // MaximumPermissionsEditKnowledge
    private Boolean MaximumPermissionsEditKnowledge;

    @JsonProperty("MaximumPermissionsEditKnowledge")
    public Boolean getMaximumPermissionsEditKnowledge() {
        return this.MaximumPermissionsEditKnowledge;
    }

    @JsonProperty("MaximumPermissionsEditKnowledge")
    public void setMaximumPermissionsEditKnowledge(Boolean MaximumPermissionsEditKnowledge) {
        this.MaximumPermissionsEditKnowledge = MaximumPermissionsEditKnowledge;
    }

    // MaximumPermissionsManageKnowledge
    private Boolean MaximumPermissionsManageKnowledge;

    @JsonProperty("MaximumPermissionsManageKnowledge")
    public Boolean getMaximumPermissionsManageKnowledge() {
        return this.MaximumPermissionsManageKnowledge;
    }

    @JsonProperty("MaximumPermissionsManageKnowledge")
    public void setMaximumPermissionsManageKnowledge(Boolean MaximumPermissionsManageKnowledge) {
        this.MaximumPermissionsManageKnowledge = MaximumPermissionsManageKnowledge;
    }

    // MaximumPermissionsManageSolutions
    private Boolean MaximumPermissionsManageSolutions;

    @JsonProperty("MaximumPermissionsManageSolutions")
    public Boolean getMaximumPermissionsManageSolutions() {
        return this.MaximumPermissionsManageSolutions;
    }

    @JsonProperty("MaximumPermissionsManageSolutions")
    public void setMaximumPermissionsManageSolutions(Boolean MaximumPermissionsManageSolutions) {
        this.MaximumPermissionsManageSolutions = MaximumPermissionsManageSolutions;
    }

    // MaximumPermissionsCustomizeApplication
    private Boolean MaximumPermissionsCustomizeApplication;

    @JsonProperty("MaximumPermissionsCustomizeApplication")
    public Boolean getMaximumPermissionsCustomizeApplication() {
        return this.MaximumPermissionsCustomizeApplication;
    }

    @JsonProperty("MaximumPermissionsCustomizeApplication")
    public void setMaximumPermissionsCustomizeApplication(Boolean MaximumPermissionsCustomizeApplication) {
        this.MaximumPermissionsCustomizeApplication = MaximumPermissionsCustomizeApplication;
    }

    // MaximumPermissionsEditReadonlyFields
    private Boolean MaximumPermissionsEditReadonlyFields;

    @JsonProperty("MaximumPermissionsEditReadonlyFields")
    public Boolean getMaximumPermissionsEditReadonlyFields() {
        return this.MaximumPermissionsEditReadonlyFields;
    }

    @JsonProperty("MaximumPermissionsEditReadonlyFields")
    public void setMaximumPermissionsEditReadonlyFields(Boolean MaximumPermissionsEditReadonlyFields) {
        this.MaximumPermissionsEditReadonlyFields = MaximumPermissionsEditReadonlyFields;
    }

    // MaximumPermissionsRunReports
    private Boolean MaximumPermissionsRunReports;

    @JsonProperty("MaximumPermissionsRunReports")
    public Boolean getMaximumPermissionsRunReports() {
        return this.MaximumPermissionsRunReports;
    }

    @JsonProperty("MaximumPermissionsRunReports")
    public void setMaximumPermissionsRunReports(Boolean MaximumPermissionsRunReports) {
        this.MaximumPermissionsRunReports = MaximumPermissionsRunReports;
    }

    // MaximumPermissionsViewSetup
    private Boolean MaximumPermissionsViewSetup;

    @JsonProperty("MaximumPermissionsViewSetup")
    public Boolean getMaximumPermissionsViewSetup() {
        return this.MaximumPermissionsViewSetup;
    }

    @JsonProperty("MaximumPermissionsViewSetup")
    public void setMaximumPermissionsViewSetup(Boolean MaximumPermissionsViewSetup) {
        this.MaximumPermissionsViewSetup = MaximumPermissionsViewSetup;
    }

    // MaximumPermissionsTransferAnyEntity
    private Boolean MaximumPermissionsTransferAnyEntity;

    @JsonProperty("MaximumPermissionsTransferAnyEntity")
    public Boolean getMaximumPermissionsTransferAnyEntity() {
        return this.MaximumPermissionsTransferAnyEntity;
    }

    @JsonProperty("MaximumPermissionsTransferAnyEntity")
    public void setMaximumPermissionsTransferAnyEntity(Boolean MaximumPermissionsTransferAnyEntity) {
        this.MaximumPermissionsTransferAnyEntity = MaximumPermissionsTransferAnyEntity;
    }

    // MaximumPermissionsNewReportBuilder
    private Boolean MaximumPermissionsNewReportBuilder;

    @JsonProperty("MaximumPermissionsNewReportBuilder")
    public Boolean getMaximumPermissionsNewReportBuilder() {
        return this.MaximumPermissionsNewReportBuilder;
    }

    @JsonProperty("MaximumPermissionsNewReportBuilder")
    public void setMaximumPermissionsNewReportBuilder(Boolean MaximumPermissionsNewReportBuilder) {
        this.MaximumPermissionsNewReportBuilder = MaximumPermissionsNewReportBuilder;
    }

    // MaximumPermissionsActivateContract
    private Boolean MaximumPermissionsActivateContract;

    @JsonProperty("MaximumPermissionsActivateContract")
    public Boolean getMaximumPermissionsActivateContract() {
        return this.MaximumPermissionsActivateContract;
    }

    @JsonProperty("MaximumPermissionsActivateContract")
    public void setMaximumPermissionsActivateContract(Boolean MaximumPermissionsActivateContract) {
        this.MaximumPermissionsActivateContract = MaximumPermissionsActivateContract;
    }

    // MaximumPermissionsActivateOrder
    private Boolean MaximumPermissionsActivateOrder;

    @JsonProperty("MaximumPermissionsActivateOrder")
    public Boolean getMaximumPermissionsActivateOrder() {
        return this.MaximumPermissionsActivateOrder;
    }

    @JsonProperty("MaximumPermissionsActivateOrder")
    public void setMaximumPermissionsActivateOrder(Boolean MaximumPermissionsActivateOrder) {
        this.MaximumPermissionsActivateOrder = MaximumPermissionsActivateOrder;
    }

    // MaximumPermissionsImportLeads
    private Boolean MaximumPermissionsImportLeads;

    @JsonProperty("MaximumPermissionsImportLeads")
    public Boolean getMaximumPermissionsImportLeads() {
        return this.MaximumPermissionsImportLeads;
    }

    @JsonProperty("MaximumPermissionsImportLeads")
    public void setMaximumPermissionsImportLeads(Boolean MaximumPermissionsImportLeads) {
        this.MaximumPermissionsImportLeads = MaximumPermissionsImportLeads;
    }

    // MaximumPermissionsManageLeads
    private Boolean MaximumPermissionsManageLeads;

    @JsonProperty("MaximumPermissionsManageLeads")
    public Boolean getMaximumPermissionsManageLeads() {
        return this.MaximumPermissionsManageLeads;
    }

    @JsonProperty("MaximumPermissionsManageLeads")
    public void setMaximumPermissionsManageLeads(Boolean MaximumPermissionsManageLeads) {
        this.MaximumPermissionsManageLeads = MaximumPermissionsManageLeads;
    }

    // MaximumPermissionsTransferAnyLead
    private Boolean MaximumPermissionsTransferAnyLead;

    @JsonProperty("MaximumPermissionsTransferAnyLead")
    public Boolean getMaximumPermissionsTransferAnyLead() {
        return this.MaximumPermissionsTransferAnyLead;
    }

    @JsonProperty("MaximumPermissionsTransferAnyLead")
    public void setMaximumPermissionsTransferAnyLead(Boolean MaximumPermissionsTransferAnyLead) {
        this.MaximumPermissionsTransferAnyLead = MaximumPermissionsTransferAnyLead;
    }

    // MaximumPermissionsViewAllData
    private Boolean MaximumPermissionsViewAllData;

    @JsonProperty("MaximumPermissionsViewAllData")
    public Boolean getMaximumPermissionsViewAllData() {
        return this.MaximumPermissionsViewAllData;
    }

    @JsonProperty("MaximumPermissionsViewAllData")
    public void setMaximumPermissionsViewAllData(Boolean MaximumPermissionsViewAllData) {
        this.MaximumPermissionsViewAllData = MaximumPermissionsViewAllData;
    }

    // MaximumPermissionsEditPublicDocuments
    private Boolean MaximumPermissionsEditPublicDocuments;

    @JsonProperty("MaximumPermissionsEditPublicDocuments")
    public Boolean getMaximumPermissionsEditPublicDocuments() {
        return this.MaximumPermissionsEditPublicDocuments;
    }

    @JsonProperty("MaximumPermissionsEditPublicDocuments")
    public void setMaximumPermissionsEditPublicDocuments(Boolean MaximumPermissionsEditPublicDocuments) {
        this.MaximumPermissionsEditPublicDocuments = MaximumPermissionsEditPublicDocuments;
    }

    // MaximumPermissionsViewEncryptedData
    private Boolean MaximumPermissionsViewEncryptedData;

    @JsonProperty("MaximumPermissionsViewEncryptedData")
    public Boolean getMaximumPermissionsViewEncryptedData() {
        return this.MaximumPermissionsViewEncryptedData;
    }

    @JsonProperty("MaximumPermissionsViewEncryptedData")
    public void setMaximumPermissionsViewEncryptedData(Boolean MaximumPermissionsViewEncryptedData) {
        this.MaximumPermissionsViewEncryptedData = MaximumPermissionsViewEncryptedData;
    }

    // MaximumPermissionsEditBrandTemplates
    private Boolean MaximumPermissionsEditBrandTemplates;

    @JsonProperty("MaximumPermissionsEditBrandTemplates")
    public Boolean getMaximumPermissionsEditBrandTemplates() {
        return this.MaximumPermissionsEditBrandTemplates;
    }

    @JsonProperty("MaximumPermissionsEditBrandTemplates")
    public void setMaximumPermissionsEditBrandTemplates(Boolean MaximumPermissionsEditBrandTemplates) {
        this.MaximumPermissionsEditBrandTemplates = MaximumPermissionsEditBrandTemplates;
    }

    // MaximumPermissionsEditHtmlTemplates
    private Boolean MaximumPermissionsEditHtmlTemplates;

    @JsonProperty("MaximumPermissionsEditHtmlTemplates")
    public Boolean getMaximumPermissionsEditHtmlTemplates() {
        return this.MaximumPermissionsEditHtmlTemplates;
    }

    @JsonProperty("MaximumPermissionsEditHtmlTemplates")
    public void setMaximumPermissionsEditHtmlTemplates(Boolean MaximumPermissionsEditHtmlTemplates) {
        this.MaximumPermissionsEditHtmlTemplates = MaximumPermissionsEditHtmlTemplates;
    }

    // MaximumPermissionsChatterInternalUser
    private Boolean MaximumPermissionsChatterInternalUser;

    @JsonProperty("MaximumPermissionsChatterInternalUser")
    public Boolean getMaximumPermissionsChatterInternalUser() {
        return this.MaximumPermissionsChatterInternalUser;
    }

    @JsonProperty("MaximumPermissionsChatterInternalUser")
    public void setMaximumPermissionsChatterInternalUser(Boolean MaximumPermissionsChatterInternalUser) {
        this.MaximumPermissionsChatterInternalUser = MaximumPermissionsChatterInternalUser;
    }

    // MaximumPermissionsManageEncryptionKeys
    private Boolean MaximumPermissionsManageEncryptionKeys;

    @JsonProperty("MaximumPermissionsManageEncryptionKeys")
    public Boolean getMaximumPermissionsManageEncryptionKeys() {
        return this.MaximumPermissionsManageEncryptionKeys;
    }

    @JsonProperty("MaximumPermissionsManageEncryptionKeys")
    public void setMaximumPermissionsManageEncryptionKeys(Boolean MaximumPermissionsManageEncryptionKeys) {
        this.MaximumPermissionsManageEncryptionKeys = MaximumPermissionsManageEncryptionKeys;
    }

    // MaximumPermissionsDeleteActivatedContract
    private Boolean MaximumPermissionsDeleteActivatedContract;

    @JsonProperty("MaximumPermissionsDeleteActivatedContract")
    public Boolean getMaximumPermissionsDeleteActivatedContract() {
        return this.MaximumPermissionsDeleteActivatedContract;
    }

    @JsonProperty("MaximumPermissionsDeleteActivatedContract")
    public void setMaximumPermissionsDeleteActivatedContract(Boolean MaximumPermissionsDeleteActivatedContract) {
        this.MaximumPermissionsDeleteActivatedContract = MaximumPermissionsDeleteActivatedContract;
    }

    // MaximumPermissionsChatterInviteExternalUsers
    private Boolean MaximumPermissionsChatterInviteExternalUsers;

    @JsonProperty("MaximumPermissionsChatterInviteExternalUsers")
    public Boolean getMaximumPermissionsChatterInviteExternalUsers() {
        return this.MaximumPermissionsChatterInviteExternalUsers;
    }

    @JsonProperty("MaximumPermissionsChatterInviteExternalUsers")
    public void setMaximumPermissionsChatterInviteExternalUsers(Boolean MaximumPermissionsChatterInviteExternalUsers) {
        this.MaximumPermissionsChatterInviteExternalUsers = MaximumPermissionsChatterInviteExternalUsers;
    }

    // MaximumPermissionsSendSitRequests
    private Boolean MaximumPermissionsSendSitRequests;

    @JsonProperty("MaximumPermissionsSendSitRequests")
    public Boolean getMaximumPermissionsSendSitRequests() {
        return this.MaximumPermissionsSendSitRequests;
    }

    @JsonProperty("MaximumPermissionsSendSitRequests")
    public void setMaximumPermissionsSendSitRequests(Boolean MaximumPermissionsSendSitRequests) {
        this.MaximumPermissionsSendSitRequests = MaximumPermissionsSendSitRequests;
    }

    // MaximumPermissionsManageRemoteAccess
    private Boolean MaximumPermissionsManageRemoteAccess;

    @JsonProperty("MaximumPermissionsManageRemoteAccess")
    public Boolean getMaximumPermissionsManageRemoteAccess() {
        return this.MaximumPermissionsManageRemoteAccess;
    }

    @JsonProperty("MaximumPermissionsManageRemoteAccess")
    public void setMaximumPermissionsManageRemoteAccess(Boolean MaximumPermissionsManageRemoteAccess) {
        this.MaximumPermissionsManageRemoteAccess = MaximumPermissionsManageRemoteAccess;
    }

    // MaximumPermissionsCanUseNewDashboardBuilder
    private Boolean MaximumPermissionsCanUseNewDashboardBuilder;

    @JsonProperty("MaximumPermissionsCanUseNewDashboardBuilder")
    public Boolean getMaximumPermissionsCanUseNewDashboardBuilder() {
        return this.MaximumPermissionsCanUseNewDashboardBuilder;
    }

    @JsonProperty("MaximumPermissionsCanUseNewDashboardBuilder")
    public void setMaximumPermissionsCanUseNewDashboardBuilder(Boolean MaximumPermissionsCanUseNewDashboardBuilder) {
        this.MaximumPermissionsCanUseNewDashboardBuilder = MaximumPermissionsCanUseNewDashboardBuilder;
    }

    // MaximumPermissionsManageCategories
    private Boolean MaximumPermissionsManageCategories;

    @JsonProperty("MaximumPermissionsManageCategories")
    public Boolean getMaximumPermissionsManageCategories() {
        return this.MaximumPermissionsManageCategories;
    }

    @JsonProperty("MaximumPermissionsManageCategories")
    public void setMaximumPermissionsManageCategories(Boolean MaximumPermissionsManageCategories) {
        this.MaximumPermissionsManageCategories = MaximumPermissionsManageCategories;
    }

    // MaximumPermissionsConvertLeads
    private Boolean MaximumPermissionsConvertLeads;

    @JsonProperty("MaximumPermissionsConvertLeads")
    public Boolean getMaximumPermissionsConvertLeads() {
        return this.MaximumPermissionsConvertLeads;
    }

    @JsonProperty("MaximumPermissionsConvertLeads")
    public void setMaximumPermissionsConvertLeads(Boolean MaximumPermissionsConvertLeads) {
        this.MaximumPermissionsConvertLeads = MaximumPermissionsConvertLeads;
    }

    // MaximumPermissionsPasswordNeverExpires
    private Boolean MaximumPermissionsPasswordNeverExpires;

    @JsonProperty("MaximumPermissionsPasswordNeverExpires")
    public Boolean getMaximumPermissionsPasswordNeverExpires() {
        return this.MaximumPermissionsPasswordNeverExpires;
    }

    @JsonProperty("MaximumPermissionsPasswordNeverExpires")
    public void setMaximumPermissionsPasswordNeverExpires(Boolean MaximumPermissionsPasswordNeverExpires) {
        this.MaximumPermissionsPasswordNeverExpires = MaximumPermissionsPasswordNeverExpires;
    }

    // MaximumPermissionsUseTeamReassignWizards
    private Boolean MaximumPermissionsUseTeamReassignWizards;

    @JsonProperty("MaximumPermissionsUseTeamReassignWizards")
    public Boolean getMaximumPermissionsUseTeamReassignWizards() {
        return this.MaximumPermissionsUseTeamReassignWizards;
    }

    @JsonProperty("MaximumPermissionsUseTeamReassignWizards")
    public void setMaximumPermissionsUseTeamReassignWizards(Boolean MaximumPermissionsUseTeamReassignWizards) {
        this.MaximumPermissionsUseTeamReassignWizards = MaximumPermissionsUseTeamReassignWizards;
    }

    // MaximumPermissionsEditActivatedOrders
    private Boolean MaximumPermissionsEditActivatedOrders;

    @JsonProperty("MaximumPermissionsEditActivatedOrders")
    public Boolean getMaximumPermissionsEditActivatedOrders() {
        return this.MaximumPermissionsEditActivatedOrders;
    }

    @JsonProperty("MaximumPermissionsEditActivatedOrders")
    public void setMaximumPermissionsEditActivatedOrders(Boolean MaximumPermissionsEditActivatedOrders) {
        this.MaximumPermissionsEditActivatedOrders = MaximumPermissionsEditActivatedOrders;
    }

    // MaximumPermissionsInstallPackaging
    private Boolean MaximumPermissionsInstallPackaging;

    @JsonProperty("MaximumPermissionsInstallPackaging")
    public Boolean getMaximumPermissionsInstallPackaging() {
        return this.MaximumPermissionsInstallPackaging;
    }

    @JsonProperty("MaximumPermissionsInstallPackaging")
    public void setMaximumPermissionsInstallPackaging(Boolean MaximumPermissionsInstallPackaging) {
        this.MaximumPermissionsInstallPackaging = MaximumPermissionsInstallPackaging;
    }

    // MaximumPermissionsPublishPackaging
    private Boolean MaximumPermissionsPublishPackaging;

    @JsonProperty("MaximumPermissionsPublishPackaging")
    public Boolean getMaximumPermissionsPublishPackaging() {
        return this.MaximumPermissionsPublishPackaging;
    }

    @JsonProperty("MaximumPermissionsPublishPackaging")
    public void setMaximumPermissionsPublishPackaging(Boolean MaximumPermissionsPublishPackaging) {
        this.MaximumPermissionsPublishPackaging = MaximumPermissionsPublishPackaging;
    }

    // MaximumPermissionsChatterOwnGroups
    private Boolean MaximumPermissionsChatterOwnGroups;

    @JsonProperty("MaximumPermissionsChatterOwnGroups")
    public Boolean getMaximumPermissionsChatterOwnGroups() {
        return this.MaximumPermissionsChatterOwnGroups;
    }

    @JsonProperty("MaximumPermissionsChatterOwnGroups")
    public void setMaximumPermissionsChatterOwnGroups(Boolean MaximumPermissionsChatterOwnGroups) {
        this.MaximumPermissionsChatterOwnGroups = MaximumPermissionsChatterOwnGroups;
    }

    // MaximumPermissionsEditOppLineItemUnitPrice
    private Boolean MaximumPermissionsEditOppLineItemUnitPrice;

    @JsonProperty("MaximumPermissionsEditOppLineItemUnitPrice")
    public Boolean getMaximumPermissionsEditOppLineItemUnitPrice() {
        return this.MaximumPermissionsEditOppLineItemUnitPrice;
    }

    @JsonProperty("MaximumPermissionsEditOppLineItemUnitPrice")
    public void setMaximumPermissionsEditOppLineItemUnitPrice(Boolean MaximumPermissionsEditOppLineItemUnitPrice) {
        this.MaximumPermissionsEditOppLineItemUnitPrice = MaximumPermissionsEditOppLineItemUnitPrice;
    }

    // MaximumPermissionsCreatePackaging
    private Boolean MaximumPermissionsCreatePackaging;

    @JsonProperty("MaximumPermissionsCreatePackaging")
    public Boolean getMaximumPermissionsCreatePackaging() {
        return this.MaximumPermissionsCreatePackaging;
    }

    @JsonProperty("MaximumPermissionsCreatePackaging")
    public void setMaximumPermissionsCreatePackaging(Boolean MaximumPermissionsCreatePackaging) {
        this.MaximumPermissionsCreatePackaging = MaximumPermissionsCreatePackaging;
    }

    // MaximumPermissionsBulkApiHardDelete
    private Boolean MaximumPermissionsBulkApiHardDelete;

    @JsonProperty("MaximumPermissionsBulkApiHardDelete")
    public Boolean getMaximumPermissionsBulkApiHardDelete() {
        return this.MaximumPermissionsBulkApiHardDelete;
    }

    @JsonProperty("MaximumPermissionsBulkApiHardDelete")
    public void setMaximumPermissionsBulkApiHardDelete(Boolean MaximumPermissionsBulkApiHardDelete) {
        this.MaximumPermissionsBulkApiHardDelete = MaximumPermissionsBulkApiHardDelete;
    }

    // MaximumPermissionsSolutionImport
    private Boolean MaximumPermissionsSolutionImport;

    @JsonProperty("MaximumPermissionsSolutionImport")
    public Boolean getMaximumPermissionsSolutionImport() {
        return this.MaximumPermissionsSolutionImport;
    }

    @JsonProperty("MaximumPermissionsSolutionImport")
    public void setMaximumPermissionsSolutionImport(Boolean MaximumPermissionsSolutionImport) {
        this.MaximumPermissionsSolutionImport = MaximumPermissionsSolutionImport;
    }

    // MaximumPermissionsManageCallCenters
    private Boolean MaximumPermissionsManageCallCenters;

    @JsonProperty("MaximumPermissionsManageCallCenters")
    public Boolean getMaximumPermissionsManageCallCenters() {
        return this.MaximumPermissionsManageCallCenters;
    }

    @JsonProperty("MaximumPermissionsManageCallCenters")
    public void setMaximumPermissionsManageCallCenters(Boolean MaximumPermissionsManageCallCenters) {
        this.MaximumPermissionsManageCallCenters = MaximumPermissionsManageCallCenters;
    }

    // MaximumPermissionsManageSynonyms
    private Boolean MaximumPermissionsManageSynonyms;

    @JsonProperty("MaximumPermissionsManageSynonyms")
    public Boolean getMaximumPermissionsManageSynonyms() {
        return this.MaximumPermissionsManageSynonyms;
    }

    @JsonProperty("MaximumPermissionsManageSynonyms")
    public void setMaximumPermissionsManageSynonyms(Boolean MaximumPermissionsManageSynonyms) {
        this.MaximumPermissionsManageSynonyms = MaximumPermissionsManageSynonyms;
    }

    // MaximumPermissionsViewContent
    private Boolean MaximumPermissionsViewContent;

    @JsonProperty("MaximumPermissionsViewContent")
    public Boolean getMaximumPermissionsViewContent() {
        return this.MaximumPermissionsViewContent;
    }

    @JsonProperty("MaximumPermissionsViewContent")
    public void setMaximumPermissionsViewContent(Boolean MaximumPermissionsViewContent) {
        this.MaximumPermissionsViewContent = MaximumPermissionsViewContent;
    }

    // MaximumPermissionsManageEmailClientConfig
    private Boolean MaximumPermissionsManageEmailClientConfig;

    @JsonProperty("MaximumPermissionsManageEmailClientConfig")
    public Boolean getMaximumPermissionsManageEmailClientConfig() {
        return this.MaximumPermissionsManageEmailClientConfig;
    }

    @JsonProperty("MaximumPermissionsManageEmailClientConfig")
    public void setMaximumPermissionsManageEmailClientConfig(Boolean MaximumPermissionsManageEmailClientConfig) {
        this.MaximumPermissionsManageEmailClientConfig = MaximumPermissionsManageEmailClientConfig;
    }

    // MaximumPermissionsEnableNotifications
    private Boolean MaximumPermissionsEnableNotifications;

    @JsonProperty("MaximumPermissionsEnableNotifications")
    public Boolean getMaximumPermissionsEnableNotifications() {
        return this.MaximumPermissionsEnableNotifications;
    }

    @JsonProperty("MaximumPermissionsEnableNotifications")
    public void setMaximumPermissionsEnableNotifications(Boolean MaximumPermissionsEnableNotifications) {
        this.MaximumPermissionsEnableNotifications = MaximumPermissionsEnableNotifications;
    }

    // MaximumPermissionsManageDataIntegrations
    private Boolean MaximumPermissionsManageDataIntegrations;

    @JsonProperty("MaximumPermissionsManageDataIntegrations")
    public Boolean getMaximumPermissionsManageDataIntegrations() {
        return this.MaximumPermissionsManageDataIntegrations;
    }

    @JsonProperty("MaximumPermissionsManageDataIntegrations")
    public void setMaximumPermissionsManageDataIntegrations(Boolean MaximumPermissionsManageDataIntegrations) {
        this.MaximumPermissionsManageDataIntegrations = MaximumPermissionsManageDataIntegrations;
    }

    // MaximumPermissionsDistributeFromPersWksp
    private Boolean MaximumPermissionsDistributeFromPersWksp;

    @JsonProperty("MaximumPermissionsDistributeFromPersWksp")
    public Boolean getMaximumPermissionsDistributeFromPersWksp() {
        return this.MaximumPermissionsDistributeFromPersWksp;
    }

    @JsonProperty("MaximumPermissionsDistributeFromPersWksp")
    public void setMaximumPermissionsDistributeFromPersWksp(Boolean MaximumPermissionsDistributeFromPersWksp) {
        this.MaximumPermissionsDistributeFromPersWksp = MaximumPermissionsDistributeFromPersWksp;
    }

    // MaximumPermissionsViewDataCategories
    private Boolean MaximumPermissionsViewDataCategories;

    @JsonProperty("MaximumPermissionsViewDataCategories")
    public Boolean getMaximumPermissionsViewDataCategories() {
        return this.MaximumPermissionsViewDataCategories;
    }

    @JsonProperty("MaximumPermissionsViewDataCategories")
    public void setMaximumPermissionsViewDataCategories(Boolean MaximumPermissionsViewDataCategories) {
        this.MaximumPermissionsViewDataCategories = MaximumPermissionsViewDataCategories;
    }

    // MaximumPermissionsManageDataCategories
    private Boolean MaximumPermissionsManageDataCategories;

    @JsonProperty("MaximumPermissionsManageDataCategories")
    public Boolean getMaximumPermissionsManageDataCategories() {
        return this.MaximumPermissionsManageDataCategories;
    }

    @JsonProperty("MaximumPermissionsManageDataCategories")
    public void setMaximumPermissionsManageDataCategories(Boolean MaximumPermissionsManageDataCategories) {
        this.MaximumPermissionsManageDataCategories = MaximumPermissionsManageDataCategories;
    }

    // MaximumPermissionsAuthorApex
    private Boolean MaximumPermissionsAuthorApex;

    @JsonProperty("MaximumPermissionsAuthorApex")
    public Boolean getMaximumPermissionsAuthorApex() {
        return this.MaximumPermissionsAuthorApex;
    }

    @JsonProperty("MaximumPermissionsAuthorApex")
    public void setMaximumPermissionsAuthorApex(Boolean MaximumPermissionsAuthorApex) {
        this.MaximumPermissionsAuthorApex = MaximumPermissionsAuthorApex;
    }

    // MaximumPermissionsManageMobile
    private Boolean MaximumPermissionsManageMobile;

    @JsonProperty("MaximumPermissionsManageMobile")
    public Boolean getMaximumPermissionsManageMobile() {
        return this.MaximumPermissionsManageMobile;
    }

    @JsonProperty("MaximumPermissionsManageMobile")
    public void setMaximumPermissionsManageMobile(Boolean MaximumPermissionsManageMobile) {
        this.MaximumPermissionsManageMobile = MaximumPermissionsManageMobile;
    }

    // MaximumPermissionsApiEnabled
    private Boolean MaximumPermissionsApiEnabled;

    @JsonProperty("MaximumPermissionsApiEnabled")
    public Boolean getMaximumPermissionsApiEnabled() {
        return this.MaximumPermissionsApiEnabled;
    }

    @JsonProperty("MaximumPermissionsApiEnabled")
    public void setMaximumPermissionsApiEnabled(Boolean MaximumPermissionsApiEnabled) {
        this.MaximumPermissionsApiEnabled = MaximumPermissionsApiEnabled;
    }

    // MaximumPermissionsManageCustomReportTypes
    private Boolean MaximumPermissionsManageCustomReportTypes;

    @JsonProperty("MaximumPermissionsManageCustomReportTypes")
    public Boolean getMaximumPermissionsManageCustomReportTypes() {
        return this.MaximumPermissionsManageCustomReportTypes;
    }

    @JsonProperty("MaximumPermissionsManageCustomReportTypes")
    public void setMaximumPermissionsManageCustomReportTypes(Boolean MaximumPermissionsManageCustomReportTypes) {
        this.MaximumPermissionsManageCustomReportTypes = MaximumPermissionsManageCustomReportTypes;
    }

    // MaximumPermissionsEditCaseComments
    private Boolean MaximumPermissionsEditCaseComments;

    @JsonProperty("MaximumPermissionsEditCaseComments")
    public Boolean getMaximumPermissionsEditCaseComments() {
        return this.MaximumPermissionsEditCaseComments;
    }

    @JsonProperty("MaximumPermissionsEditCaseComments")
    public void setMaximumPermissionsEditCaseComments(Boolean MaximumPermissionsEditCaseComments) {
        this.MaximumPermissionsEditCaseComments = MaximumPermissionsEditCaseComments;
    }

    // MaximumPermissionsTransferAnyCase
    private Boolean MaximumPermissionsTransferAnyCase;

    @JsonProperty("MaximumPermissionsTransferAnyCase")
    public Boolean getMaximumPermissionsTransferAnyCase() {
        return this.MaximumPermissionsTransferAnyCase;
    }

    @JsonProperty("MaximumPermissionsTransferAnyCase")
    public void setMaximumPermissionsTransferAnyCase(Boolean MaximumPermissionsTransferAnyCase) {
        this.MaximumPermissionsTransferAnyCase = MaximumPermissionsTransferAnyCase;
    }

    // MaximumPermissionsContentAdministrator
    private Boolean MaximumPermissionsContentAdministrator;

    @JsonProperty("MaximumPermissionsContentAdministrator")
    public Boolean getMaximumPermissionsContentAdministrator() {
        return this.MaximumPermissionsContentAdministrator;
    }

    @JsonProperty("MaximumPermissionsContentAdministrator")
    public void setMaximumPermissionsContentAdministrator(Boolean MaximumPermissionsContentAdministrator) {
        this.MaximumPermissionsContentAdministrator = MaximumPermissionsContentAdministrator;
    }

    // MaximumPermissionsCreateWorkspaces
    private Boolean MaximumPermissionsCreateWorkspaces;

    @JsonProperty("MaximumPermissionsCreateWorkspaces")
    public Boolean getMaximumPermissionsCreateWorkspaces() {
        return this.MaximumPermissionsCreateWorkspaces;
    }

    @JsonProperty("MaximumPermissionsCreateWorkspaces")
    public void setMaximumPermissionsCreateWorkspaces(Boolean MaximumPermissionsCreateWorkspaces) {
        this.MaximumPermissionsCreateWorkspaces = MaximumPermissionsCreateWorkspaces;
    }

    // MaximumPermissionsManageContentPermissions
    private Boolean MaximumPermissionsManageContentPermissions;

    @JsonProperty("MaximumPermissionsManageContentPermissions")
    public Boolean getMaximumPermissionsManageContentPermissions() {
        return this.MaximumPermissionsManageContentPermissions;
    }

    @JsonProperty("MaximumPermissionsManageContentPermissions")
    public void setMaximumPermissionsManageContentPermissions(Boolean MaximumPermissionsManageContentPermissions) {
        this.MaximumPermissionsManageContentPermissions = MaximumPermissionsManageContentPermissions;
    }

    // MaximumPermissionsManageContentProperties
    private Boolean MaximumPermissionsManageContentProperties;

    @JsonProperty("MaximumPermissionsManageContentProperties")
    public Boolean getMaximumPermissionsManageContentProperties() {
        return this.MaximumPermissionsManageContentProperties;
    }

    @JsonProperty("MaximumPermissionsManageContentProperties")
    public void setMaximumPermissionsManageContentProperties(Boolean MaximumPermissionsManageContentProperties) {
        this.MaximumPermissionsManageContentProperties = MaximumPermissionsManageContentProperties;
    }

    // MaximumPermissionsManageContentTypes
    private Boolean MaximumPermissionsManageContentTypes;

    @JsonProperty("MaximumPermissionsManageContentTypes")
    public Boolean getMaximumPermissionsManageContentTypes() {
        return this.MaximumPermissionsManageContentTypes;
    }

    @JsonProperty("MaximumPermissionsManageContentTypes")
    public void setMaximumPermissionsManageContentTypes(Boolean MaximumPermissionsManageContentTypes) {
        this.MaximumPermissionsManageContentTypes = MaximumPermissionsManageContentTypes;
    }

    // MaximumPermissionsManageExchangeConfig
    private Boolean MaximumPermissionsManageExchangeConfig;

    @JsonProperty("MaximumPermissionsManageExchangeConfig")
    public Boolean getMaximumPermissionsManageExchangeConfig() {
        return this.MaximumPermissionsManageExchangeConfig;
    }

    @JsonProperty("MaximumPermissionsManageExchangeConfig")
    public void setMaximumPermissionsManageExchangeConfig(Boolean MaximumPermissionsManageExchangeConfig) {
        this.MaximumPermissionsManageExchangeConfig = MaximumPermissionsManageExchangeConfig;
    }

    // MaximumPermissionsManageAnalyticSnapshots
    private Boolean MaximumPermissionsManageAnalyticSnapshots;

    @JsonProperty("MaximumPermissionsManageAnalyticSnapshots")
    public Boolean getMaximumPermissionsManageAnalyticSnapshots() {
        return this.MaximumPermissionsManageAnalyticSnapshots;
    }

    @JsonProperty("MaximumPermissionsManageAnalyticSnapshots")
    public void setMaximumPermissionsManageAnalyticSnapshots(Boolean MaximumPermissionsManageAnalyticSnapshots) {
        this.MaximumPermissionsManageAnalyticSnapshots = MaximumPermissionsManageAnalyticSnapshots;
    }

    // MaximumPermissionsScheduleReports
    private Boolean MaximumPermissionsScheduleReports;

    @JsonProperty("MaximumPermissionsScheduleReports")
    public Boolean getMaximumPermissionsScheduleReports() {
        return this.MaximumPermissionsScheduleReports;
    }

    @JsonProperty("MaximumPermissionsScheduleReports")
    public void setMaximumPermissionsScheduleReports(Boolean MaximumPermissionsScheduleReports) {
        this.MaximumPermissionsScheduleReports = MaximumPermissionsScheduleReports;
    }

    // MaximumPermissionsManageBusinessHourHolidays
    private Boolean MaximumPermissionsManageBusinessHourHolidays;

    @JsonProperty("MaximumPermissionsManageBusinessHourHolidays")
    public Boolean getMaximumPermissionsManageBusinessHourHolidays() {
        return this.MaximumPermissionsManageBusinessHourHolidays;
    }

    @JsonProperty("MaximumPermissionsManageBusinessHourHolidays")
    public void setMaximumPermissionsManageBusinessHourHolidays(Boolean MaximumPermissionsManageBusinessHourHolidays) {
        this.MaximumPermissionsManageBusinessHourHolidays = MaximumPermissionsManageBusinessHourHolidays;
    }

    // MaximumPermissionsManageDynamicDashboards
    private Boolean MaximumPermissionsManageDynamicDashboards;

    @JsonProperty("MaximumPermissionsManageDynamicDashboards")
    public Boolean getMaximumPermissionsManageDynamicDashboards() {
        return this.MaximumPermissionsManageDynamicDashboards;
    }

    @JsonProperty("MaximumPermissionsManageDynamicDashboards")
    public void setMaximumPermissionsManageDynamicDashboards(Boolean MaximumPermissionsManageDynamicDashboards) {
        this.MaximumPermissionsManageDynamicDashboards = MaximumPermissionsManageDynamicDashboards;
    }

    // MaximumPermissionsCustomSidebarOnAllPages
    private Boolean MaximumPermissionsCustomSidebarOnAllPages;

    @JsonProperty("MaximumPermissionsCustomSidebarOnAllPages")
    public Boolean getMaximumPermissionsCustomSidebarOnAllPages() {
        return this.MaximumPermissionsCustomSidebarOnAllPages;
    }

    @JsonProperty("MaximumPermissionsCustomSidebarOnAllPages")
    public void setMaximumPermissionsCustomSidebarOnAllPages(Boolean MaximumPermissionsCustomSidebarOnAllPages) {
        this.MaximumPermissionsCustomSidebarOnAllPages = MaximumPermissionsCustomSidebarOnAllPages;
    }

    // MaximumPermissionsManageInteraction
    private Boolean MaximumPermissionsManageInteraction;

    @JsonProperty("MaximumPermissionsManageInteraction")
    public Boolean getMaximumPermissionsManageInteraction() {
        return this.MaximumPermissionsManageInteraction;
    }

    @JsonProperty("MaximumPermissionsManageInteraction")
    public void setMaximumPermissionsManageInteraction(Boolean MaximumPermissionsManageInteraction) {
        this.MaximumPermissionsManageInteraction = MaximumPermissionsManageInteraction;
    }

    // MaximumPermissionsViewMyTeamsDashboards
    private Boolean MaximumPermissionsViewMyTeamsDashboards;

    @JsonProperty("MaximumPermissionsViewMyTeamsDashboards")
    public Boolean getMaximumPermissionsViewMyTeamsDashboards() {
        return this.MaximumPermissionsViewMyTeamsDashboards;
    }

    @JsonProperty("MaximumPermissionsViewMyTeamsDashboards")
    public void setMaximumPermissionsViewMyTeamsDashboards(Boolean MaximumPermissionsViewMyTeamsDashboards) {
        this.MaximumPermissionsViewMyTeamsDashboards = MaximumPermissionsViewMyTeamsDashboards;
    }

    // MaximumPermissionsModerateChatter
    private Boolean MaximumPermissionsModerateChatter;

    @JsonProperty("MaximumPermissionsModerateChatter")
    public Boolean getMaximumPermissionsModerateChatter() {
        return this.MaximumPermissionsModerateChatter;
    }

    @JsonProperty("MaximumPermissionsModerateChatter")
    public void setMaximumPermissionsModerateChatter(Boolean MaximumPermissionsModerateChatter) {
        this.MaximumPermissionsModerateChatter = MaximumPermissionsModerateChatter;
    }

    // MaximumPermissionsResetPasswords
    private Boolean MaximumPermissionsResetPasswords;

    @JsonProperty("MaximumPermissionsResetPasswords")
    public Boolean getMaximumPermissionsResetPasswords() {
        return this.MaximumPermissionsResetPasswords;
    }

    @JsonProperty("MaximumPermissionsResetPasswords")
    public void setMaximumPermissionsResetPasswords(Boolean MaximumPermissionsResetPasswords) {
        this.MaximumPermissionsResetPasswords = MaximumPermissionsResetPasswords;
    }

    // MaximumPermissionsFlowUFLRequired
    private Boolean MaximumPermissionsFlowUFLRequired;

    @JsonProperty("MaximumPermissionsFlowUFLRequired")
    public Boolean getMaximumPermissionsFlowUFLRequired() {
        return this.MaximumPermissionsFlowUFLRequired;
    }

    @JsonProperty("MaximumPermissionsFlowUFLRequired")
    public void setMaximumPermissionsFlowUFLRequired(Boolean MaximumPermissionsFlowUFLRequired) {
        this.MaximumPermissionsFlowUFLRequired = MaximumPermissionsFlowUFLRequired;
    }

    // MaximumPermissionsCanInsertFeedSystemFields
    private Boolean MaximumPermissionsCanInsertFeedSystemFields;

    @JsonProperty("MaximumPermissionsCanInsertFeedSystemFields")
    public Boolean getMaximumPermissionsCanInsertFeedSystemFields() {
        return this.MaximumPermissionsCanInsertFeedSystemFields;
    }

    @JsonProperty("MaximumPermissionsCanInsertFeedSystemFields")
    public void setMaximumPermissionsCanInsertFeedSystemFields(Boolean MaximumPermissionsCanInsertFeedSystemFields) {
        this.MaximumPermissionsCanInsertFeedSystemFields = MaximumPermissionsCanInsertFeedSystemFields;
    }

    // MaximumPermissionsManageKnowledgeImportExport
    private Boolean MaximumPermissionsManageKnowledgeImportExport;

    @JsonProperty("MaximumPermissionsManageKnowledgeImportExport")
    public Boolean getMaximumPermissionsManageKnowledgeImportExport() {
        return this.MaximumPermissionsManageKnowledgeImportExport;
    }

    @JsonProperty("MaximumPermissionsManageKnowledgeImportExport")
    public void setMaximumPermissionsManageKnowledgeImportExport(Boolean MaximumPermissionsManageKnowledgeImportExport) {
        this.MaximumPermissionsManageKnowledgeImportExport = MaximumPermissionsManageKnowledgeImportExport;
    }

    // MaximumPermissionsEmailTemplateManagement
    private Boolean MaximumPermissionsEmailTemplateManagement;

    @JsonProperty("MaximumPermissionsEmailTemplateManagement")
    public Boolean getMaximumPermissionsEmailTemplateManagement() {
        return this.MaximumPermissionsEmailTemplateManagement;
    }

    @JsonProperty("MaximumPermissionsEmailTemplateManagement")
    public void setMaximumPermissionsEmailTemplateManagement(Boolean MaximumPermissionsEmailTemplateManagement) {
        this.MaximumPermissionsEmailTemplateManagement = MaximumPermissionsEmailTemplateManagement;
    }

    // MaximumPermissionsEmailAdministration
    private Boolean MaximumPermissionsEmailAdministration;

    @JsonProperty("MaximumPermissionsEmailAdministration")
    public Boolean getMaximumPermissionsEmailAdministration() {
        return this.MaximumPermissionsEmailAdministration;
    }

    @JsonProperty("MaximumPermissionsEmailAdministration")
    public void setMaximumPermissionsEmailAdministration(Boolean MaximumPermissionsEmailAdministration) {
        this.MaximumPermissionsEmailAdministration = MaximumPermissionsEmailAdministration;
    }

    // MaximumPermissionsManageChatterMessages
    private Boolean MaximumPermissionsManageChatterMessages;

    @JsonProperty("MaximumPermissionsManageChatterMessages")
    public Boolean getMaximumPermissionsManageChatterMessages() {
        return this.MaximumPermissionsManageChatterMessages;
    }

    @JsonProperty("MaximumPermissionsManageChatterMessages")
    public void setMaximumPermissionsManageChatterMessages(Boolean MaximumPermissionsManageChatterMessages) {
        this.MaximumPermissionsManageChatterMessages = MaximumPermissionsManageChatterMessages;
    }

    // MaximumPermissionsAllowEmailIC
    private Boolean MaximumPermissionsAllowEmailIC;

    @JsonProperty("MaximumPermissionsAllowEmailIC")
    public Boolean getMaximumPermissionsAllowEmailIC() {
        return this.MaximumPermissionsAllowEmailIC;
    }

    @JsonProperty("MaximumPermissionsAllowEmailIC")
    public void setMaximumPermissionsAllowEmailIC(Boolean MaximumPermissionsAllowEmailIC) {
        this.MaximumPermissionsAllowEmailIC = MaximumPermissionsAllowEmailIC;
    }

    // MaximumPermissionsChatterFileLink
    private Boolean MaximumPermissionsChatterFileLink;

    @JsonProperty("MaximumPermissionsChatterFileLink")
    public Boolean getMaximumPermissionsChatterFileLink() {
        return this.MaximumPermissionsChatterFileLink;
    }

    @JsonProperty("MaximumPermissionsChatterFileLink")
    public void setMaximumPermissionsChatterFileLink(Boolean MaximumPermissionsChatterFileLink) {
        this.MaximumPermissionsChatterFileLink = MaximumPermissionsChatterFileLink;
    }

    // MaximumPermissionsForceTwoFactor
    private Boolean MaximumPermissionsForceTwoFactor;

    @JsonProperty("MaximumPermissionsForceTwoFactor")
    public Boolean getMaximumPermissionsForceTwoFactor() {
        return this.MaximumPermissionsForceTwoFactor;
    }

    @JsonProperty("MaximumPermissionsForceTwoFactor")
    public void setMaximumPermissionsForceTwoFactor(Boolean MaximumPermissionsForceTwoFactor) {
        this.MaximumPermissionsForceTwoFactor = MaximumPermissionsForceTwoFactor;
    }

    // MaximumPermissionsViewEventLogFiles
    private Boolean MaximumPermissionsViewEventLogFiles;

    @JsonProperty("MaximumPermissionsViewEventLogFiles")
    public Boolean getMaximumPermissionsViewEventLogFiles() {
        return this.MaximumPermissionsViewEventLogFiles;
    }

    @JsonProperty("MaximumPermissionsViewEventLogFiles")
    public void setMaximumPermissionsViewEventLogFiles(Boolean MaximumPermissionsViewEventLogFiles) {
        this.MaximumPermissionsViewEventLogFiles = MaximumPermissionsViewEventLogFiles;
    }

    // MaximumPermissionsManageNetworks
    private Boolean MaximumPermissionsManageNetworks;

    @JsonProperty("MaximumPermissionsManageNetworks")
    public Boolean getMaximumPermissionsManageNetworks() {
        return this.MaximumPermissionsManageNetworks;
    }

    @JsonProperty("MaximumPermissionsManageNetworks")
    public void setMaximumPermissionsManageNetworks(Boolean MaximumPermissionsManageNetworks) {
        this.MaximumPermissionsManageNetworks = MaximumPermissionsManageNetworks;
    }

    // MaximumPermissionsManageAuthProviders
    private Boolean MaximumPermissionsManageAuthProviders;

    @JsonProperty("MaximumPermissionsManageAuthProviders")
    public Boolean getMaximumPermissionsManageAuthProviders() {
        return this.MaximumPermissionsManageAuthProviders;
    }

    @JsonProperty("MaximumPermissionsManageAuthProviders")
    public void setMaximumPermissionsManageAuthProviders(Boolean MaximumPermissionsManageAuthProviders) {
        this.MaximumPermissionsManageAuthProviders = MaximumPermissionsManageAuthProviders;
    }

    // MaximumPermissionsRunFlow
    private Boolean MaximumPermissionsRunFlow;

    @JsonProperty("MaximumPermissionsRunFlow")
    public Boolean getMaximumPermissionsRunFlow() {
        return this.MaximumPermissionsRunFlow;
    }

    @JsonProperty("MaximumPermissionsRunFlow")
    public void setMaximumPermissionsRunFlow(Boolean MaximumPermissionsRunFlow) {
        this.MaximumPermissionsRunFlow = MaximumPermissionsRunFlow;
    }

    // MaximumPermissionsCreateCustomizeDashboards
    private Boolean MaximumPermissionsCreateCustomizeDashboards;

    @JsonProperty("MaximumPermissionsCreateCustomizeDashboards")
    public Boolean getMaximumPermissionsCreateCustomizeDashboards() {
        return this.MaximumPermissionsCreateCustomizeDashboards;
    }

    @JsonProperty("MaximumPermissionsCreateCustomizeDashboards")
    public void setMaximumPermissionsCreateCustomizeDashboards(Boolean MaximumPermissionsCreateCustomizeDashboards) {
        this.MaximumPermissionsCreateCustomizeDashboards = MaximumPermissionsCreateCustomizeDashboards;
    }

    // MaximumPermissionsCreateDashboardFolders
    private Boolean MaximumPermissionsCreateDashboardFolders;

    @JsonProperty("MaximumPermissionsCreateDashboardFolders")
    public Boolean getMaximumPermissionsCreateDashboardFolders() {
        return this.MaximumPermissionsCreateDashboardFolders;
    }

    @JsonProperty("MaximumPermissionsCreateDashboardFolders")
    public void setMaximumPermissionsCreateDashboardFolders(Boolean MaximumPermissionsCreateDashboardFolders) {
        this.MaximumPermissionsCreateDashboardFolders = MaximumPermissionsCreateDashboardFolders;
    }

    // MaximumPermissionsViewPublicDashboards
    private Boolean MaximumPermissionsViewPublicDashboards;

    @JsonProperty("MaximumPermissionsViewPublicDashboards")
    public Boolean getMaximumPermissionsViewPublicDashboards() {
        return this.MaximumPermissionsViewPublicDashboards;
    }

    @JsonProperty("MaximumPermissionsViewPublicDashboards")
    public void setMaximumPermissionsViewPublicDashboards(Boolean MaximumPermissionsViewPublicDashboards) {
        this.MaximumPermissionsViewPublicDashboards = MaximumPermissionsViewPublicDashboards;
    }

    // MaximumPermissionsManageDashbdsInPubFolders
    private Boolean MaximumPermissionsManageDashbdsInPubFolders;

    @JsonProperty("MaximumPermissionsManageDashbdsInPubFolders")
    public Boolean getMaximumPermissionsManageDashbdsInPubFolders() {
        return this.MaximumPermissionsManageDashbdsInPubFolders;
    }

    @JsonProperty("MaximumPermissionsManageDashbdsInPubFolders")
    public void setMaximumPermissionsManageDashbdsInPubFolders(Boolean MaximumPermissionsManageDashbdsInPubFolders) {
        this.MaximumPermissionsManageDashbdsInPubFolders = MaximumPermissionsManageDashbdsInPubFolders;
    }

    // MaximumPermissionsCreateCustomizeReports
    private Boolean MaximumPermissionsCreateCustomizeReports;

    @JsonProperty("MaximumPermissionsCreateCustomizeReports")
    public Boolean getMaximumPermissionsCreateCustomizeReports() {
        return this.MaximumPermissionsCreateCustomizeReports;
    }

    @JsonProperty("MaximumPermissionsCreateCustomizeReports")
    public void setMaximumPermissionsCreateCustomizeReports(Boolean MaximumPermissionsCreateCustomizeReports) {
        this.MaximumPermissionsCreateCustomizeReports = MaximumPermissionsCreateCustomizeReports;
    }

    // MaximumPermissionsCreateReportFolders
    private Boolean MaximumPermissionsCreateReportFolders;

    @JsonProperty("MaximumPermissionsCreateReportFolders")
    public Boolean getMaximumPermissionsCreateReportFolders() {
        return this.MaximumPermissionsCreateReportFolders;
    }

    @JsonProperty("MaximumPermissionsCreateReportFolders")
    public void setMaximumPermissionsCreateReportFolders(Boolean MaximumPermissionsCreateReportFolders) {
        this.MaximumPermissionsCreateReportFolders = MaximumPermissionsCreateReportFolders;
    }

    // MaximumPermissionsViewPublicReports
    private Boolean MaximumPermissionsViewPublicReports;

    @JsonProperty("MaximumPermissionsViewPublicReports")
    public Boolean getMaximumPermissionsViewPublicReports() {
        return this.MaximumPermissionsViewPublicReports;
    }

    @JsonProperty("MaximumPermissionsViewPublicReports")
    public void setMaximumPermissionsViewPublicReports(Boolean MaximumPermissionsViewPublicReports) {
        this.MaximumPermissionsViewPublicReports = MaximumPermissionsViewPublicReports;
    }

    // MaximumPermissionsManageReportsInPubFolders
    private Boolean MaximumPermissionsManageReportsInPubFolders;

    @JsonProperty("MaximumPermissionsManageReportsInPubFolders")
    public Boolean getMaximumPermissionsManageReportsInPubFolders() {
        return this.MaximumPermissionsManageReportsInPubFolders;
    }

    @JsonProperty("MaximumPermissionsManageReportsInPubFolders")
    public void setMaximumPermissionsManageReportsInPubFolders(Boolean MaximumPermissionsManageReportsInPubFolders) {
        this.MaximumPermissionsManageReportsInPubFolders = MaximumPermissionsManageReportsInPubFolders;
    }

    // MaximumPermissionsEditMyDashboards
    private Boolean MaximumPermissionsEditMyDashboards;

    @JsonProperty("MaximumPermissionsEditMyDashboards")
    public Boolean getMaximumPermissionsEditMyDashboards() {
        return this.MaximumPermissionsEditMyDashboards;
    }

    @JsonProperty("MaximumPermissionsEditMyDashboards")
    public void setMaximumPermissionsEditMyDashboards(Boolean MaximumPermissionsEditMyDashboards) {
        this.MaximumPermissionsEditMyDashboards = MaximumPermissionsEditMyDashboards;
    }

    // MaximumPermissionsEditMyReports
    private Boolean MaximumPermissionsEditMyReports;

    @JsonProperty("MaximumPermissionsEditMyReports")
    public Boolean getMaximumPermissionsEditMyReports() {
        return this.MaximumPermissionsEditMyReports;
    }

    @JsonProperty("MaximumPermissionsEditMyReports")
    public void setMaximumPermissionsEditMyReports(Boolean MaximumPermissionsEditMyReports) {
        this.MaximumPermissionsEditMyReports = MaximumPermissionsEditMyReports;
    }

    // MaximumPermissionsViewAllUsers
    private Boolean MaximumPermissionsViewAllUsers;

    @JsonProperty("MaximumPermissionsViewAllUsers")
    public Boolean getMaximumPermissionsViewAllUsers() {
        return this.MaximumPermissionsViewAllUsers;
    }

    @JsonProperty("MaximumPermissionsViewAllUsers")
    public void setMaximumPermissionsViewAllUsers(Boolean MaximumPermissionsViewAllUsers) {
        this.MaximumPermissionsViewAllUsers = MaximumPermissionsViewAllUsers;
    }

    // MaximumPermissionsAllowUniversalSearch
    private Boolean MaximumPermissionsAllowUniversalSearch;

    @JsonProperty("MaximumPermissionsAllowUniversalSearch")
    public Boolean getMaximumPermissionsAllowUniversalSearch() {
        return this.MaximumPermissionsAllowUniversalSearch;
    }

    @JsonProperty("MaximumPermissionsAllowUniversalSearch")
    public void setMaximumPermissionsAllowUniversalSearch(Boolean MaximumPermissionsAllowUniversalSearch) {
        this.MaximumPermissionsAllowUniversalSearch = MaximumPermissionsAllowUniversalSearch;
    }

    // MaximumPermissionsConnectOrgToEnvironmentHub
    private Boolean MaximumPermissionsConnectOrgToEnvironmentHub;

    @JsonProperty("MaximumPermissionsConnectOrgToEnvironmentHub")
    public Boolean getMaximumPermissionsConnectOrgToEnvironmentHub() {
        return this.MaximumPermissionsConnectOrgToEnvironmentHub;
    }

    @JsonProperty("MaximumPermissionsConnectOrgToEnvironmentHub")
    public void setMaximumPermissionsConnectOrgToEnvironmentHub(Boolean MaximumPermissionsConnectOrgToEnvironmentHub) {
        this.MaximumPermissionsConnectOrgToEnvironmentHub = MaximumPermissionsConnectOrgToEnvironmentHub;
    }

    // MaximumPermissionsWorkCalibrationUser
    private Boolean MaximumPermissionsWorkCalibrationUser;

    @JsonProperty("MaximumPermissionsWorkCalibrationUser")
    public Boolean getMaximumPermissionsWorkCalibrationUser() {
        return this.MaximumPermissionsWorkCalibrationUser;
    }

    @JsonProperty("MaximumPermissionsWorkCalibrationUser")
    public void setMaximumPermissionsWorkCalibrationUser(Boolean MaximumPermissionsWorkCalibrationUser) {
        this.MaximumPermissionsWorkCalibrationUser = MaximumPermissionsWorkCalibrationUser;
    }

    // MaximumPermissionsCreateCustomizeFilters
    private Boolean MaximumPermissionsCreateCustomizeFilters;

    @JsonProperty("MaximumPermissionsCreateCustomizeFilters")
    public Boolean getMaximumPermissionsCreateCustomizeFilters() {
        return this.MaximumPermissionsCreateCustomizeFilters;
    }

    @JsonProperty("MaximumPermissionsCreateCustomizeFilters")
    public void setMaximumPermissionsCreateCustomizeFilters(Boolean MaximumPermissionsCreateCustomizeFilters) {
        this.MaximumPermissionsCreateCustomizeFilters = MaximumPermissionsCreateCustomizeFilters;
    }

    // MaximumPermissionsWorkDotComUserPerm
    private Boolean MaximumPermissionsWorkDotComUserPerm;

    @JsonProperty("MaximumPermissionsWorkDotComUserPerm")
    public Boolean getMaximumPermissionsWorkDotComUserPerm() {
        return this.MaximumPermissionsWorkDotComUserPerm;
    }

    @JsonProperty("MaximumPermissionsWorkDotComUserPerm")
    public void setMaximumPermissionsWorkDotComUserPerm(Boolean MaximumPermissionsWorkDotComUserPerm) {
        this.MaximumPermissionsWorkDotComUserPerm = MaximumPermissionsWorkDotComUserPerm;
    }

    // MaximumPermissionsGovernNetworks
    private Boolean MaximumPermissionsGovernNetworks;

    @JsonProperty("MaximumPermissionsGovernNetworks")
    public Boolean getMaximumPermissionsGovernNetworks() {
        return this.MaximumPermissionsGovernNetworks;
    }

    @JsonProperty("MaximumPermissionsGovernNetworks")
    public void setMaximumPermissionsGovernNetworks(Boolean MaximumPermissionsGovernNetworks) {
        this.MaximumPermissionsGovernNetworks = MaximumPermissionsGovernNetworks;
    }

    // MaximumPermissionsSalesConsole
    private Boolean MaximumPermissionsSalesConsole;

    @JsonProperty("MaximumPermissionsSalesConsole")
    public Boolean getMaximumPermissionsSalesConsole() {
        return this.MaximumPermissionsSalesConsole;
    }

    @JsonProperty("MaximumPermissionsSalesConsole")
    public void setMaximumPermissionsSalesConsole(Boolean MaximumPermissionsSalesConsole) {
        this.MaximumPermissionsSalesConsole = MaximumPermissionsSalesConsole;
    }

    // MaximumPermissionsTwoFactorApi
    private Boolean MaximumPermissionsTwoFactorApi;

    @JsonProperty("MaximumPermissionsTwoFactorApi")
    public Boolean getMaximumPermissionsTwoFactorApi() {
        return this.MaximumPermissionsTwoFactorApi;
    }

    @JsonProperty("MaximumPermissionsTwoFactorApi")
    public void setMaximumPermissionsTwoFactorApi(Boolean MaximumPermissionsTwoFactorApi) {
        this.MaximumPermissionsTwoFactorApi = MaximumPermissionsTwoFactorApi;
    }

    // MaximumPermissionsDeleteTopics
    private Boolean MaximumPermissionsDeleteTopics;

    @JsonProperty("MaximumPermissionsDeleteTopics")
    public Boolean getMaximumPermissionsDeleteTopics() {
        return this.MaximumPermissionsDeleteTopics;
    }

    @JsonProperty("MaximumPermissionsDeleteTopics")
    public void setMaximumPermissionsDeleteTopics(Boolean MaximumPermissionsDeleteTopics) {
        this.MaximumPermissionsDeleteTopics = MaximumPermissionsDeleteTopics;
    }

    // MaximumPermissionsEditTopics
    private Boolean MaximumPermissionsEditTopics;

    @JsonProperty("MaximumPermissionsEditTopics")
    public Boolean getMaximumPermissionsEditTopics() {
        return this.MaximumPermissionsEditTopics;
    }

    @JsonProperty("MaximumPermissionsEditTopics")
    public void setMaximumPermissionsEditTopics(Boolean MaximumPermissionsEditTopics) {
        this.MaximumPermissionsEditTopics = MaximumPermissionsEditTopics;
    }

    // MaximumPermissionsCreateTopics
    private Boolean MaximumPermissionsCreateTopics;

    @JsonProperty("MaximumPermissionsCreateTopics")
    public Boolean getMaximumPermissionsCreateTopics() {
        return this.MaximumPermissionsCreateTopics;
    }

    @JsonProperty("MaximumPermissionsCreateTopics")
    public void setMaximumPermissionsCreateTopics(Boolean MaximumPermissionsCreateTopics) {
        this.MaximumPermissionsCreateTopics = MaximumPermissionsCreateTopics;
    }

    // MaximumPermissionsAssignTopics
    private Boolean MaximumPermissionsAssignTopics;

    @JsonProperty("MaximumPermissionsAssignTopics")
    public Boolean getMaximumPermissionsAssignTopics() {
        return this.MaximumPermissionsAssignTopics;
    }

    @JsonProperty("MaximumPermissionsAssignTopics")
    public void setMaximumPermissionsAssignTopics(Boolean MaximumPermissionsAssignTopics) {
        this.MaximumPermissionsAssignTopics = MaximumPermissionsAssignTopics;
    }

    // MaximumPermissionsIdentityEnabled
    private Boolean MaximumPermissionsIdentityEnabled;

    @JsonProperty("MaximumPermissionsIdentityEnabled")
    public Boolean getMaximumPermissionsIdentityEnabled() {
        return this.MaximumPermissionsIdentityEnabled;
    }

    @JsonProperty("MaximumPermissionsIdentityEnabled")
    public void setMaximumPermissionsIdentityEnabled(Boolean MaximumPermissionsIdentityEnabled) {
        this.MaximumPermissionsIdentityEnabled = MaximumPermissionsIdentityEnabled;
    }

    // MaximumPermissionsIdentityConnect
    private Boolean MaximumPermissionsIdentityConnect;

    @JsonProperty("MaximumPermissionsIdentityConnect")
    public Boolean getMaximumPermissionsIdentityConnect() {
        return this.MaximumPermissionsIdentityConnect;
    }

    @JsonProperty("MaximumPermissionsIdentityConnect")
    public void setMaximumPermissionsIdentityConnect(Boolean MaximumPermissionsIdentityConnect) {
        this.MaximumPermissionsIdentityConnect = MaximumPermissionsIdentityConnect;
    }

    // MaximumPermissionsAllowViewKnowledge
    private Boolean MaximumPermissionsAllowViewKnowledge;

    @JsonProperty("MaximumPermissionsAllowViewKnowledge")
    public Boolean getMaximumPermissionsAllowViewKnowledge() {
        return this.MaximumPermissionsAllowViewKnowledge;
    }

    @JsonProperty("MaximumPermissionsAllowViewKnowledge")
    public void setMaximumPermissionsAllowViewKnowledge(Boolean MaximumPermissionsAllowViewKnowledge) {
        this.MaximumPermissionsAllowViewKnowledge = MaximumPermissionsAllowViewKnowledge;
    }

    // MaximumPermissionsManageSearchPromotionRules
    private Boolean MaximumPermissionsManageSearchPromotionRules;

    @JsonProperty("MaximumPermissionsManageSearchPromotionRules")
    public Boolean getMaximumPermissionsManageSearchPromotionRules() {
        return this.MaximumPermissionsManageSearchPromotionRules;
    }

    @JsonProperty("MaximumPermissionsManageSearchPromotionRules")
    public void setMaximumPermissionsManageSearchPromotionRules(Boolean MaximumPermissionsManageSearchPromotionRules) {
        this.MaximumPermissionsManageSearchPromotionRules = MaximumPermissionsManageSearchPromotionRules;
    }

    // MaximumPermissionsCustomMobileAppsAccess
    private Boolean MaximumPermissionsCustomMobileAppsAccess;

    @JsonProperty("MaximumPermissionsCustomMobileAppsAccess")
    public Boolean getMaximumPermissionsCustomMobileAppsAccess() {
        return this.MaximumPermissionsCustomMobileAppsAccess;
    }

    @JsonProperty("MaximumPermissionsCustomMobileAppsAccess")
    public void setMaximumPermissionsCustomMobileAppsAccess(Boolean MaximumPermissionsCustomMobileAppsAccess) {
        this.MaximumPermissionsCustomMobileAppsAccess = MaximumPermissionsCustomMobileAppsAccess;
    }

    // MaximumPermissionsViewHelpLink
    private Boolean MaximumPermissionsViewHelpLink;

    @JsonProperty("MaximumPermissionsViewHelpLink")
    public Boolean getMaximumPermissionsViewHelpLink() {
        return this.MaximumPermissionsViewHelpLink;
    }

    @JsonProperty("MaximumPermissionsViewHelpLink")
    public void setMaximumPermissionsViewHelpLink(Boolean MaximumPermissionsViewHelpLink) {
        this.MaximumPermissionsViewHelpLink = MaximumPermissionsViewHelpLink;
    }

    // MaximumPermissionsManageProfilesPermissionsets
    private Boolean MaximumPermissionsManageProfilesPermissionsets;

    @JsonProperty("MaximumPermissionsManageProfilesPermissionsets")
    public Boolean getMaximumPermissionsManageProfilesPermissionsets() {
        return this.MaximumPermissionsManageProfilesPermissionsets;
    }

    @JsonProperty("MaximumPermissionsManageProfilesPermissionsets")
    public void setMaximumPermissionsManageProfilesPermissionsets(Boolean MaximumPermissionsManageProfilesPermissionsets) {
        this.MaximumPermissionsManageProfilesPermissionsets = MaximumPermissionsManageProfilesPermissionsets;
    }

    // MaximumPermissionsAssignPermissionSets
    private Boolean MaximumPermissionsAssignPermissionSets;

    @JsonProperty("MaximumPermissionsAssignPermissionSets")
    public Boolean getMaximumPermissionsAssignPermissionSets() {
        return this.MaximumPermissionsAssignPermissionSets;
    }

    @JsonProperty("MaximumPermissionsAssignPermissionSets")
    public void setMaximumPermissionsAssignPermissionSets(Boolean MaximumPermissionsAssignPermissionSets) {
        this.MaximumPermissionsAssignPermissionSets = MaximumPermissionsAssignPermissionSets;
    }

    // MaximumPermissionsManageRoles
    private Boolean MaximumPermissionsManageRoles;

    @JsonProperty("MaximumPermissionsManageRoles")
    public Boolean getMaximumPermissionsManageRoles() {
        return this.MaximumPermissionsManageRoles;
    }

    @JsonProperty("MaximumPermissionsManageRoles")
    public void setMaximumPermissionsManageRoles(Boolean MaximumPermissionsManageRoles) {
        this.MaximumPermissionsManageRoles = MaximumPermissionsManageRoles;
    }

    // MaximumPermissionsManageIpAddresses
    private Boolean MaximumPermissionsManageIpAddresses;

    @JsonProperty("MaximumPermissionsManageIpAddresses")
    public Boolean getMaximumPermissionsManageIpAddresses() {
        return this.MaximumPermissionsManageIpAddresses;
    }

    @JsonProperty("MaximumPermissionsManageIpAddresses")
    public void setMaximumPermissionsManageIpAddresses(Boolean MaximumPermissionsManageIpAddresses) {
        this.MaximumPermissionsManageIpAddresses = MaximumPermissionsManageIpAddresses;
    }

    // MaximumPermissionsManageSharing
    private Boolean MaximumPermissionsManageSharing;

    @JsonProperty("MaximumPermissionsManageSharing")
    public Boolean getMaximumPermissionsManageSharing() {
        return this.MaximumPermissionsManageSharing;
    }

    @JsonProperty("MaximumPermissionsManageSharing")
    public void setMaximumPermissionsManageSharing(Boolean MaximumPermissionsManageSharing) {
        this.MaximumPermissionsManageSharing = MaximumPermissionsManageSharing;
    }

    // MaximumPermissionsManageInternalUsers
    private Boolean MaximumPermissionsManageInternalUsers;

    @JsonProperty("MaximumPermissionsManageInternalUsers")
    public Boolean getMaximumPermissionsManageInternalUsers() {
        return this.MaximumPermissionsManageInternalUsers;
    }

    @JsonProperty("MaximumPermissionsManageInternalUsers")
    public void setMaximumPermissionsManageInternalUsers(Boolean MaximumPermissionsManageInternalUsers) {
        this.MaximumPermissionsManageInternalUsers = MaximumPermissionsManageInternalUsers;
    }

    // MaximumPermissionsManagePasswordPolicies
    private Boolean MaximumPermissionsManagePasswordPolicies;

    @JsonProperty("MaximumPermissionsManagePasswordPolicies")
    public Boolean getMaximumPermissionsManagePasswordPolicies() {
        return this.MaximumPermissionsManagePasswordPolicies;
    }

    @JsonProperty("MaximumPermissionsManagePasswordPolicies")
    public void setMaximumPermissionsManagePasswordPolicies(Boolean MaximumPermissionsManagePasswordPolicies) {
        this.MaximumPermissionsManagePasswordPolicies = MaximumPermissionsManagePasswordPolicies;
    }

    // MaximumPermissionsManageLoginAccessPolicies
    private Boolean MaximumPermissionsManageLoginAccessPolicies;

    @JsonProperty("MaximumPermissionsManageLoginAccessPolicies")
    public Boolean getMaximumPermissionsManageLoginAccessPolicies() {
        return this.MaximumPermissionsManageLoginAccessPolicies;
    }

    @JsonProperty("MaximumPermissionsManageLoginAccessPolicies")
    public void setMaximumPermissionsManageLoginAccessPolicies(Boolean MaximumPermissionsManageLoginAccessPolicies) {
        this.MaximumPermissionsManageLoginAccessPolicies = MaximumPermissionsManageLoginAccessPolicies;
    }

    // MaximumPermissionsManageCustomPermissions
    private Boolean MaximumPermissionsManageCustomPermissions;

    @JsonProperty("MaximumPermissionsManageCustomPermissions")
    public Boolean getMaximumPermissionsManageCustomPermissions() {
        return this.MaximumPermissionsManageCustomPermissions;
    }

    @JsonProperty("MaximumPermissionsManageCustomPermissions")
    public void setMaximumPermissionsManageCustomPermissions(Boolean MaximumPermissionsManageCustomPermissions) {
        this.MaximumPermissionsManageCustomPermissions = MaximumPermissionsManageCustomPermissions;
    }

    // MaximumPermissionsManageUnlistedGroups
    private Boolean MaximumPermissionsManageUnlistedGroups;

    @JsonProperty("MaximumPermissionsManageUnlistedGroups")
    public Boolean getMaximumPermissionsManageUnlistedGroups() {
        return this.MaximumPermissionsManageUnlistedGroups;
    }

    @JsonProperty("MaximumPermissionsManageUnlistedGroups")
    public void setMaximumPermissionsManageUnlistedGroups(Boolean MaximumPermissionsManageUnlistedGroups) {
        this.MaximumPermissionsManageUnlistedGroups = MaximumPermissionsManageUnlistedGroups;
    }

    // MaximumPermissionsModifySecureAgents
    private Boolean MaximumPermissionsModifySecureAgents;

    @JsonProperty("MaximumPermissionsModifySecureAgents")
    public Boolean getMaximumPermissionsModifySecureAgents() {
        return this.MaximumPermissionsModifySecureAgents;
    }

    @JsonProperty("MaximumPermissionsModifySecureAgents")
    public void setMaximumPermissionsModifySecureAgents(Boolean MaximumPermissionsModifySecureAgents) {
        this.MaximumPermissionsModifySecureAgents = MaximumPermissionsModifySecureAgents;
    }

    // MaximumPermissionsManageTwoFactor
    private Boolean MaximumPermissionsManageTwoFactor;

    @JsonProperty("MaximumPermissionsManageTwoFactor")
    public Boolean getMaximumPermissionsManageTwoFactor() {
        return this.MaximumPermissionsManageTwoFactor;
    }

    @JsonProperty("MaximumPermissionsManageTwoFactor")
    public void setMaximumPermissionsManageTwoFactor(Boolean MaximumPermissionsManageTwoFactor) {
        this.MaximumPermissionsManageTwoFactor = MaximumPermissionsManageTwoFactor;
    }

    // MaximumPermissionsChatterForSharePoint
    private Boolean MaximumPermissionsChatterForSharePoint;

    @JsonProperty("MaximumPermissionsChatterForSharePoint")
    public Boolean getMaximumPermissionsChatterForSharePoint() {
        return this.MaximumPermissionsChatterForSharePoint;
    }

    @JsonProperty("MaximumPermissionsChatterForSharePoint")
    public void setMaximumPermissionsChatterForSharePoint(Boolean MaximumPermissionsChatterForSharePoint) {
        this.MaximumPermissionsChatterForSharePoint = MaximumPermissionsChatterForSharePoint;
    }

    // MaximumPermissionsLightningExperienceUser
    private Boolean MaximumPermissionsLightningExperienceUser;

    @JsonProperty("MaximumPermissionsLightningExperienceUser")
    public Boolean getMaximumPermissionsLightningExperienceUser() {
        return this.MaximumPermissionsLightningExperienceUser;
    }

    @JsonProperty("MaximumPermissionsLightningExperienceUser")
    public void setMaximumPermissionsLightningExperienceUser(Boolean MaximumPermissionsLightningExperienceUser) {
        this.MaximumPermissionsLightningExperienceUser = MaximumPermissionsLightningExperienceUser;
    }

    // MaximumPermissionsConfigCustomRecs
    private Boolean MaximumPermissionsConfigCustomRecs;

    @JsonProperty("MaximumPermissionsConfigCustomRecs")
    public Boolean getMaximumPermissionsConfigCustomRecs() {
        return this.MaximumPermissionsConfigCustomRecs;
    }

    @JsonProperty("MaximumPermissionsConfigCustomRecs")
    public void setMaximumPermissionsConfigCustomRecs(Boolean MaximumPermissionsConfigCustomRecs) {
        this.MaximumPermissionsConfigCustomRecs = MaximumPermissionsConfigCustomRecs;
    }

    // MaximumPermissionsShareInternalArticles
    private Boolean MaximumPermissionsShareInternalArticles;

    @JsonProperty("MaximumPermissionsShareInternalArticles")
    public Boolean getMaximumPermissionsShareInternalArticles() {
        return this.MaximumPermissionsShareInternalArticles;
    }

    @JsonProperty("MaximumPermissionsShareInternalArticles")
    public void setMaximumPermissionsShareInternalArticles(Boolean MaximumPermissionsShareInternalArticles) {
        this.MaximumPermissionsShareInternalArticles = MaximumPermissionsShareInternalArticles;
    }

    // MaximumPermissionsMergeTopics
    private Boolean MaximumPermissionsMergeTopics;

    @JsonProperty("MaximumPermissionsMergeTopics")
    public Boolean getMaximumPermissionsMergeTopics() {
        return this.MaximumPermissionsMergeTopics;
    }

    @JsonProperty("MaximumPermissionsMergeTopics")
    public void setMaximumPermissionsMergeTopics(Boolean MaximumPermissionsMergeTopics) {
        this.MaximumPermissionsMergeTopics = MaximumPermissionsMergeTopics;
    }

    // UsedLicenses
    private Integer UsedLicenses;

    @JsonProperty("UsedLicenses")
    public Integer getUsedLicenses() {
        return this.UsedLicenses;
    }

    @JsonProperty("UsedLicenses")
    public void setUsedLicenses(Integer UsedLicenses) {
        this.UsedLicenses = UsedLicenses;
    }

}
