/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist AggregateField
 */
public enum AggregateFieldEnum {

    // Account.AccountNumber
    ACCOUNT_ACCOUNTNUMBER("Account.AccountNumber"),
    // Account.AccountSource
    ACCOUNT_ACCOUNTSOURCE("Account.AccountSource"),
    // Account.AnnualRevenue
    ACCOUNT_ANNUALREVENUE("Account.AnnualRevenue"),
    // Account.BillingAddress
    ACCOUNT_BILLINGADDRESS("Account.BillingAddress"),
    // Account.BillingCity
    ACCOUNT_BILLINGCITY("Account.BillingCity"),
    // Account.BillingCountry
    ACCOUNT_BILLINGCOUNTRY("Account.BillingCountry"),
    // Account.BillingLatitude
    ACCOUNT_BILLINGLATITUDE("Account.BillingLatitude"),
    // Account.BillingLongitude
    ACCOUNT_BILLINGLONGITUDE("Account.BillingLongitude"),
    // Account.BillingPostalCode
    ACCOUNT_BILLINGPOSTALCODE("Account.BillingPostalCode"),
    // Account.BillingState
    ACCOUNT_BILLINGSTATE("Account.BillingState"),
    // Account.BillingStreet
    ACCOUNT_BILLINGSTREET("Account.BillingStreet"),
    // Account.CleanStatus
    ACCOUNT_CLEANSTATUS("Account.CleanStatus"),
    // Account.CreatedById
    ACCOUNT_CREATEDBYID("Account.CreatedById"),
    // Account.CreatedDate
    ACCOUNT_CREATEDDATE("Account.CreatedDate"),
    // Account.DandbCompanyId
    ACCOUNT_DANDBCOMPANYID("Account.DandbCompanyId"),
    // Account.Description
    ACCOUNT_DESCRIPTION("Account.Description"),
    // Account.DunsNumber
    ACCOUNT_DUNSNUMBER("Account.DunsNumber"),
    // Account.Fax
    ACCOUNT_FAX("Account.Fax"),
    // Account.Id
    ACCOUNT_ID("Account.Id"),
    // Account.Industry
    ACCOUNT_INDUSTRY("Account.Industry"),
    // Account.IsDeleted
    ACCOUNT_ISDELETED("Account.IsDeleted"),
    // Account.Jigsaw
    ACCOUNT_JIGSAW("Account.Jigsaw"),
    // Account.JigsawCompanyId
    ACCOUNT_JIGSAWCOMPANYID("Account.JigsawCompanyId"),
    // Account.LastActivityDate
    ACCOUNT_LASTACTIVITYDATE("Account.LastActivityDate"),
    // Account.LastModifiedById
    ACCOUNT_LASTMODIFIEDBYID("Account.LastModifiedById"),
    // Account.LastModifiedDate
    ACCOUNT_LASTMODIFIEDDATE("Account.LastModifiedDate"),
    // Account.LastReferencedDate
    ACCOUNT_LASTREFERENCEDDATE("Account.LastReferencedDate"),
    // Account.LastViewedDate
    ACCOUNT_LASTVIEWEDDATE("Account.LastViewedDate"),
    // Account.MasterRecordId
    ACCOUNT_MASTERRECORDID("Account.MasterRecordId"),
    // Account.NaicsCode
    ACCOUNT_NAICSCODE("Account.NaicsCode"),
    // Account.NaicsDesc
    ACCOUNT_NAICSDESC("Account.NaicsDesc"),
    // Account.Name
    ACCOUNT_NAME("Account.Name"),
    // Account.NumberOfEmployees
    ACCOUNT_NUMBEROFEMPLOYEES("Account.NumberOfEmployees"),
    // Account.OwnerId
    ACCOUNT_OWNERID("Account.OwnerId"),
    // Account.Ownership
    ACCOUNT_OWNERSHIP("Account.Ownership"),
    // Account.ParentId
    ACCOUNT_PARENTID("Account.ParentId"),
    // Account.Phone
    ACCOUNT_PHONE("Account.Phone"),
    // Account.PhotoUrl
    ACCOUNT_PHOTOURL("Account.PhotoUrl"),
    // Account.Rating
    ACCOUNT_RATING("Account.Rating"),
    // Account.ShippingAddress
    ACCOUNT_SHIPPINGADDRESS("Account.ShippingAddress"),
    // Account.ShippingCity
    ACCOUNT_SHIPPINGCITY("Account.ShippingCity"),
    // Account.ShippingCountry
    ACCOUNT_SHIPPINGCOUNTRY("Account.ShippingCountry"),
    // Account.ShippingLatitude
    ACCOUNT_SHIPPINGLATITUDE("Account.ShippingLatitude"),
    // Account.ShippingLongitude
    ACCOUNT_SHIPPINGLONGITUDE("Account.ShippingLongitude"),
    // Account.ShippingPostalCode
    ACCOUNT_SHIPPINGPOSTALCODE("Account.ShippingPostalCode"),
    // Account.ShippingState
    ACCOUNT_SHIPPINGSTATE("Account.ShippingState"),
    // Account.ShippingStreet
    ACCOUNT_SHIPPINGSTREET("Account.ShippingStreet"),
    // Account.Sic
    ACCOUNT_SIC("Account.Sic"),
    // Account.SicDesc
    ACCOUNT_SICDESC("Account.SicDesc"),
    // Account.Site
    ACCOUNT_SITE("Account.Site"),
    // Account.SystemModstamp
    ACCOUNT_SYSTEMMODSTAMP("Account.SystemModstamp"),
    // Account.TickerSymbol
    ACCOUNT_TICKERSYMBOL("Account.TickerSymbol"),
    // Account.Tradestyle
    ACCOUNT_TRADESTYLE("Account.Tradestyle"),
    // Account.Type
    ACCOUNT_TYPE("Account.Type"),
    // Account.Website
    ACCOUNT_WEBSITE("Account.Website"),
    // Account.YearStarted
    ACCOUNT_YEARSTARTED("Account.YearStarted"),
    // Asset.AccountId
    ASSET_ACCOUNTID("Asset.AccountId"),
    // Asset.ContactId
    ASSET_CONTACTID("Asset.ContactId"),
    // Asset.CreatedById
    ASSET_CREATEDBYID("Asset.CreatedById"),
    // Asset.CreatedDate
    ASSET_CREATEDDATE("Asset.CreatedDate"),
    // Asset.Description
    ASSET_DESCRIPTION("Asset.Description"),
    // Asset.Id
    ASSET_ID("Asset.Id"),
    // Asset.InstallDate
    ASSET_INSTALLDATE("Asset.InstallDate"),
    // Asset.IsCompetitorProduct
    ASSET_ISCOMPETITORPRODUCT("Asset.IsCompetitorProduct"),
    // Asset.IsDeleted
    ASSET_ISDELETED("Asset.IsDeleted"),
    // Asset.LastModifiedById
    ASSET_LASTMODIFIEDBYID("Asset.LastModifiedById"),
    // Asset.LastModifiedDate
    ASSET_LASTMODIFIEDDATE("Asset.LastModifiedDate"),
    // Asset.LastReferencedDate
    ASSET_LASTREFERENCEDDATE("Asset.LastReferencedDate"),
    // Asset.LastViewedDate
    ASSET_LASTVIEWEDDATE("Asset.LastViewedDate"),
    // Asset.Name
    ASSET_NAME("Asset.Name"),
    // Asset.OwnerId
    ASSET_OWNERID("Asset.OwnerId"),
    // Asset.Price
    ASSET_PRICE("Asset.Price"),
    // Asset.Product2Id
    ASSET_PRODUCT2ID("Asset.Product2Id"),
    // Asset.PurchaseDate
    ASSET_PURCHASEDATE("Asset.PurchaseDate"),
    // Asset.Quantity
    ASSET_QUANTITY("Asset.Quantity"),
    // Asset.SerialNumber
    ASSET_SERIALNUMBER("Asset.SerialNumber"),
    // Asset.Status
    ASSET_STATUS("Asset.Status"),
    // Asset.SystemModstamp
    ASSET_SYSTEMMODSTAMP("Asset.SystemModstamp"),
    // Asset.UsageEndDate
    ASSET_USAGEENDDATE("Asset.UsageEndDate"),
    // Campaign.ActualCost
    CAMPAIGN_ACTUALCOST("Campaign.ActualCost"),
    // Campaign.AmountAllOpportunities
    CAMPAIGN_AMOUNTALLOPPORTUNITIES("Campaign.AmountAllOpportunities"),
    // Campaign.AmountWonOpportunities
    CAMPAIGN_AMOUNTWONOPPORTUNITIES("Campaign.AmountWonOpportunities"),
    // Campaign.BudgetedCost
    CAMPAIGN_BUDGETEDCOST("Campaign.BudgetedCost"),
    // Campaign.CampaignMemberRecordTypeId
    CAMPAIGN_CAMPAIGNMEMBERRECORDTYPEID("Campaign.CampaignMemberRecordTypeId"),
    // Campaign.CreatedById
    CAMPAIGN_CREATEDBYID("Campaign.CreatedById"),
    // Campaign.CreatedDate
    CAMPAIGN_CREATEDDATE("Campaign.CreatedDate"),
    // Campaign.Description
    CAMPAIGN_DESCRIPTION("Campaign.Description"),
    // Campaign.EndDate
    CAMPAIGN_ENDDATE("Campaign.EndDate"),
    // Campaign.ExpectedResponse
    CAMPAIGN_EXPECTEDRESPONSE("Campaign.ExpectedResponse"),
    // Campaign.ExpectedRevenue
    CAMPAIGN_EXPECTEDREVENUE("Campaign.ExpectedRevenue"),
    // Campaign.Id
    CAMPAIGN_ID("Campaign.Id"),
    // Campaign.IsActive
    CAMPAIGN_ISACTIVE("Campaign.IsActive"),
    // Campaign.IsDeleted
    CAMPAIGN_ISDELETED("Campaign.IsDeleted"),
    // Campaign.LastActivityDate
    CAMPAIGN_LASTACTIVITYDATE("Campaign.LastActivityDate"),
    // Campaign.LastModifiedById
    CAMPAIGN_LASTMODIFIEDBYID("Campaign.LastModifiedById"),
    // Campaign.LastModifiedDate
    CAMPAIGN_LASTMODIFIEDDATE("Campaign.LastModifiedDate"),
    // Campaign.LastReferencedDate
    CAMPAIGN_LASTREFERENCEDDATE("Campaign.LastReferencedDate"),
    // Campaign.LastViewedDate
    CAMPAIGN_LASTVIEWEDDATE("Campaign.LastViewedDate"),
    // Campaign.Name
    CAMPAIGN_NAME("Campaign.Name"),
    // Campaign.NumberOfContacts
    CAMPAIGN_NUMBEROFCONTACTS("Campaign.NumberOfContacts"),
    // Campaign.NumberOfConvertedLeads
    CAMPAIGN_NUMBEROFCONVERTEDLEADS("Campaign.NumberOfConvertedLeads"),
    // Campaign.NumberOfLeads
    CAMPAIGN_NUMBEROFLEADS("Campaign.NumberOfLeads"),
    // Campaign.NumberOfOpportunities
    CAMPAIGN_NUMBEROFOPPORTUNITIES("Campaign.NumberOfOpportunities"),
    // Campaign.NumberOfResponses
    CAMPAIGN_NUMBEROFRESPONSES("Campaign.NumberOfResponses"),
    // Campaign.NumberOfWonOpportunities
    CAMPAIGN_NUMBEROFWONOPPORTUNITIES("Campaign.NumberOfWonOpportunities"),
    // Campaign.NumberSent
    CAMPAIGN_NUMBERSENT("Campaign.NumberSent"),
    // Campaign.OwnerId
    CAMPAIGN_OWNERID("Campaign.OwnerId"),
    // Campaign.ParentId
    CAMPAIGN_PARENTID("Campaign.ParentId"),
    // Campaign.StartDate
    CAMPAIGN_STARTDATE("Campaign.StartDate"),
    // Campaign.Status
    CAMPAIGN_STATUS("Campaign.Status"),
    // Campaign.SystemModstamp
    CAMPAIGN_SYSTEMMODSTAMP("Campaign.SystemModstamp"),
    // Campaign.Type
    CAMPAIGN_TYPE("Campaign.Type"),
    // Case.AccountId
    CASE_ACCOUNTID("Case.AccountId"),
    // Case.AssetId
    CASE_ASSETID("Case.AssetId"),
    // Case.CaseNumber
    CASE_CASENUMBER("Case.CaseNumber"),
    // Case.ClosedDate
    CASE_CLOSEDDATE("Case.ClosedDate"),
    // Case.ContactId
    CASE_CONTACTID("Case.ContactId"),
    // Case.CreatedById
    CASE_CREATEDBYID("Case.CreatedById"),
    // Case.CreatedDate
    CASE_CREATEDDATE("Case.CreatedDate"),
    // Case.Description
    CASE_DESCRIPTION("Case.Description"),
    // Case.Id
    CASE_ID("Case.Id"),
    // Case.IsClosed
    CASE_ISCLOSED("Case.IsClosed"),
    // Case.IsDeleted
    CASE_ISDELETED("Case.IsDeleted"),
    // Case.IsEscalated
    CASE_ISESCALATED("Case.IsEscalated"),
    // Case.LastModifiedById
    CASE_LASTMODIFIEDBYID("Case.LastModifiedById"),
    // Case.LastModifiedDate
    CASE_LASTMODIFIEDDATE("Case.LastModifiedDate"),
    // Case.LastReferencedDate
    CASE_LASTREFERENCEDDATE("Case.LastReferencedDate"),
    // Case.LastViewedDate
    CASE_LASTVIEWEDDATE("Case.LastViewedDate"),
    // Case.Origin
    CASE_ORIGIN("Case.Origin"),
    // Case.OwnerId
    CASE_OWNERID("Case.OwnerId"),
    // Case.ParentId
    CASE_PARENTID("Case.ParentId"),
    // Case.Priority
    CASE_PRIORITY("Case.Priority"),
    // Case.Reason
    CASE_REASON("Case.Reason"),
    // Case.Status
    CASE_STATUS("Case.Status"),
    // Case.Subject
    CASE_SUBJECT("Case.Subject"),
    // Case.SuppliedCompany
    CASE_SUPPLIEDCOMPANY("Case.SuppliedCompany"),
    // Case.SuppliedEmail
    CASE_SUPPLIEDEMAIL("Case.SuppliedEmail"),
    // Case.SuppliedName
    CASE_SUPPLIEDNAME("Case.SuppliedName"),
    // Case.SuppliedPhone
    CASE_SUPPLIEDPHONE("Case.SuppliedPhone"),
    // Case.SystemModstamp
    CASE_SYSTEMMODSTAMP("Case.SystemModstamp"),
    // Case.Type
    CASE_TYPE("Case.Type"),
    // CollaborationGroup.AnnouncementId
    COLLABORATIONGROUP_ANNOUNCEMENTID("CollaborationGroup.AnnouncementId"),
    // CollaborationGroup.CanHaveGuests
    COLLABORATIONGROUP_CANHAVEGUESTS("CollaborationGroup.CanHaveGuests"),
    // CollaborationGroup.CollaborationType
    COLLABORATIONGROUP_COLLABORATIONTYPE("CollaborationGroup.CollaborationType"),
    // CollaborationGroup.CreatedById
    COLLABORATIONGROUP_CREATEDBYID("CollaborationGroup.CreatedById"),
    // CollaborationGroup.CreatedDate
    COLLABORATIONGROUP_CREATEDDATE("CollaborationGroup.CreatedDate"),
    // CollaborationGroup.Description
    COLLABORATIONGROUP_DESCRIPTION("CollaborationGroup.Description"),
    // CollaborationGroup.FullPhotoUrl
    COLLABORATIONGROUP_FULLPHOTOURL("CollaborationGroup.FullPhotoUrl"),
    // CollaborationGroup.GroupEmail
    COLLABORATIONGROUP_GROUPEMAIL("CollaborationGroup.GroupEmail"),
    // CollaborationGroup.HasPrivateFieldsAccess
    COLLABORATIONGROUP_HASPRIVATEFIELDSACCESS("CollaborationGroup.HasPrivateFieldsAccess"),
    // CollaborationGroup.Id
    COLLABORATIONGROUP_ID("CollaborationGroup.Id"),
    // CollaborationGroup.InformationBody
    COLLABORATIONGROUP_INFORMATIONBODY("CollaborationGroup.InformationBody"),
    // CollaborationGroup.InformationTitle
    COLLABORATIONGROUP_INFORMATIONTITLE("CollaborationGroup.InformationTitle"),
    // CollaborationGroup.IsArchived
    COLLABORATIONGROUP_ISARCHIVED("CollaborationGroup.IsArchived"),
    // CollaborationGroup.IsAutoArchiveDisabled
    COLLABORATIONGROUP_ISAUTOARCHIVEDISABLED("CollaborationGroup.IsAutoArchiveDisabled"),
    // CollaborationGroup.LastFeedModifiedDate
    COLLABORATIONGROUP_LASTFEEDMODIFIEDDATE("CollaborationGroup.LastFeedModifiedDate"),
    // CollaborationGroup.LastModifiedById
    COLLABORATIONGROUP_LASTMODIFIEDBYID("CollaborationGroup.LastModifiedById"),
    // CollaborationGroup.LastModifiedDate
    COLLABORATIONGROUP_LASTMODIFIEDDATE("CollaborationGroup.LastModifiedDate"),
    // CollaborationGroup.LastReferencedDate
    COLLABORATIONGROUP_LASTREFERENCEDDATE("CollaborationGroup.LastReferencedDate"),
    // CollaborationGroup.LastViewedDate
    COLLABORATIONGROUP_LASTVIEWEDDATE("CollaborationGroup.LastViewedDate"),
    // CollaborationGroup.MemberCount
    COLLABORATIONGROUP_MEMBERCOUNT("CollaborationGroup.MemberCount"),
    // CollaborationGroup.Name
    COLLABORATIONGROUP_NAME("CollaborationGroup.Name"),
    // CollaborationGroup.OwnerId
    COLLABORATIONGROUP_OWNERID("CollaborationGroup.OwnerId"),
    // CollaborationGroup.SmallPhotoUrl
    COLLABORATIONGROUP_SMALLPHOTOURL("CollaborationGroup.SmallPhotoUrl"),
    // CollaborationGroup.SystemModstamp
    COLLABORATIONGROUP_SYSTEMMODSTAMP("CollaborationGroup.SystemModstamp"),
    // Contact.AccountId
    CONTACT_ACCOUNTID("Contact.AccountId"),
    // Contact.AssistantName
    CONTACT_ASSISTANTNAME("Contact.AssistantName"),
    // Contact.AssistantPhone
    CONTACT_ASSISTANTPHONE("Contact.AssistantPhone"),
    // Contact.Birthdate
    CONTACT_BIRTHDATE("Contact.Birthdate"),
    // Contact.CleanStatus
    CONTACT_CLEANSTATUS("Contact.CleanStatus"),
    // Contact.CreatedById
    CONTACT_CREATEDBYID("Contact.CreatedById"),
    // Contact.CreatedDate
    CONTACT_CREATEDDATE("Contact.CreatedDate"),
    // Contact.Department
    CONTACT_DEPARTMENT("Contact.Department"),
    // Contact.Description
    CONTACT_DESCRIPTION("Contact.Description"),
    // Contact.Email
    CONTACT_EMAIL("Contact.Email"),
    // Contact.EmailBouncedDate
    CONTACT_EMAILBOUNCEDDATE("Contact.EmailBouncedDate"),
    // Contact.EmailBouncedReason
    CONTACT_EMAILBOUNCEDREASON("Contact.EmailBouncedReason"),
    // Contact.Fax
    CONTACT_FAX("Contact.Fax"),
    // Contact.FirstName
    CONTACT_FIRSTNAME("Contact.FirstName"),
    // Contact.HomePhone
    CONTACT_HOMEPHONE("Contact.HomePhone"),
    // Contact.Id
    CONTACT_ID("Contact.Id"),
    // Contact.IsDeleted
    CONTACT_ISDELETED("Contact.IsDeleted"),
    // Contact.IsEmailBounced
    CONTACT_ISEMAILBOUNCED("Contact.IsEmailBounced"),
    // Contact.Jigsaw
    CONTACT_JIGSAW("Contact.Jigsaw"),
    // Contact.JigsawContactId
    CONTACT_JIGSAWCONTACTID("Contact.JigsawContactId"),
    // Contact.LastActivityDate
    CONTACT_LASTACTIVITYDATE("Contact.LastActivityDate"),
    // Contact.LastCURequestDate
    CONTACT_LASTCUREQUESTDATE("Contact.LastCURequestDate"),
    // Contact.LastCUUpdateDate
    CONTACT_LASTCUUPDATEDATE("Contact.LastCUUpdateDate"),
    // Contact.LastModifiedById
    CONTACT_LASTMODIFIEDBYID("Contact.LastModifiedById"),
    // Contact.LastModifiedDate
    CONTACT_LASTMODIFIEDDATE("Contact.LastModifiedDate"),
    // Contact.LastName
    CONTACT_LASTNAME("Contact.LastName"),
    // Contact.LastReferencedDate
    CONTACT_LASTREFERENCEDDATE("Contact.LastReferencedDate"),
    // Contact.LastViewedDate
    CONTACT_LASTVIEWEDDATE("Contact.LastViewedDate"),
    // Contact.LeadSource
    CONTACT_LEADSOURCE("Contact.LeadSource"),
    // Contact.MailingAddress
    CONTACT_MAILINGADDRESS("Contact.MailingAddress"),
    // Contact.MailingCity
    CONTACT_MAILINGCITY("Contact.MailingCity"),
    // Contact.MailingCountry
    CONTACT_MAILINGCOUNTRY("Contact.MailingCountry"),
    // Contact.MailingLatitude
    CONTACT_MAILINGLATITUDE("Contact.MailingLatitude"),
    // Contact.MailingLongitude
    CONTACT_MAILINGLONGITUDE("Contact.MailingLongitude"),
    // Contact.MailingPostalCode
    CONTACT_MAILINGPOSTALCODE("Contact.MailingPostalCode"),
    // Contact.MailingState
    CONTACT_MAILINGSTATE("Contact.MailingState"),
    // Contact.MailingStreet
    CONTACT_MAILINGSTREET("Contact.MailingStreet"),
    // Contact.MasterRecordId
    CONTACT_MASTERRECORDID("Contact.MasterRecordId"),
    // Contact.MobilePhone
    CONTACT_MOBILEPHONE("Contact.MobilePhone"),
    // Contact.Name
    CONTACT_NAME("Contact.Name"),
    // Contact.OtherAddress
    CONTACT_OTHERADDRESS("Contact.OtherAddress"),
    // Contact.OtherCity
    CONTACT_OTHERCITY("Contact.OtherCity"),
    // Contact.OtherCountry
    CONTACT_OTHERCOUNTRY("Contact.OtherCountry"),
    // Contact.OtherLatitude
    CONTACT_OTHERLATITUDE("Contact.OtherLatitude"),
    // Contact.OtherLongitude
    CONTACT_OTHERLONGITUDE("Contact.OtherLongitude"),
    // Contact.OtherPhone
    CONTACT_OTHERPHONE("Contact.OtherPhone"),
    // Contact.OtherPostalCode
    CONTACT_OTHERPOSTALCODE("Contact.OtherPostalCode"),
    // Contact.OtherState
    CONTACT_OTHERSTATE("Contact.OtherState"),
    // Contact.OtherStreet
    CONTACT_OTHERSTREET("Contact.OtherStreet"),
    // Contact.OwnerId
    CONTACT_OWNERID("Contact.OwnerId"),
    // Contact.Phone
    CONTACT_PHONE("Contact.Phone"),
    // Contact.PhotoUrl
    CONTACT_PHOTOURL("Contact.PhotoUrl"),
    // Contact.ReportsToId
    CONTACT_REPORTSTOID("Contact.ReportsToId"),
    // Contact.Salutation
    CONTACT_SALUTATION("Contact.Salutation"),
    // Contact.SystemModstamp
    CONTACT_SYSTEMMODSTAMP("Contact.SystemModstamp"),
    // Contact.Title
    CONTACT_TITLE("Contact.Title"),
    // Contract.AccountId
    CONTRACT_ACCOUNTID("Contract.AccountId"),
    // Contract.ActivatedById
    CONTRACT_ACTIVATEDBYID("Contract.ActivatedById"),
    // Contract.ActivatedDate
    CONTRACT_ACTIVATEDDATE("Contract.ActivatedDate"),
    // Contract.BillingAddress
    CONTRACT_BILLINGADDRESS("Contract.BillingAddress"),
    // Contract.BillingCity
    CONTRACT_BILLINGCITY("Contract.BillingCity"),
    // Contract.BillingCountry
    CONTRACT_BILLINGCOUNTRY("Contract.BillingCountry"),
    // Contract.BillingLatitude
    CONTRACT_BILLINGLATITUDE("Contract.BillingLatitude"),
    // Contract.BillingLongitude
    CONTRACT_BILLINGLONGITUDE("Contract.BillingLongitude"),
    // Contract.BillingPostalCode
    CONTRACT_BILLINGPOSTALCODE("Contract.BillingPostalCode"),
    // Contract.BillingState
    CONTRACT_BILLINGSTATE("Contract.BillingState"),
    // Contract.BillingStreet
    CONTRACT_BILLINGSTREET("Contract.BillingStreet"),
    // Contract.CompanySignedDate
    CONTRACT_COMPANYSIGNEDDATE("Contract.CompanySignedDate"),
    // Contract.CompanySignedId
    CONTRACT_COMPANYSIGNEDID("Contract.CompanySignedId"),
    // Contract.ContractNumber
    CONTRACT_CONTRACTNUMBER("Contract.ContractNumber"),
    // Contract.ContractTerm
    CONTRACT_CONTRACTTERM("Contract.ContractTerm"),
    // Contract.CreatedById
    CONTRACT_CREATEDBYID("Contract.CreatedById"),
    // Contract.CreatedDate
    CONTRACT_CREATEDDATE("Contract.CreatedDate"),
    // Contract.CustomerSignedDate
    CONTRACT_CUSTOMERSIGNEDDATE("Contract.CustomerSignedDate"),
    // Contract.CustomerSignedId
    CONTRACT_CUSTOMERSIGNEDID("Contract.CustomerSignedId"),
    // Contract.CustomerSignedTitle
    CONTRACT_CUSTOMERSIGNEDTITLE("Contract.CustomerSignedTitle"),
    // Contract.Description
    CONTRACT_DESCRIPTION("Contract.Description"),
    // Contract.EndDate
    CONTRACT_ENDDATE("Contract.EndDate"),
    // Contract.Id
    CONTRACT_ID("Contract.Id"),
    // Contract.IsDeleted
    CONTRACT_ISDELETED("Contract.IsDeleted"),
    // Contract.LastActivityDate
    CONTRACT_LASTACTIVITYDATE("Contract.LastActivityDate"),
    // Contract.LastApprovedDate
    CONTRACT_LASTAPPROVEDDATE("Contract.LastApprovedDate"),
    // Contract.LastModifiedById
    CONTRACT_LASTMODIFIEDBYID("Contract.LastModifiedById"),
    // Contract.LastModifiedDate
    CONTRACT_LASTMODIFIEDDATE("Contract.LastModifiedDate"),
    // Contract.LastReferencedDate
    CONTRACT_LASTREFERENCEDDATE("Contract.LastReferencedDate"),
    // Contract.LastViewedDate
    CONTRACT_LASTVIEWEDDATE("Contract.LastViewedDate"),
    // Contract.OwnerExpirationNotice
    CONTRACT_OWNEREXPIRATIONNOTICE("Contract.OwnerExpirationNotice"),
    // Contract.OwnerId
    CONTRACT_OWNERID("Contract.OwnerId"),
    // Contract.Pricebook2Id
    CONTRACT_PRICEBOOK2ID("Contract.Pricebook2Id"),
    // Contract.SpecialTerms
    CONTRACT_SPECIALTERMS("Contract.SpecialTerms"),
    // Contract.StartDate
    CONTRACT_STARTDATE("Contract.StartDate"),
    // Contract.Status
    CONTRACT_STATUS("Contract.Status"),
    // Contract.StatusCode
    CONTRACT_STATUSCODE("Contract.StatusCode"),
    // Contract.SystemModstamp
    CONTRACT_SYSTEMMODSTAMP("Contract.SystemModstamp"),
    // DandBCompany.Address
    DANDBCOMPANY_ADDRESS("DandBCompany.Address"),
    // DandBCompany.City
    DANDBCOMPANY_CITY("DandBCompany.City"),
    // DandBCompany.CompanyCurrencyIsoCode
    DANDBCOMPANY_COMPANYCURRENCYISOCODE("DandBCompany.CompanyCurrencyIsoCode"),
    // DandBCompany.Country
    DANDBCOMPANY_COUNTRY("DandBCompany.Country"),
    // DandBCompany.CountryAccessCode
    DANDBCOMPANY_COUNTRYACCESSCODE("DandBCompany.CountryAccessCode"),
    // DandBCompany.CreatedById
    DANDBCOMPANY_CREATEDBYID("DandBCompany.CreatedById"),
    // DandBCompany.CreatedDate
    DANDBCOMPANY_CREATEDDATE("DandBCompany.CreatedDate"),
    // DandBCompany.CurrencyCode
    DANDBCOMPANY_CURRENCYCODE("DandBCompany.CurrencyCode"),
    // DandBCompany.Description
    DANDBCOMPANY_DESCRIPTION("DandBCompany.Description"),
    // DandBCompany.DomesticUltimateBusinessName
    DANDBCOMPANY_DOMESTICULTIMATEBUSINESSNAME("DandBCompany.DomesticUltimateBusinessName"),
    // DandBCompany.DomesticUltimateDunsNumber
    DANDBCOMPANY_DOMESTICULTIMATEDUNSNUMBER("DandBCompany.DomesticUltimateDunsNumber"),
    // DandBCompany.DunsNumber
    DANDBCOMPANY_DUNSNUMBER("DandBCompany.DunsNumber"),
    // DandBCompany.EmployeesHere
    DANDBCOMPANY_EMPLOYEESHERE("DandBCompany.EmployeesHere"),
    // DandBCompany.EmployeesHereReliability
    DANDBCOMPANY_EMPLOYEESHERERELIABILITY("DandBCompany.EmployeesHereReliability"),
    // DandBCompany.EmployeesTotal
    DANDBCOMPANY_EMPLOYEESTOTAL("DandBCompany.EmployeesTotal"),
    // DandBCompany.EmployeesTotalReliability
    DANDBCOMPANY_EMPLOYEESTOTALRELIABILITY("DandBCompany.EmployeesTotalReliability"),
    // DandBCompany.FamilyMembers
    DANDBCOMPANY_FAMILYMEMBERS("DandBCompany.FamilyMembers"),
    // DandBCompany.Fax
    DANDBCOMPANY_FAX("DandBCompany.Fax"),
    // DandBCompany.FifthNaics
    DANDBCOMPANY_FIFTHNAICS("DandBCompany.FifthNaics"),
    // DandBCompany.FifthNaicsDesc
    DANDBCOMPANY_FIFTHNAICSDESC("DandBCompany.FifthNaicsDesc"),
    // DandBCompany.FifthSic
    DANDBCOMPANY_FIFTHSIC("DandBCompany.FifthSic"),
    // DandBCompany.FifthSicDesc
    DANDBCOMPANY_FIFTHSICDESC("DandBCompany.FifthSicDesc"),
    // DandBCompany.FipsMsaCode
    DANDBCOMPANY_FIPSMSACODE("DandBCompany.FipsMsaCode"),
    // DandBCompany.FipsMsaDesc
    DANDBCOMPANY_FIPSMSADESC("DandBCompany.FipsMsaDesc"),
    // DandBCompany.FourthNaics
    DANDBCOMPANY_FOURTHNAICS("DandBCompany.FourthNaics"),
    // DandBCompany.FourthNaicsDesc
    DANDBCOMPANY_FOURTHNAICSDESC("DandBCompany.FourthNaicsDesc"),
    // DandBCompany.FourthSic
    DANDBCOMPANY_FOURTHSIC("DandBCompany.FourthSic"),
    // DandBCompany.FourthSicDesc
    DANDBCOMPANY_FOURTHSICDESC("DandBCompany.FourthSicDesc"),
    // DandBCompany.GeoCodeAccuracy
    DANDBCOMPANY_GEOCODEACCURACY("DandBCompany.GeoCodeAccuracy"),
    // DandBCompany.GlobalUltimateBusinessName
    DANDBCOMPANY_GLOBALULTIMATEBUSINESSNAME("DandBCompany.GlobalUltimateBusinessName"),
    // DandBCompany.GlobalUltimateDunsNumber
    DANDBCOMPANY_GLOBALULTIMATEDUNSNUMBER("DandBCompany.GlobalUltimateDunsNumber"),
    // DandBCompany.GlobalUltimateTotalEmployees
    DANDBCOMPANY_GLOBALULTIMATETOTALEMPLOYEES("DandBCompany.GlobalUltimateTotalEmployees"),
    // DandBCompany.Id
    DANDBCOMPANY_ID("DandBCompany.Id"),
    // DandBCompany.ImportExportAgent
    DANDBCOMPANY_IMPORTEXPORTAGENT("DandBCompany.ImportExportAgent"),
    // DandBCompany.IsDeleted
    DANDBCOMPANY_ISDELETED("DandBCompany.IsDeleted"),
    // DandBCompany.LastModifiedById
    DANDBCOMPANY_LASTMODIFIEDBYID("DandBCompany.LastModifiedById"),
    // DandBCompany.LastModifiedDate
    DANDBCOMPANY_LASTMODIFIEDDATE("DandBCompany.LastModifiedDate"),
    // DandBCompany.Latitude
    DANDBCOMPANY_LATITUDE("DandBCompany.Latitude"),
    // DandBCompany.LegalStatus
    DANDBCOMPANY_LEGALSTATUS("DandBCompany.LegalStatus"),
    // DandBCompany.LocationStatus
    DANDBCOMPANY_LOCATIONSTATUS("DandBCompany.LocationStatus"),
    // DandBCompany.Longitude
    DANDBCOMPANY_LONGITUDE("DandBCompany.Longitude"),
    // DandBCompany.MailingAddress
    DANDBCOMPANY_MAILINGADDRESS("DandBCompany.MailingAddress"),
    // DandBCompany.MailingCity
    DANDBCOMPANY_MAILINGCITY("DandBCompany.MailingCity"),
    // DandBCompany.MailingCountry
    DANDBCOMPANY_MAILINGCOUNTRY("DandBCompany.MailingCountry"),
    // DandBCompany.MailingPostalCode
    DANDBCOMPANY_MAILINGPOSTALCODE("DandBCompany.MailingPostalCode"),
    // DandBCompany.MailingState
    DANDBCOMPANY_MAILINGSTATE("DandBCompany.MailingState"),
    // DandBCompany.MailingStreet
    DANDBCOMPANY_MAILINGSTREET("DandBCompany.MailingStreet"),
    // DandBCompany.MarketingPreScreen
    DANDBCOMPANY_MARKETINGPRESCREEN("DandBCompany.MarketingPreScreen"),
    // DandBCompany.MarketingSegmentationCluster
    DANDBCOMPANY_MARKETINGSEGMENTATIONCLUSTER("DandBCompany.MarketingSegmentationCluster"),
    // DandBCompany.MinorityOwned
    DANDBCOMPANY_MINORITYOWNED("DandBCompany.MinorityOwned"),
    // DandBCompany.Name
    DANDBCOMPANY_NAME("DandBCompany.Name"),
    // DandBCompany.NationalId
    DANDBCOMPANY_NATIONALID("DandBCompany.NationalId"),
    // DandBCompany.NationalIdType
    DANDBCOMPANY_NATIONALIDTYPE("DandBCompany.NationalIdType"),
    // DandBCompany.OutOfBusiness
    DANDBCOMPANY_OUTOFBUSINESS("DandBCompany.OutOfBusiness"),
    // DandBCompany.OwnOrRent
    DANDBCOMPANY_OWNORRENT("DandBCompany.OwnOrRent"),
    // DandBCompany.ParentOrHqBusinessName
    DANDBCOMPANY_PARENTORHQBUSINESSNAME("DandBCompany.ParentOrHqBusinessName"),
    // DandBCompany.ParentOrHqDunsNumber
    DANDBCOMPANY_PARENTORHQDUNSNUMBER("DandBCompany.ParentOrHqDunsNumber"),
    // DandBCompany.Phone
    DANDBCOMPANY_PHONE("DandBCompany.Phone"),
    // DandBCompany.PostalCode
    DANDBCOMPANY_POSTALCODE("DandBCompany.PostalCode"),
    // DandBCompany.PrimaryNaics
    DANDBCOMPANY_PRIMARYNAICS("DandBCompany.PrimaryNaics"),
    // DandBCompany.PrimaryNaicsDesc
    DANDBCOMPANY_PRIMARYNAICSDESC("DandBCompany.PrimaryNaicsDesc"),
    // DandBCompany.PrimarySic
    DANDBCOMPANY_PRIMARYSIC("DandBCompany.PrimarySic"),
    // DandBCompany.PrimarySicDesc
    DANDBCOMPANY_PRIMARYSICDESC("DandBCompany.PrimarySicDesc"),
    // DandBCompany.PublicIndicator
    DANDBCOMPANY_PUBLICINDICATOR("DandBCompany.PublicIndicator"),
    // DandBCompany.SalesVolume
    DANDBCOMPANY_SALESVOLUME("DandBCompany.SalesVolume"),
    // DandBCompany.SalesVolumeReliability
    DANDBCOMPANY_SALESVOLUMERELIABILITY("DandBCompany.SalesVolumeReliability"),
    // DandBCompany.SecondNaics
    DANDBCOMPANY_SECONDNAICS("DandBCompany.SecondNaics"),
    // DandBCompany.SecondNaicsDesc
    DANDBCOMPANY_SECONDNAICSDESC("DandBCompany.SecondNaicsDesc"),
    // DandBCompany.SecondSic
    DANDBCOMPANY_SECONDSIC("DandBCompany.SecondSic"),
    // DandBCompany.SecondSicDesc
    DANDBCOMPANY_SECONDSICDESC("DandBCompany.SecondSicDesc"),
    // DandBCompany.SixthNaics
    DANDBCOMPANY_SIXTHNAICS("DandBCompany.SixthNaics"),
    // DandBCompany.SixthNaicsDesc
    DANDBCOMPANY_SIXTHNAICSDESC("DandBCompany.SixthNaicsDesc"),
    // DandBCompany.SixthSic
    DANDBCOMPANY_SIXTHSIC("DandBCompany.SixthSic"),
    // DandBCompany.SixthSicDesc
    DANDBCOMPANY_SIXTHSICDESC("DandBCompany.SixthSicDesc"),
    // DandBCompany.SmallBusiness
    DANDBCOMPANY_SMALLBUSINESS("DandBCompany.SmallBusiness"),
    // DandBCompany.State
    DANDBCOMPANY_STATE("DandBCompany.State"),
    // DandBCompany.StockExchange
    DANDBCOMPANY_STOCKEXCHANGE("DandBCompany.StockExchange"),
    // DandBCompany.StockSymbol
    DANDBCOMPANY_STOCKSYMBOL("DandBCompany.StockSymbol"),
    // DandBCompany.Street
    DANDBCOMPANY_STREET("DandBCompany.Street"),
    // DandBCompany.Subsidiary
    DANDBCOMPANY_SUBSIDIARY("DandBCompany.Subsidiary"),
    // DandBCompany.SystemModstamp
    DANDBCOMPANY_SYSTEMMODSTAMP("DandBCompany.SystemModstamp"),
    // DandBCompany.ThirdNaics
    DANDBCOMPANY_THIRDNAICS("DandBCompany.ThirdNaics"),
    // DandBCompany.ThirdNaicsDesc
    DANDBCOMPANY_THIRDNAICSDESC("DandBCompany.ThirdNaicsDesc"),
    // DandBCompany.ThirdSic
    DANDBCOMPANY_THIRDSIC("DandBCompany.ThirdSic"),
    // DandBCompany.ThirdSicDesc
    DANDBCOMPANY_THIRDSICDESC("DandBCompany.ThirdSicDesc"),
    // DandBCompany.TradeStyle1
    DANDBCOMPANY_TRADESTYLE1("DandBCompany.TradeStyle1"),
    // DandBCompany.TradeStyle2
    DANDBCOMPANY_TRADESTYLE2("DandBCompany.TradeStyle2"),
    // DandBCompany.TradeStyle3
    DANDBCOMPANY_TRADESTYLE3("DandBCompany.TradeStyle3"),
    // DandBCompany.TradeStyle4
    DANDBCOMPANY_TRADESTYLE4("DandBCompany.TradeStyle4"),
    // DandBCompany.TradeStyle5
    DANDBCOMPANY_TRADESTYLE5("DandBCompany.TradeStyle5"),
    // DandBCompany.URL
    DANDBCOMPANY_URL("DandBCompany.URL"),
    // DandBCompany.UsTaxId
    DANDBCOMPANY_USTAXID("DandBCompany.UsTaxId"),
    // DandBCompany.WomenOwned
    DANDBCOMPANY_WOMENOWNED("DandBCompany.WomenOwned"),
    // DandBCompany.YearStarted
    DANDBCOMPANY_YEARSTARTED("DandBCompany.YearStarted"),
    // DuplicateRecordItem.CreatedById
    DUPLICATERECORDITEM_CREATEDBYID("DuplicateRecordItem.CreatedById"),
    // DuplicateRecordItem.CreatedDate
    DUPLICATERECORDITEM_CREATEDDATE("DuplicateRecordItem.CreatedDate"),
    // DuplicateRecordItem.DuplicateRecordSetId
    DUPLICATERECORDITEM_DUPLICATERECORDSETID("DuplicateRecordItem.DuplicateRecordSetId"),
    // DuplicateRecordItem.Id
    DUPLICATERECORDITEM_ID("DuplicateRecordItem.Id"),
    // DuplicateRecordItem.IsDeleted
    DUPLICATERECORDITEM_ISDELETED("DuplicateRecordItem.IsDeleted"),
    // DuplicateRecordItem.LastModifiedById
    DUPLICATERECORDITEM_LASTMODIFIEDBYID("DuplicateRecordItem.LastModifiedById"),
    // DuplicateRecordItem.LastModifiedDate
    DUPLICATERECORDITEM_LASTMODIFIEDDATE("DuplicateRecordItem.LastModifiedDate"),
    // DuplicateRecordItem.Name
    DUPLICATERECORDITEM_NAME("DuplicateRecordItem.Name"),
    // DuplicateRecordItem.RecordId
    DUPLICATERECORDITEM_RECORDID("DuplicateRecordItem.RecordId"),
    // DuplicateRecordItem.SystemModstamp
    DUPLICATERECORDITEM_SYSTEMMODSTAMP("DuplicateRecordItem.SystemModstamp"),
    // DuplicateRecordSet.CreatedById
    DUPLICATERECORDSET_CREATEDBYID("DuplicateRecordSet.CreatedById"),
    // DuplicateRecordSet.CreatedDate
    DUPLICATERECORDSET_CREATEDDATE("DuplicateRecordSet.CreatedDate"),
    // DuplicateRecordSet.DuplicateRuleId
    DUPLICATERECORDSET_DUPLICATERULEID("DuplicateRecordSet.DuplicateRuleId"),
    // DuplicateRecordSet.Id
    DUPLICATERECORDSET_ID("DuplicateRecordSet.Id"),
    // DuplicateRecordSet.IsDeleted
    DUPLICATERECORDSET_ISDELETED("DuplicateRecordSet.IsDeleted"),
    // DuplicateRecordSet.LastModifiedById
    DUPLICATERECORDSET_LASTMODIFIEDBYID("DuplicateRecordSet.LastModifiedById"),
    // DuplicateRecordSet.LastModifiedDate
    DUPLICATERECORDSET_LASTMODIFIEDDATE("DuplicateRecordSet.LastModifiedDate"),
    // DuplicateRecordSet.LastReferencedDate
    DUPLICATERECORDSET_LASTREFERENCEDDATE("DuplicateRecordSet.LastReferencedDate"),
    // DuplicateRecordSet.LastViewedDate
    DUPLICATERECORDSET_LASTVIEWEDDATE("DuplicateRecordSet.LastViewedDate"),
    // DuplicateRecordSet.Name
    DUPLICATERECORDSET_NAME("DuplicateRecordSet.Name"),
    // DuplicateRecordSet.RecordCount
    DUPLICATERECORDSET_RECORDCOUNT("DuplicateRecordSet.RecordCount"),
    // DuplicateRecordSet.SystemModstamp
    DUPLICATERECORDSET_SYSTEMMODSTAMP("DuplicateRecordSet.SystemModstamp"),
    // FlowInterview.CreatedById
    FLOWINTERVIEW_CREATEDBYID("FlowInterview.CreatedById"),
    // FlowInterview.CreatedDate
    FLOWINTERVIEW_CREATEDDATE("FlowInterview.CreatedDate"),
    // FlowInterview.CurrentElement
    FLOWINTERVIEW_CURRENTELEMENT("FlowInterview.CurrentElement"),
    // FlowInterview.Id
    FLOWINTERVIEW_ID("FlowInterview.Id"),
    // FlowInterview.InterviewLabel
    FLOWINTERVIEW_INTERVIEWLABEL("FlowInterview.InterviewLabel"),
    // FlowInterview.IsDeleted
    FLOWINTERVIEW_ISDELETED("FlowInterview.IsDeleted"),
    // FlowInterview.LastModifiedById
    FLOWINTERVIEW_LASTMODIFIEDBYID("FlowInterview.LastModifiedById"),
    // FlowInterview.LastModifiedDate
    FLOWINTERVIEW_LASTMODIFIEDDATE("FlowInterview.LastModifiedDate"),
    // FlowInterview.Name
    FLOWINTERVIEW_NAME("FlowInterview.Name"),
    // FlowInterview.OwnerId
    FLOWINTERVIEW_OWNERID("FlowInterview.OwnerId"),
    // FlowInterview.PauseLabel
    FLOWINTERVIEW_PAUSELABEL("FlowInterview.PauseLabel"),
    // FlowInterview.SystemModstamp
    FLOWINTERVIEW_SYSTEMMODSTAMP("FlowInterview.SystemModstamp"),
    // Goal.CompletionDate
    GOAL_COMPLETIONDATE("Goal.CompletionDate"),
    // Goal.CreatedById
    GOAL_CREATEDBYID("Goal.CreatedById"),
    // Goal.CreatedDate
    GOAL_CREATEDDATE("Goal.CreatedDate"),
    // Goal.Description
    GOAL_DESCRIPTION("Goal.Description"),
    // Goal.DueDate
    GOAL_DUEDATE("Goal.DueDate"),
    // Goal.Id
    GOAL_ID("Goal.Id"),
    // Goal.ImageUrl
    GOAL_IMAGEURL("Goal.ImageUrl"),
    // Goal.IsDeleted
    GOAL_ISDELETED("Goal.IsDeleted"),
    // Goal.IsKeyCompanyGoal
    GOAL_ISKEYCOMPANYGOAL("Goal.IsKeyCompanyGoal"),
    // Goal.LastModifiedById
    GOAL_LASTMODIFIEDBYID("Goal.LastModifiedById"),
    // Goal.LastModifiedDate
    GOAL_LASTMODIFIEDDATE("Goal.LastModifiedDate"),
    // Goal.LastReferencedDate
    GOAL_LASTREFERENCEDDATE("Goal.LastReferencedDate"),
    // Goal.LastViewedDate
    GOAL_LASTVIEWEDDATE("Goal.LastViewedDate"),
    // Goal.Name
    GOAL_NAME("Goal.Name"),
    // Goal.OwnerId
    GOAL_OWNERID("Goal.OwnerId"),
    // Goal.Progress
    GOAL_PROGRESS("Goal.Progress"),
    // Goal.StartDate
    GOAL_STARTDATE("Goal.StartDate"),
    // Goal.Status
    GOAL_STATUS("Goal.Status"),
    // Goal.SystemModstamp
    GOAL_SYSTEMMODSTAMP("Goal.SystemModstamp"),
    // GoalLink.CreatedById
    GOALLINK_CREATEDBYID("GoalLink.CreatedById"),
    // GoalLink.CreatedDate
    GOALLINK_CREATEDDATE("GoalLink.CreatedDate"),
    // GoalLink.Id
    GOALLINK_ID("GoalLink.Id"),
    // GoalLink.IsDeleted
    GOALLINK_ISDELETED("GoalLink.IsDeleted"),
    // GoalLink.LastModifiedById
    GOALLINK_LASTMODIFIEDBYID("GoalLink.LastModifiedById"),
    // GoalLink.LastModifiedDate
    GOALLINK_LASTMODIFIEDDATE("GoalLink.LastModifiedDate"),
    // GoalLink.Name
    GOALLINK_NAME("GoalLink.Name"),
    // GoalLink.ParentGoalId
    GOALLINK_PARENTGOALID("GoalLink.ParentGoalId"),
    // GoalLink.SubgoalId
    GOALLINK_SUBGOALID("GoalLink.SubgoalId"),
    // GoalLink.SystemModstamp
    GOALLINK_SYSTEMMODSTAMP("GoalLink.SystemModstamp"),
    // Idea.Body
    IDEA_BODY("Idea.Body"),
    // Idea.Categories
    IDEA_CATEGORIES("Idea.Categories"),
    // Idea.CommunityId
    IDEA_COMMUNITYID("Idea.CommunityId"),
    // Idea.CreatedById
    IDEA_CREATEDBYID("Idea.CreatedById"),
    // Idea.CreatedDate
    IDEA_CREATEDDATE("Idea.CreatedDate"),
    // Idea.CreatorFullPhotoUrl
    IDEA_CREATORFULLPHOTOURL("Idea.CreatorFullPhotoUrl"),
    // Idea.CreatorName
    IDEA_CREATORNAME("Idea.CreatorName"),
    // Idea.CreatorSmallPhotoUrl
    IDEA_CREATORSMALLPHOTOURL("Idea.CreatorSmallPhotoUrl"),
    // Idea.Id
    IDEA_ID("Idea.Id"),
    // Idea.IsDeleted
    IDEA_ISDELETED("Idea.IsDeleted"),
    // Idea.IsHtml
    IDEA_ISHTML("Idea.IsHtml"),
    // Idea.IsMerged
    IDEA_ISMERGED("Idea.IsMerged"),
    // Idea.LastCommentDate
    IDEA_LASTCOMMENTDATE("Idea.LastCommentDate"),
    // Idea.LastCommentId
    IDEA_LASTCOMMENTID("Idea.LastCommentId"),
    // Idea.LastModifiedById
    IDEA_LASTMODIFIEDBYID("Idea.LastModifiedById"),
    // Idea.LastModifiedDate
    IDEA_LASTMODIFIEDDATE("Idea.LastModifiedDate"),
    // Idea.LastReferencedDate
    IDEA_LASTREFERENCEDDATE("Idea.LastReferencedDate"),
    // Idea.LastViewedDate
    IDEA_LASTVIEWEDDATE("Idea.LastViewedDate"),
    // Idea.NumComments
    IDEA_NUMCOMMENTS("Idea.NumComments"),
    // Idea.ParentIdeaId
    IDEA_PARENTIDEAID("Idea.ParentIdeaId"),
    // Idea.RecordTypeId
    IDEA_RECORDTYPEID("Idea.RecordTypeId"),
    // Idea.Status
    IDEA_STATUS("Idea.Status"),
    // Idea.SystemModstamp
    IDEA_SYSTEMMODSTAMP("Idea.SystemModstamp"),
    // Idea.Title
    IDEA_TITLE("Idea.Title"),
    // Idea.VoteScore
    IDEA_VOTESCORE("Idea.VoteScore"),
    // Idea.VoteTotal
    IDEA_VOTETOTAL("Idea.VoteTotal"),
    // Lead.Address
    LEAD_ADDRESS("Lead.Address"),
    // Lead.AnnualRevenue
    LEAD_ANNUALREVENUE("Lead.AnnualRevenue"),
    // Lead.City
    LEAD_CITY("Lead.City"),
    // Lead.CleanStatus
    LEAD_CLEANSTATUS("Lead.CleanStatus"),
    // Lead.Company
    LEAD_COMPANY("Lead.Company"),
    // Lead.CompanyDunsNumber
    LEAD_COMPANYDUNSNUMBER("Lead.CompanyDunsNumber"),
    // Lead.ConvertedAccountId
    LEAD_CONVERTEDACCOUNTID("Lead.ConvertedAccountId"),
    // Lead.ConvertedContactId
    LEAD_CONVERTEDCONTACTID("Lead.ConvertedContactId"),
    // Lead.ConvertedDate
    LEAD_CONVERTEDDATE("Lead.ConvertedDate"),
    // Lead.ConvertedOpportunityId
    LEAD_CONVERTEDOPPORTUNITYID("Lead.ConvertedOpportunityId"),
    // Lead.Country
    LEAD_COUNTRY("Lead.Country"),
    // Lead.CreatedById
    LEAD_CREATEDBYID("Lead.CreatedById"),
    // Lead.CreatedDate
    LEAD_CREATEDDATE("Lead.CreatedDate"),
    // Lead.DandbCompanyId
    LEAD_DANDBCOMPANYID("Lead.DandbCompanyId"),
    // Lead.Description
    LEAD_DESCRIPTION("Lead.Description"),
    // Lead.Email
    LEAD_EMAIL("Lead.Email"),
    // Lead.EmailBouncedDate
    LEAD_EMAILBOUNCEDDATE("Lead.EmailBouncedDate"),
    // Lead.EmailBouncedReason
    LEAD_EMAILBOUNCEDREASON("Lead.EmailBouncedReason"),
    // Lead.Fax
    LEAD_FAX("Lead.Fax"),
    // Lead.FirstName
    LEAD_FIRSTNAME("Lead.FirstName"),
    // Lead.Id
    LEAD_ID("Lead.Id"),
    // Lead.Industry
    LEAD_INDUSTRY("Lead.Industry"),
    // Lead.IsConverted
    LEAD_ISCONVERTED("Lead.IsConverted"),
    // Lead.IsDeleted
    LEAD_ISDELETED("Lead.IsDeleted"),
    // Lead.IsUnreadByOwner
    LEAD_ISUNREADBYOWNER("Lead.IsUnreadByOwner"),
    // Lead.Jigsaw
    LEAD_JIGSAW("Lead.Jigsaw"),
    // Lead.JigsawContactId
    LEAD_JIGSAWCONTACTID("Lead.JigsawContactId"),
    // Lead.LastActivityDate
    LEAD_LASTACTIVITYDATE("Lead.LastActivityDate"),
    // Lead.LastModifiedById
    LEAD_LASTMODIFIEDBYID("Lead.LastModifiedById"),
    // Lead.LastModifiedDate
    LEAD_LASTMODIFIEDDATE("Lead.LastModifiedDate"),
    // Lead.LastName
    LEAD_LASTNAME("Lead.LastName"),
    // Lead.LastReferencedDate
    LEAD_LASTREFERENCEDDATE("Lead.LastReferencedDate"),
    // Lead.LastViewedDate
    LEAD_LASTVIEWEDDATE("Lead.LastViewedDate"),
    // Lead.Latitude
    LEAD_LATITUDE("Lead.Latitude"),
    // Lead.LeadSource
    LEAD_LEADSOURCE("Lead.LeadSource"),
    // Lead.Longitude
    LEAD_LONGITUDE("Lead.Longitude"),
    // Lead.MasterRecordId
    LEAD_MASTERRECORDID("Lead.MasterRecordId"),
    // Lead.MobilePhone
    LEAD_MOBILEPHONE("Lead.MobilePhone"),
    // Lead.Name
    LEAD_NAME("Lead.Name"),
    // Lead.NumberOfEmployees
    LEAD_NUMBEROFEMPLOYEES("Lead.NumberOfEmployees"),
    // Lead.OwnerId
    LEAD_OWNERID("Lead.OwnerId"),
    // Lead.Phone
    LEAD_PHONE("Lead.Phone"),
    // Lead.PhotoUrl
    LEAD_PHOTOURL("Lead.PhotoUrl"),
    // Lead.PostalCode
    LEAD_POSTALCODE("Lead.PostalCode"),
    // Lead.Rating
    LEAD_RATING("Lead.Rating"),
    // Lead.Salutation
    LEAD_SALUTATION("Lead.Salutation"),
    // Lead.State
    LEAD_STATE("Lead.State"),
    // Lead.Status
    LEAD_STATUS("Lead.Status"),
    // Lead.Street
    LEAD_STREET("Lead.Street"),
    // Lead.SystemModstamp
    LEAD_SYSTEMMODSTAMP("Lead.SystemModstamp"),
    // Lead.Title
    LEAD_TITLE("Lead.Title"),
    // Lead.Website
    LEAD_WEBSITE("Lead.Website"),
    // Macro.CreatedById
    MACRO_CREATEDBYID("Macro.CreatedById"),
    // Macro.CreatedDate
    MACRO_CREATEDDATE("Macro.CreatedDate"),
    // Macro.Description
    MACRO_DESCRIPTION("Macro.Description"),
    // Macro.Id
    MACRO_ID("Macro.Id"),
    // Macro.IsDeleted
    MACRO_ISDELETED("Macro.IsDeleted"),
    // Macro.LastModifiedById
    MACRO_LASTMODIFIEDBYID("Macro.LastModifiedById"),
    // Macro.LastModifiedDate
    MACRO_LASTMODIFIEDDATE("Macro.LastModifiedDate"),
    // Macro.LastReferencedDate
    MACRO_LASTREFERENCEDDATE("Macro.LastReferencedDate"),
    // Macro.LastViewedDate
    MACRO_LASTVIEWEDDATE("Macro.LastViewedDate"),
    // Macro.Name
    MACRO_NAME("Macro.Name"),
    // Macro.OwnerId
    MACRO_OWNERID("Macro.OwnerId"),
    // Macro.SystemModstamp
    MACRO_SYSTEMMODSTAMP("Macro.SystemModstamp"),
    // Metric.CompletionDate
    METRIC_COMPLETIONDATE("Metric.CompletionDate"),
    // Metric.CreatedById
    METRIC_CREATEDBYID("Metric.CreatedById"),
    // Metric.CreatedDate
    METRIC_CREATEDDATE("Metric.CreatedDate"),
    // Metric.CurrentValue
    METRIC_CURRENTVALUE("Metric.CurrentValue"),
    // Metric.Description
    METRIC_DESCRIPTION("Metric.Description"),
    // Metric.DueDate
    METRIC_DUEDATE("Metric.DueDate"),
    // Metric.GoalId
    METRIC_GOALID("Metric.GoalId"),
    // Metric.Id
    METRIC_ID("Metric.Id"),
    // Metric.InitialValue
    METRIC_INITIALVALUE("Metric.InitialValue"),
    // Metric.IsCompletionMetric
    METRIC_ISCOMPLETIONMETRIC("Metric.IsCompletionMetric"),
    // Metric.IsDeleted
    METRIC_ISDELETED("Metric.IsDeleted"),
    // Metric.LastComment
    METRIC_LASTCOMMENT("Metric.LastComment"),
    // Metric.LastModifiedById
    METRIC_LASTMODIFIEDBYID("Metric.LastModifiedById"),
    // Metric.LastModifiedDate
    METRIC_LASTMODIFIEDDATE("Metric.LastModifiedDate"),
    // Metric.LastReferencedDate
    METRIC_LASTREFERENCEDDATE("Metric.LastReferencedDate"),
    // Metric.LastViewedDate
    METRIC_LASTVIEWEDDATE("Metric.LastViewedDate"),
    // Metric.Name
    METRIC_NAME("Metric.Name"),
    // Metric.OwnerId
    METRIC_OWNERID("Metric.OwnerId"),
    // Metric.Progress
    METRIC_PROGRESS("Metric.Progress"),
    // Metric.RecordTypeId
    METRIC_RECORDTYPEID("Metric.RecordTypeId"),
    // Metric.StartDate
    METRIC_STARTDATE("Metric.StartDate"),
    // Metric.Status
    METRIC_STATUS("Metric.Status"),
    // Metric.SystemModstamp
    METRIC_SYSTEMMODSTAMP("Metric.SystemModstamp"),
    // Metric.TargetValue
    METRIC_TARGETVALUE("Metric.TargetValue"),
    // Metric.Weight
    METRIC_WEIGHT("Metric.Weight"),
    // Opportunity.AccountId
    OPPORTUNITY_ACCOUNTID("Opportunity.AccountId"),
    // Opportunity.Amount
    OPPORTUNITY_AMOUNT("Opportunity.Amount"),
    // Opportunity.CampaignId
    OPPORTUNITY_CAMPAIGNID("Opportunity.CampaignId"),
    // Opportunity.CloseDate
    OPPORTUNITY_CLOSEDATE("Opportunity.CloseDate"),
    // Opportunity.CreatedById
    OPPORTUNITY_CREATEDBYID("Opportunity.CreatedById"),
    // Opportunity.CreatedDate
    OPPORTUNITY_CREATEDDATE("Opportunity.CreatedDate"),
    // Opportunity.Description
    OPPORTUNITY_DESCRIPTION("Opportunity.Description"),
    // Opportunity.ExpectedRevenue
    OPPORTUNITY_EXPECTEDREVENUE("Opportunity.ExpectedRevenue"),
    // Opportunity.Fiscal
    OPPORTUNITY_FISCAL("Opportunity.Fiscal"),
    // Opportunity.FiscalQuarter
    OPPORTUNITY_FISCALQUARTER("Opportunity.FiscalQuarter"),
    // Opportunity.FiscalYear
    OPPORTUNITY_FISCALYEAR("Opportunity.FiscalYear"),
    // Opportunity.ForecastCategory
    OPPORTUNITY_FORECASTCATEGORY("Opportunity.ForecastCategory"),
    // Opportunity.ForecastCategoryName
    OPPORTUNITY_FORECASTCATEGORYNAME("Opportunity.ForecastCategoryName"),
    // Opportunity.HasOpportunityLineItem
    OPPORTUNITY_HASOPPORTUNITYLINEITEM("Opportunity.HasOpportunityLineItem"),
    // Opportunity.Id
    OPPORTUNITY_ID("Opportunity.Id"),
    // Opportunity.IsClosed
    OPPORTUNITY_ISCLOSED("Opportunity.IsClosed"),
    // Opportunity.IsDeleted
    OPPORTUNITY_ISDELETED("Opportunity.IsDeleted"),
    // Opportunity.IsPrivate
    OPPORTUNITY_ISPRIVATE("Opportunity.IsPrivate"),
    // Opportunity.IsWon
    OPPORTUNITY_ISWON("Opportunity.IsWon"),
    // Opportunity.LastActivityDate
    OPPORTUNITY_LASTACTIVITYDATE("Opportunity.LastActivityDate"),
    // Opportunity.LastModifiedById
    OPPORTUNITY_LASTMODIFIEDBYID("Opportunity.LastModifiedById"),
    // Opportunity.LastModifiedDate
    OPPORTUNITY_LASTMODIFIEDDATE("Opportunity.LastModifiedDate"),
    // Opportunity.LastReferencedDate
    OPPORTUNITY_LASTREFERENCEDDATE("Opportunity.LastReferencedDate"),
    // Opportunity.LastViewedDate
    OPPORTUNITY_LASTVIEWEDDATE("Opportunity.LastViewedDate"),
    // Opportunity.LeadSource
    OPPORTUNITY_LEADSOURCE("Opportunity.LeadSource"),
    // Opportunity.Name
    OPPORTUNITY_NAME("Opportunity.Name"),
    // Opportunity.NextStep
    OPPORTUNITY_NEXTSTEP("Opportunity.NextStep"),
    // Opportunity.OwnerId
    OPPORTUNITY_OWNERID("Opportunity.OwnerId"),
    // Opportunity.Pricebook2Id
    OPPORTUNITY_PRICEBOOK2ID("Opportunity.Pricebook2Id"),
    // Opportunity.Probability
    OPPORTUNITY_PROBABILITY("Opportunity.Probability"),
    // Opportunity.StageName
    OPPORTUNITY_STAGENAME("Opportunity.StageName"),
    // Opportunity.SystemModstamp
    OPPORTUNITY_SYSTEMMODSTAMP("Opportunity.SystemModstamp"),
    // Opportunity.TotalOpportunityQuantity
    OPPORTUNITY_TOTALOPPORTUNITYQUANTITY("Opportunity.TotalOpportunityQuantity"),
    // Opportunity.Type
    OPPORTUNITY_TYPE("Opportunity.Type"),
    // Order.AccountId
    ORDER_ACCOUNTID("Order.AccountId"),
    // Order.ActivatedById
    ORDER_ACTIVATEDBYID("Order.ActivatedById"),
    // Order.ActivatedDate
    ORDER_ACTIVATEDDATE("Order.ActivatedDate"),
    // Order.BillToContactId
    ORDER_BILLTOCONTACTID("Order.BillToContactId"),
    // Order.BillingAddress
    ORDER_BILLINGADDRESS("Order.BillingAddress"),
    // Order.BillingCity
    ORDER_BILLINGCITY("Order.BillingCity"),
    // Order.BillingCountry
    ORDER_BILLINGCOUNTRY("Order.BillingCountry"),
    // Order.BillingLatitude
    ORDER_BILLINGLATITUDE("Order.BillingLatitude"),
    // Order.BillingLongitude
    ORDER_BILLINGLONGITUDE("Order.BillingLongitude"),
    // Order.BillingPostalCode
    ORDER_BILLINGPOSTALCODE("Order.BillingPostalCode"),
    // Order.BillingState
    ORDER_BILLINGSTATE("Order.BillingState"),
    // Order.BillingStreet
    ORDER_BILLINGSTREET("Order.BillingStreet"),
    // Order.CompanyAuthorizedById
    ORDER_COMPANYAUTHORIZEDBYID("Order.CompanyAuthorizedById"),
    // Order.CompanyAuthorizedDate
    ORDER_COMPANYAUTHORIZEDDATE("Order.CompanyAuthorizedDate"),
    // Order.ContractId
    ORDER_CONTRACTID("Order.ContractId"),
    // Order.CreatedById
    ORDER_CREATEDBYID("Order.CreatedById"),
    // Order.CreatedDate
    ORDER_CREATEDDATE("Order.CreatedDate"),
    // Order.CustomerAuthorizedById
    ORDER_CUSTOMERAUTHORIZEDBYID("Order.CustomerAuthorizedById"),
    // Order.CustomerAuthorizedDate
    ORDER_CUSTOMERAUTHORIZEDDATE("Order.CustomerAuthorizedDate"),
    // Order.Description
    ORDER_DESCRIPTION("Order.Description"),
    // Order.EffectiveDate
    ORDER_EFFECTIVEDATE("Order.EffectiveDate"),
    // Order.EndDate
    ORDER_ENDDATE("Order.EndDate"),
    // Order.Id
    ORDER_ID("Order.Id"),
    // Order.IsDeleted
    ORDER_ISDELETED("Order.IsDeleted"),
    // Order.IsReductionOrder
    ORDER_ISREDUCTIONORDER("Order.IsReductionOrder"),
    // Order.LastModifiedById
    ORDER_LASTMODIFIEDBYID("Order.LastModifiedById"),
    // Order.LastModifiedDate
    ORDER_LASTMODIFIEDDATE("Order.LastModifiedDate"),
    // Order.LastReferencedDate
    ORDER_LASTREFERENCEDDATE("Order.LastReferencedDate"),
    // Order.LastViewedDate
    ORDER_LASTVIEWEDDATE("Order.LastViewedDate"),
    // Order.Name
    ORDER_NAME("Order.Name"),
    // Order.OrderNumber
    ORDER_ORDERNUMBER("Order.OrderNumber"),
    // Order.OrderReferenceNumber
    ORDER_ORDERREFERENCENUMBER("Order.OrderReferenceNumber"),
    // Order.OriginalOrderId
    ORDER_ORIGINALORDERID("Order.OriginalOrderId"),
    // Order.OwnerId
    ORDER_OWNERID("Order.OwnerId"),
    // Order.PoDate
    ORDER_PODATE("Order.PoDate"),
    // Order.PoNumber
    ORDER_PONUMBER("Order.PoNumber"),
    // Order.Pricebook2Id
    ORDER_PRICEBOOK2ID("Order.Pricebook2Id"),
    // Order.ShipToContactId
    ORDER_SHIPTOCONTACTID("Order.ShipToContactId"),
    // Order.ShippingAddress
    ORDER_SHIPPINGADDRESS("Order.ShippingAddress"),
    // Order.ShippingCity
    ORDER_SHIPPINGCITY("Order.ShippingCity"),
    // Order.ShippingCountry
    ORDER_SHIPPINGCOUNTRY("Order.ShippingCountry"),
    // Order.ShippingLatitude
    ORDER_SHIPPINGLATITUDE("Order.ShippingLatitude"),
    // Order.ShippingLongitude
    ORDER_SHIPPINGLONGITUDE("Order.ShippingLongitude"),
    // Order.ShippingPostalCode
    ORDER_SHIPPINGPOSTALCODE("Order.ShippingPostalCode"),
    // Order.ShippingState
    ORDER_SHIPPINGSTATE("Order.ShippingState"),
    // Order.ShippingStreet
    ORDER_SHIPPINGSTREET("Order.ShippingStreet"),
    // Order.Status
    ORDER_STATUS("Order.Status"),
    // Order.StatusCode
    ORDER_STATUSCODE("Order.StatusCode"),
    // Order.SystemModstamp
    ORDER_SYSTEMMODSTAMP("Order.SystemModstamp"),
    // Order.TotalAmount
    ORDER_TOTALAMOUNT("Order.TotalAmount"),
    // Order.Type
    ORDER_TYPE("Order.Type"),
    // Pricebook2.CreatedById
    PRICEBOOK2_CREATEDBYID("Pricebook2.CreatedById"),
    // Pricebook2.CreatedDate
    PRICEBOOK2_CREATEDDATE("Pricebook2.CreatedDate"),
    // Pricebook2.Description
    PRICEBOOK2_DESCRIPTION("Pricebook2.Description"),
    // Pricebook2.Id
    PRICEBOOK2_ID("Pricebook2.Id"),
    // Pricebook2.IsActive
    PRICEBOOK2_ISACTIVE("Pricebook2.IsActive"),
    // Pricebook2.IsDeleted
    PRICEBOOK2_ISDELETED("Pricebook2.IsDeleted"),
    // Pricebook2.IsStandard
    PRICEBOOK2_ISSTANDARD("Pricebook2.IsStandard"),
    // Pricebook2.LastModifiedById
    PRICEBOOK2_LASTMODIFIEDBYID("Pricebook2.LastModifiedById"),
    // Pricebook2.LastModifiedDate
    PRICEBOOK2_LASTMODIFIEDDATE("Pricebook2.LastModifiedDate"),
    // Pricebook2.LastReferencedDate
    PRICEBOOK2_LASTREFERENCEDDATE("Pricebook2.LastReferencedDate"),
    // Pricebook2.LastViewedDate
    PRICEBOOK2_LASTVIEWEDDATE("Pricebook2.LastViewedDate"),
    // Pricebook2.Name
    PRICEBOOK2_NAME("Pricebook2.Name"),
    // Pricebook2.SystemModstamp
    PRICEBOOK2_SYSTEMMODSTAMP("Pricebook2.SystemModstamp"),
    // PricebookEntry.CreatedById
    PRICEBOOKENTRY_CREATEDBYID("PricebookEntry.CreatedById"),
    // PricebookEntry.CreatedDate
    PRICEBOOKENTRY_CREATEDDATE("PricebookEntry.CreatedDate"),
    // PricebookEntry.Id
    PRICEBOOKENTRY_ID("PricebookEntry.Id"),
    // PricebookEntry.IsActive
    PRICEBOOKENTRY_ISACTIVE("PricebookEntry.IsActive"),
    // PricebookEntry.IsDeleted
    PRICEBOOKENTRY_ISDELETED("PricebookEntry.IsDeleted"),
    // PricebookEntry.LastModifiedById
    PRICEBOOKENTRY_LASTMODIFIEDBYID("PricebookEntry.LastModifiedById"),
    // PricebookEntry.LastModifiedDate
    PRICEBOOKENTRY_LASTMODIFIEDDATE("PricebookEntry.LastModifiedDate"),
    // PricebookEntry.Name
    PRICEBOOKENTRY_NAME("PricebookEntry.Name"),
    // PricebookEntry.Pricebook2Id
    PRICEBOOKENTRY_PRICEBOOK2ID("PricebookEntry.Pricebook2Id"),
    // PricebookEntry.Product2Id
    PRICEBOOKENTRY_PRODUCT2ID("PricebookEntry.Product2Id"),
    // PricebookEntry.ProductCode
    PRICEBOOKENTRY_PRODUCTCODE("PricebookEntry.ProductCode"),
    // PricebookEntry.SystemModstamp
    PRICEBOOKENTRY_SYSTEMMODSTAMP("PricebookEntry.SystemModstamp"),
    // PricebookEntry.UnitPrice
    PRICEBOOKENTRY_UNITPRICE("PricebookEntry.UnitPrice"),
    // PricebookEntry.UseStandardPrice
    PRICEBOOKENTRY_USESTANDARDPRICE("PricebookEntry.UseStandardPrice"),
    // Product2.CreatedById
    PRODUCT2_CREATEDBYID("Product2.CreatedById"),
    // Product2.CreatedDate
    PRODUCT2_CREATEDDATE("Product2.CreatedDate"),
    // Product2.Description
    PRODUCT2_DESCRIPTION("Product2.Description"),
    // Product2.Family
    PRODUCT2_FAMILY("Product2.Family"),
    // Product2.Id
    PRODUCT2_ID("Product2.Id"),
    // Product2.IsActive
    PRODUCT2_ISACTIVE("Product2.IsActive"),
    // Product2.IsDeleted
    PRODUCT2_ISDELETED("Product2.IsDeleted"),
    // Product2.LastModifiedById
    PRODUCT2_LASTMODIFIEDBYID("Product2.LastModifiedById"),
    // Product2.LastModifiedDate
    PRODUCT2_LASTMODIFIEDDATE("Product2.LastModifiedDate"),
    // Product2.LastReferencedDate
    PRODUCT2_LASTREFERENCEDDATE("Product2.LastReferencedDate"),
    // Product2.LastViewedDate
    PRODUCT2_LASTVIEWEDDATE("Product2.LastViewedDate"),
    // Product2.Name
    PRODUCT2_NAME("Product2.Name"),
    // Product2.ProductCode
    PRODUCT2_PRODUCTCODE("Product2.ProductCode"),
    // Product2.SystemModstamp
    PRODUCT2_SYSTEMMODSTAMP("Product2.SystemModstamp"),
    // Solution.CreatedById
    SOLUTION_CREATEDBYID("Solution.CreatedById"),
    // Solution.CreatedDate
    SOLUTION_CREATEDDATE("Solution.CreatedDate"),
    // Solution.Id
    SOLUTION_ID("Solution.Id"),
    // Solution.IsDeleted
    SOLUTION_ISDELETED("Solution.IsDeleted"),
    // Solution.IsHtml
    SOLUTION_ISHTML("Solution.IsHtml"),
    // Solution.IsPublished
    SOLUTION_ISPUBLISHED("Solution.IsPublished"),
    // Solution.IsPublishedInPublicKb
    SOLUTION_ISPUBLISHEDINPUBLICKB("Solution.IsPublishedInPublicKb"),
    // Solution.IsReviewed
    SOLUTION_ISREVIEWED("Solution.IsReviewed"),
    // Solution.LastModifiedById
    SOLUTION_LASTMODIFIEDBYID("Solution.LastModifiedById"),
    // Solution.LastModifiedDate
    SOLUTION_LASTMODIFIEDDATE("Solution.LastModifiedDate"),
    // Solution.LastReferencedDate
    SOLUTION_LASTREFERENCEDDATE("Solution.LastReferencedDate"),
    // Solution.LastViewedDate
    SOLUTION_LASTVIEWEDDATE("Solution.LastViewedDate"),
    // Solution.OwnerId
    SOLUTION_OWNERID("Solution.OwnerId"),
    // Solution.SolutionName
    SOLUTION_SOLUTIONNAME("Solution.SolutionName"),
    // Solution.SolutionNote
    SOLUTION_SOLUTIONNOTE("Solution.SolutionNote"),
    // Solution.SolutionNumber
    SOLUTION_SOLUTIONNUMBER("Solution.SolutionNumber"),
    // Solution.Status
    SOLUTION_STATUS("Solution.Status"),
    // Solution.SystemModstamp
    SOLUTION_SYSTEMMODSTAMP("Solution.SystemModstamp"),
    // Solution.TimesUsed
    SOLUTION_TIMESUSED("Solution.TimesUsed"),
    // User.AboutMe
    USER_ABOUTME("User.AboutMe"),
    // User.AccountId
    USER_ACCOUNTID("User.AccountId"),
    // User.Address
    USER_ADDRESS("User.Address"),
    // User.Alias
    USER_ALIAS("User.Alias"),
    // User.BadgeText
    USER_BADGETEXT("User.BadgeText"),
    // User.CallCenterId
    USER_CALLCENTERID("User.CallCenterId"),
    // User.City
    USER_CITY("User.City"),
    // User.CommunityNickname
    USER_COMMUNITYNICKNAME("User.CommunityNickname"),
    // User.CompanyName
    USER_COMPANYNAME("User.CompanyName"),
    // User.ContactId
    USER_CONTACTID("User.ContactId"),
    // User.Country
    USER_COUNTRY("User.Country"),
    // User.CreatedById
    USER_CREATEDBYID("User.CreatedById"),
    // User.CreatedDate
    USER_CREATEDDATE("User.CreatedDate"),
    // User.DefaultGroupNotificationFrequency
    USER_DEFAULTGROUPNOTIFICATIONFREQUENCY("User.DefaultGroupNotificationFrequency"),
    // User.DelegatedApproverId
    USER_DELEGATEDAPPROVERID("User.DelegatedApproverId"),
    // User.Department
    USER_DEPARTMENT("User.Department"),
    // User.DigestFrequency
    USER_DIGESTFREQUENCY("User.DigestFrequency"),
    // User.Division
    USER_DIVISION("User.Division"),
    // User.Email
    USER_EMAIL("User.Email"),
    // User.EmailEncodingKey
    USER_EMAILENCODINGKEY("User.EmailEncodingKey"),
    // User.EmailPreferencesAutoBcc
    USER_EMAILPREFERENCESAUTOBCC("User.EmailPreferencesAutoBcc"),
    // User.EmailPreferencesAutoBccStayInTouch
    USER_EMAILPREFERENCESAUTOBCCSTAYINTOUCH("User.EmailPreferencesAutoBccStayInTouch"),
    // User.EmailPreferencesStayInTouchReminder
    USER_EMAILPREFERENCESSTAYINTOUCHREMINDER("User.EmailPreferencesStayInTouchReminder"),
    // User.EmployeeNumber
    USER_EMPLOYEENUMBER("User.EmployeeNumber"),
    // User.Extension
    USER_EXTENSION("User.Extension"),
    // User.Fax
    USER_FAX("User.Fax"),
    // User.FederationIdentifier
    USER_FEDERATIONIDENTIFIER("User.FederationIdentifier"),
    // User.FirstName
    USER_FIRSTNAME("User.FirstName"),
    // User.ForecastEnabled
    USER_FORECASTENABLED("User.ForecastEnabled"),
    // User.FullPhotoUrl
    USER_FULLPHOTOURL("User.FullPhotoUrl"),
    // User.Id
    USER_ID("User.Id"),
    // User.IsActive
    USER_ISACTIVE("User.IsActive"),
    // User.JigsawImportLimitOverride
    USER_JIGSAWIMPORTLIMITOVERRIDE("User.JigsawImportLimitOverride"),
    // User.LanguageLocaleKey
    USER_LANGUAGELOCALEKEY("User.LanguageLocaleKey"),
    // User.LastLoginDate
    USER_LASTLOGINDATE("User.LastLoginDate"),
    // User.LastModifiedById
    USER_LASTMODIFIEDBYID("User.LastModifiedById"),
    // User.LastModifiedDate
    USER_LASTMODIFIEDDATE("User.LastModifiedDate"),
    // User.LastName
    USER_LASTNAME("User.LastName"),
    // User.LastPasswordChangeDate
    USER_LASTPASSWORDCHANGEDATE("User.LastPasswordChangeDate"),
    // User.LastReferencedDate
    USER_LASTREFERENCEDDATE("User.LastReferencedDate"),
    // User.LastViewedDate
    USER_LASTVIEWEDDATE("User.LastViewedDate"),
    // User.Latitude
    USER_LATITUDE("User.Latitude"),
    // User.LocaleSidKey
    USER_LOCALESIDKEY("User.LocaleSidKey"),
    // User.Longitude
    USER_LONGITUDE("User.Longitude"),
    // User.ManagerId
    USER_MANAGERID("User.ManagerId"),
    // User.MobilePhone
    USER_MOBILEPHONE("User.MobilePhone"),
    // User.Name
    USER_NAME("User.Name"),
    // User.OfflinePdaTrialExpirationDate
    USER_OFFLINEPDATRIALEXPIRATIONDATE("User.OfflinePdaTrialExpirationDate"),
    // User.OfflineTrialExpirationDate
    USER_OFFLINETRIALEXPIRATIONDATE("User.OfflineTrialExpirationDate"),
    // User.Phone
    USER_PHONE("User.Phone"),
    // User.PostalCode
    USER_POSTALCODE("User.PostalCode"),
    // User.ProfileId
    USER_PROFILEID("User.ProfileId"),
    // User.ReceivesAdminInfoEmails
    USER_RECEIVESADMININFOEMAILS("User.ReceivesAdminInfoEmails"),
    // User.ReceivesInfoEmails
    USER_RECEIVESINFOEMAILS("User.ReceivesInfoEmails"),
    // User.SenderEmail
    USER_SENDEREMAIL("User.SenderEmail"),
    // User.SenderName
    USER_SENDERNAME("User.SenderName"),
    // User.Signature
    USER_SIGNATURE("User.Signature"),
    // User.SmallPhotoUrl
    USER_SMALLPHOTOURL("User.SmallPhotoUrl"),
    // User.State
    USER_STATE("User.State"),
    // User.StayInTouchNote
    USER_STAYINTOUCHNOTE("User.StayInTouchNote"),
    // User.StayInTouchSignature
    USER_STAYINTOUCHSIGNATURE("User.StayInTouchSignature"),
    // User.StayInTouchSubject
    USER_STAYINTOUCHSUBJECT("User.StayInTouchSubject"),
    // User.Street
    USER_STREET("User.Street"),
    // User.SystemModstamp
    USER_SYSTEMMODSTAMP("User.SystemModstamp"),
    // User.TimeZoneSidKey
    USER_TIMEZONESIDKEY("User.TimeZoneSidKey"),
    // User.Title
    USER_TITLE("User.Title"),
    // User.UserPermissionsCallCenterAutoLogin
    USER_USERPERMISSIONSCALLCENTERAUTOLOGIN("User.UserPermissionsCallCenterAutoLogin"),
    // User.UserPermissionsChatterAnswersUser
    USER_USERPERMISSIONSCHATTERANSWERSUSER("User.UserPermissionsChatterAnswersUser"),
    // User.UserPermissionsInteractionUser
    USER_USERPERMISSIONSINTERACTIONUSER("User.UserPermissionsInteractionUser"),
    // User.UserPermissionsJigsawProspectingUser
    USER_USERPERMISSIONSJIGSAWPROSPECTINGUSER("User.UserPermissionsJigsawProspectingUser"),
    // User.UserPermissionsKnowledgeUser
    USER_USERPERMISSIONSKNOWLEDGEUSER("User.UserPermissionsKnowledgeUser"),
    // User.UserPermissionsMarketingUser
    USER_USERPERMISSIONSMARKETINGUSER("User.UserPermissionsMarketingUser"),
    // User.UserPermissionsMobileUser
    USER_USERPERMISSIONSMOBILEUSER("User.UserPermissionsMobileUser"),
    // User.UserPermissionsOfflineUser
    USER_USERPERMISSIONSOFFLINEUSER("User.UserPermissionsOfflineUser"),
    // User.UserPermissionsSFContentUser
    USER_USERPERMISSIONSSFCONTENTUSER("User.UserPermissionsSFContentUser"),
    // User.UserPermissionsSiteforceContributorUser
    USER_USERPERMISSIONSSITEFORCECONTRIBUTORUSER("User.UserPermissionsSiteforceContributorUser"),
    // User.UserPermissionsSiteforcePublisherUser
    USER_USERPERMISSIONSSITEFORCEPUBLISHERUSER("User.UserPermissionsSiteforcePublisherUser"),
    // User.UserPermissionsSupportUser
    USER_USERPERMISSIONSSUPPORTUSER("User.UserPermissionsSupportUser"),
    // User.UserPermissionsWorkDotComUserFeature
    USER_USERPERMISSIONSWORKDOTCOMUSERFEATURE("User.UserPermissionsWorkDotComUserFeature"),
    // User.UserPreferencesActivityRemindersPopup
    USER_USERPREFERENCESACTIVITYREMINDERSPOPUP("User.UserPreferencesActivityRemindersPopup"),
    // User.UserPreferencesApexPagesDeveloperMode
    USER_USERPREFERENCESAPEXPAGESDEVELOPERMODE("User.UserPreferencesApexPagesDeveloperMode"),
    // User.UserPreferencesContentEmailAsAndWhen
    USER_USERPREFERENCESCONTENTEMAILASANDWHEN("User.UserPreferencesContentEmailAsAndWhen"),
    // User.UserPreferencesContentNoEmail
    USER_USERPREFERENCESCONTENTNOEMAIL("User.UserPreferencesContentNoEmail"),
    // User.UserPreferencesDisCommentAfterLikeEmail
    USER_USERPREFERENCESDISCOMMENTAFTERLIKEEMAIL("User.UserPreferencesDisCommentAfterLikeEmail"),
    // User.UserPreferencesDisMentionsCommentEmail
    USER_USERPREFERENCESDISMENTIONSCOMMENTEMAIL("User.UserPreferencesDisMentionsCommentEmail"),
    // User.UserPreferencesDisProfPostCommentEmail
    USER_USERPREFERENCESDISPROFPOSTCOMMENTEMAIL("User.UserPreferencesDisProfPostCommentEmail"),
    // User.UserPreferencesDisableAllFeedsEmail
    USER_USERPREFERENCESDISABLEALLFEEDSEMAIL("User.UserPreferencesDisableAllFeedsEmail"),
    // User.UserPreferencesDisableBookmarkEmail
    USER_USERPREFERENCESDISABLEBOOKMARKEMAIL("User.UserPreferencesDisableBookmarkEmail"),
    // User.UserPreferencesDisableChangeCommentEmail
    USER_USERPREFERENCESDISABLECHANGECOMMENTEMAIL("User.UserPreferencesDisableChangeCommentEmail"),
    // User.UserPreferencesDisableEndorsementEmail
    USER_USERPREFERENCESDISABLEENDORSEMENTEMAIL("User.UserPreferencesDisableEndorsementEmail"),
    // User.UserPreferencesDisableFeedbackEmail
    USER_USERPREFERENCESDISABLEFEEDBACKEMAIL("User.UserPreferencesDisableFeedbackEmail"),
    // User.UserPreferencesDisableFileShareNotificationsForApi
    USER_USERPREFERENCESDISABLEFILESHARENOTIFICATIONSFORAPI("User.UserPreferencesDisableFileShareNotificationsForApi"),
    // User.UserPreferencesDisableFollowersEmail
    USER_USERPREFERENCESDISABLEFOLLOWERSEMAIL("User.UserPreferencesDisableFollowersEmail"),
    // User.UserPreferencesDisableLaterCommentEmail
    USER_USERPREFERENCESDISABLELATERCOMMENTEMAIL("User.UserPreferencesDisableLaterCommentEmail"),
    // User.UserPreferencesDisableLikeEmail
    USER_USERPREFERENCESDISABLELIKEEMAIL("User.UserPreferencesDisableLikeEmail"),
    // User.UserPreferencesDisableMentionsPostEmail
    USER_USERPREFERENCESDISABLEMENTIONSPOSTEMAIL("User.UserPreferencesDisableMentionsPostEmail"),
    // User.UserPreferencesDisableMessageEmail
    USER_USERPREFERENCESDISABLEMESSAGEEMAIL("User.UserPreferencesDisableMessageEmail"),
    // User.UserPreferencesDisableProfilePostEmail
    USER_USERPREFERENCESDISABLEPROFILEPOSTEMAIL("User.UserPreferencesDisableProfilePostEmail"),
    // User.UserPreferencesDisableSharePostEmail
    USER_USERPREFERENCESDISABLESHAREPOSTEMAIL("User.UserPreferencesDisableSharePostEmail"),
    // User.UserPreferencesDisableWorkEmail
    USER_USERPREFERENCESDISABLEWORKEMAIL("User.UserPreferencesDisableWorkEmail"),
    // User.UserPreferencesEnableAutoSubForFeeds
    USER_USERPREFERENCESENABLEAUTOSUBFORFEEDS("User.UserPreferencesEnableAutoSubForFeeds"),
    // User.UserPreferencesEventRemindersCheckboxDefault
    USER_USERPREFERENCESEVENTREMINDERSCHECKBOXDEFAULT("User.UserPreferencesEventRemindersCheckboxDefault"),
    // User.UserPreferencesHideCSNDesktopTask
    USER_USERPREFERENCESHIDECSNDESKTOPTASK("User.UserPreferencesHideCSNDesktopTask"),
    // User.UserPreferencesHideCSNGetChatterMobileTask
    USER_USERPREFERENCESHIDECSNGETCHATTERMOBILETASK("User.UserPreferencesHideCSNGetChatterMobileTask"),
    // User.UserPreferencesHideChatterOnboardingSplash
    USER_USERPREFERENCESHIDECHATTERONBOARDINGSPLASH("User.UserPreferencesHideChatterOnboardingSplash"),
    // User.UserPreferencesHideS1BrowserUI
    USER_USERPREFERENCESHIDES1BROWSERUI("User.UserPreferencesHideS1BrowserUI"),
    // User.UserPreferencesHideSecondChatterOnboardingSplash
    USER_USERPREFERENCESHIDESECONDCHATTERONBOARDINGSPLASH("User.UserPreferencesHideSecondChatterOnboardingSplash"),
    // User.UserPreferencesJigsawListUser
    USER_USERPREFERENCESJIGSAWLISTUSER("User.UserPreferencesJigsawListUser"),
    // User.UserPreferencesLightningExperiencePreferred
    USER_USERPREFERENCESLIGHTNINGEXPERIENCEPREFERRED("User.UserPreferencesLightningExperiencePreferred"),
    // User.UserPreferencesPathAssistantCollapsed
    USER_USERPREFERENCESPATHASSISTANTCOLLAPSED("User.UserPreferencesPathAssistantCollapsed"),
    // User.UserPreferencesReminderSoundOff
    USER_USERPREFERENCESREMINDERSOUNDOFF("User.UserPreferencesReminderSoundOff"),
    // User.UserPreferencesShowCityToExternalUsers
    USER_USERPREFERENCESSHOWCITYTOEXTERNALUSERS("User.UserPreferencesShowCityToExternalUsers"),
    // User.UserPreferencesShowCityToGuestUsers
    USER_USERPREFERENCESSHOWCITYTOGUESTUSERS("User.UserPreferencesShowCityToGuestUsers"),
    // User.UserPreferencesShowCountryToExternalUsers
    USER_USERPREFERENCESSHOWCOUNTRYTOEXTERNALUSERS("User.UserPreferencesShowCountryToExternalUsers"),
    // User.UserPreferencesShowCountryToGuestUsers
    USER_USERPREFERENCESSHOWCOUNTRYTOGUESTUSERS("User.UserPreferencesShowCountryToGuestUsers"),
    // User.UserPreferencesShowEmailToExternalUsers
    USER_USERPREFERENCESSHOWEMAILTOEXTERNALUSERS("User.UserPreferencesShowEmailToExternalUsers"),
    // User.UserPreferencesShowFaxToExternalUsers
    USER_USERPREFERENCESSHOWFAXTOEXTERNALUSERS("User.UserPreferencesShowFaxToExternalUsers"),
    // User.UserPreferencesShowManagerToExternalUsers
    USER_USERPREFERENCESSHOWMANAGERTOEXTERNALUSERS("User.UserPreferencesShowManagerToExternalUsers"),
    // User.UserPreferencesShowMobilePhoneToExternalUsers
    USER_USERPREFERENCESSHOWMOBILEPHONETOEXTERNALUSERS("User.UserPreferencesShowMobilePhoneToExternalUsers"),
    // User.UserPreferencesShowPostalCodeToExternalUsers
    USER_USERPREFERENCESSHOWPOSTALCODETOEXTERNALUSERS("User.UserPreferencesShowPostalCodeToExternalUsers"),
    // User.UserPreferencesShowPostalCodeToGuestUsers
    USER_USERPREFERENCESSHOWPOSTALCODETOGUESTUSERS("User.UserPreferencesShowPostalCodeToGuestUsers"),
    // User.UserPreferencesShowProfilePicToGuestUsers
    USER_USERPREFERENCESSHOWPROFILEPICTOGUESTUSERS("User.UserPreferencesShowProfilePicToGuestUsers"),
    // User.UserPreferencesShowStateToExternalUsers
    USER_USERPREFERENCESSHOWSTATETOEXTERNALUSERS("User.UserPreferencesShowStateToExternalUsers"),
    // User.UserPreferencesShowStateToGuestUsers
    USER_USERPREFERENCESSHOWSTATETOGUESTUSERS("User.UserPreferencesShowStateToGuestUsers"),
    // User.UserPreferencesShowStreetAddressToExternalUsers
    USER_USERPREFERENCESSHOWSTREETADDRESSTOEXTERNALUSERS("User.UserPreferencesShowStreetAddressToExternalUsers"),
    // User.UserPreferencesShowTitleToExternalUsers
    USER_USERPREFERENCESSHOWTITLETOEXTERNALUSERS("User.UserPreferencesShowTitleToExternalUsers"),
    // User.UserPreferencesShowTitleToGuestUsers
    USER_USERPREFERENCESSHOWTITLETOGUESTUSERS("User.UserPreferencesShowTitleToGuestUsers"),
    // User.UserPreferencesShowWorkPhoneToExternalUsers
    USER_USERPREFERENCESSHOWWORKPHONETOEXTERNALUSERS("User.UserPreferencesShowWorkPhoneToExternalUsers"),
    // User.UserPreferencesTaskRemindersCheckboxDefault
    USER_USERPREFERENCESTASKREMINDERSCHECKBOXDEFAULT("User.UserPreferencesTaskRemindersCheckboxDefault"),
    // User.UserRoleId
    USER_USERROLEID("User.UserRoleId"),
    // User.UserType
    USER_USERTYPE("User.UserType"),
    // User.Username
    USER_USERNAME("User.Username"),
    // UserProvisioningRequest.AppName
    USERPROVISIONINGREQUEST_APPNAME("UserProvisioningRequest.AppName"),
    // UserProvisioningRequest.ApprovalStatus
    USERPROVISIONINGREQUEST_APPROVALSTATUS("UserProvisioningRequest.ApprovalStatus"),
    // UserProvisioningRequest.ConnectedAppId
    USERPROVISIONINGREQUEST_CONNECTEDAPPID("UserProvisioningRequest.ConnectedAppId"),
    // UserProvisioningRequest.CreatedById
    USERPROVISIONINGREQUEST_CREATEDBYID("UserProvisioningRequest.CreatedById"),
    // UserProvisioningRequest.CreatedDate
    USERPROVISIONINGREQUEST_CREATEDDATE("UserProvisioningRequest.CreatedDate"),
    // UserProvisioningRequest.ExternalUserId
    USERPROVISIONINGREQUEST_EXTERNALUSERID("UserProvisioningRequest.ExternalUserId"),
    // UserProvisioningRequest.Id
    USERPROVISIONINGREQUEST_ID("UserProvisioningRequest.Id"),
    // UserProvisioningRequest.IsDeleted
    USERPROVISIONINGREQUEST_ISDELETED("UserProvisioningRequest.IsDeleted"),
    // UserProvisioningRequest.LastModifiedById
    USERPROVISIONINGREQUEST_LASTMODIFIEDBYID("UserProvisioningRequest.LastModifiedById"),
    // UserProvisioningRequest.LastModifiedDate
    USERPROVISIONINGREQUEST_LASTMODIFIEDDATE("UserProvisioningRequest.LastModifiedDate"),
    // UserProvisioningRequest.ManagerId
    USERPROVISIONINGREQUEST_MANAGERID("UserProvisioningRequest.ManagerId"),
    // UserProvisioningRequest.Name
    USERPROVISIONINGREQUEST_NAME("UserProvisioningRequest.Name"),
    // UserProvisioningRequest.Operation
    USERPROVISIONINGREQUEST_OPERATION("UserProvisioningRequest.Operation"),
    // UserProvisioningRequest.OwnerId
    USERPROVISIONINGREQUEST_OWNERID("UserProvisioningRequest.OwnerId"),
    // UserProvisioningRequest.SalesforceUserId
    USERPROVISIONINGREQUEST_SALESFORCEUSERID("UserProvisioningRequest.SalesforceUserId"),
    // UserProvisioningRequest.ScheduleDate
    USERPROVISIONINGREQUEST_SCHEDULEDATE("UserProvisioningRequest.ScheduleDate"),
    // UserProvisioningRequest.State
    USERPROVISIONINGREQUEST_STATE("UserProvisioningRequest.State"),
    // UserProvisioningRequest.SystemModstamp
    USERPROVISIONINGREQUEST_SYSTEMMODSTAMP("UserProvisioningRequest.SystemModstamp"),
    // UserProvisioningRequest.UserProvAccountId
    USERPROVISIONINGREQUEST_USERPROVACCOUNTID("UserProvisioningRequest.UserProvAccountId"),
    // UserProvisioningRequest.UserProvConfigId
    USERPROVISIONINGREQUEST_USERPROVCONFIGID("UserProvisioningRequest.UserProvConfigId"),
    // WorkCoaching.CoachId
    WORKCOACHING_COACHID("WorkCoaching.CoachId"),
    // WorkCoaching.CoachedId
    WORKCOACHING_COACHEDID("WorkCoaching.CoachedId"),
    // WorkCoaching.CreatedById
    WORKCOACHING_CREATEDBYID("WorkCoaching.CreatedById"),
    // WorkCoaching.CreatedDate
    WORKCOACHING_CREATEDDATE("WorkCoaching.CreatedDate"),
    // WorkCoaching.Id
    WORKCOACHING_ID("WorkCoaching.Id"),
    // WorkCoaching.IsDeleted
    WORKCOACHING_ISDELETED("WorkCoaching.IsDeleted"),
    // WorkCoaching.IsInactive
    WORKCOACHING_ISINACTIVE("WorkCoaching.IsInactive"),
    // WorkCoaching.LastModifiedById
    WORKCOACHING_LASTMODIFIEDBYID("WorkCoaching.LastModifiedById"),
    // WorkCoaching.LastModifiedDate
    WORKCOACHING_LASTMODIFIEDDATE("WorkCoaching.LastModifiedDate"),
    // WorkCoaching.LastReferencedDate
    WORKCOACHING_LASTREFERENCEDDATE("WorkCoaching.LastReferencedDate"),
    // WorkCoaching.LastViewedDate
    WORKCOACHING_LASTVIEWEDDATE("WorkCoaching.LastViewedDate"),
    // WorkCoaching.Name
    WORKCOACHING_NAME("WorkCoaching.Name"),
    // WorkCoaching.OwnerId
    WORKCOACHING_OWNERID("WorkCoaching.OwnerId"),
    // WorkCoaching.SystemModstamp
    WORKCOACHING_SYSTEMMODSTAMP("WorkCoaching.SystemModstamp"),
    // WorkFeedback.CreatedById
    WORKFEEDBACK_CREATEDBYID("WorkFeedback.CreatedById"),
    // WorkFeedback.CreatedDate
    WORKFEEDBACK_CREATEDDATE("WorkFeedback.CreatedDate"),
    // WorkFeedback.Feedback
    WORKFEEDBACK_FEEDBACK("WorkFeedback.Feedback"),
    // WorkFeedback.Id
    WORKFEEDBACK_ID("WorkFeedback.Id"),
    // WorkFeedback.IsDeleted
    WORKFEEDBACK_ISDELETED("WorkFeedback.IsDeleted"),
    // WorkFeedback.LastModifiedById
    WORKFEEDBACK_LASTMODIFIEDBYID("WorkFeedback.LastModifiedById"),
    // WorkFeedback.LastModifiedDate
    WORKFEEDBACK_LASTMODIFIEDDATE("WorkFeedback.LastModifiedDate"),
    // WorkFeedback.Name
    WORKFEEDBACK_NAME("WorkFeedback.Name"),
    // WorkFeedback.OwnerId
    WORKFEEDBACK_OWNERID("WorkFeedback.OwnerId"),
    // WorkFeedback.QuestionId
    WORKFEEDBACK_QUESTIONID("WorkFeedback.QuestionId"),
    // WorkFeedback.RequestId
    WORKFEEDBACK_REQUESTID("WorkFeedback.RequestId"),
    // WorkFeedback.SystemModstamp
    WORKFEEDBACK_SYSTEMMODSTAMP("WorkFeedback.SystemModstamp"),
    // WorkFeedbackQuestion.Choices
    WORKFEEDBACKQUESTION_CHOICES("WorkFeedbackQuestion.Choices"),
    // WorkFeedbackQuestion.CreatedById
    WORKFEEDBACKQUESTION_CREATEDBYID("WorkFeedbackQuestion.CreatedById"),
    // WorkFeedbackQuestion.CreatedDate
    WORKFEEDBACKQUESTION_CREATEDDATE("WorkFeedbackQuestion.CreatedDate"),
    // WorkFeedbackQuestion.Detail
    WORKFEEDBACKQUESTION_DETAIL("WorkFeedbackQuestion.Detail"),
    // WorkFeedbackQuestion.Id
    WORKFEEDBACKQUESTION_ID("WorkFeedbackQuestion.Id"),
    // WorkFeedbackQuestion.IsConfidentialAnswer
    WORKFEEDBACKQUESTION_ISCONFIDENTIALANSWER("WorkFeedbackQuestion.IsConfidentialAnswer"),
    // WorkFeedbackQuestion.IsDeleted
    WORKFEEDBACKQUESTION_ISDELETED("WorkFeedbackQuestion.IsDeleted"),
    // WorkFeedbackQuestion.IsOptional
    WORKFEEDBACKQUESTION_ISOPTIONAL("WorkFeedbackQuestion.IsOptional"),
    // WorkFeedbackQuestion.LastModifiedById
    WORKFEEDBACKQUESTION_LASTMODIFIEDBYID("WorkFeedbackQuestion.LastModifiedById"),
    // WorkFeedbackQuestion.LastModifiedDate
    WORKFEEDBACKQUESTION_LASTMODIFIEDDATE("WorkFeedbackQuestion.LastModifiedDate"),
    // WorkFeedbackQuestion.Name
    WORKFEEDBACKQUESTION_NAME("WorkFeedbackQuestion.Name"),
    // WorkFeedbackQuestion.Number
    WORKFEEDBACKQUESTION_NUMBER("WorkFeedbackQuestion.Number"),
    // WorkFeedbackQuestion.OwnerId
    WORKFEEDBACKQUESTION_OWNERID("WorkFeedbackQuestion.OwnerId"),
    // WorkFeedbackQuestion.QuestionSetId
    WORKFEEDBACKQUESTION_QUESTIONSETID("WorkFeedbackQuestion.QuestionSetId"),
    // WorkFeedbackQuestion.SystemModstamp
    WORKFEEDBACKQUESTION_SYSTEMMODSTAMP("WorkFeedbackQuestion.SystemModstamp"),
    // WorkFeedbackQuestion.Text
    WORKFEEDBACKQUESTION_TEXT("WorkFeedbackQuestion.Text"),
    // WorkFeedbackQuestion.Type
    WORKFEEDBACKQUESTION_TYPE("WorkFeedbackQuestion.Type"),
    // WorkFeedbackQuestionSet.CreatedById
    WORKFEEDBACKQUESTIONSET_CREATEDBYID("WorkFeedbackQuestionSet.CreatedById"),
    // WorkFeedbackQuestionSet.CreatedDate
    WORKFEEDBACKQUESTIONSET_CREATEDDATE("WorkFeedbackQuestionSet.CreatedDate"),
    // WorkFeedbackQuestionSet.DueDate
    WORKFEEDBACKQUESTIONSET_DUEDATE("WorkFeedbackQuestionSet.DueDate"),
    // WorkFeedbackQuestionSet.FeedbackType
    WORKFEEDBACKQUESTIONSET_FEEDBACKTYPE("WorkFeedbackQuestionSet.FeedbackType"),
    // WorkFeedbackQuestionSet.Id
    WORKFEEDBACKQUESTIONSET_ID("WorkFeedbackQuestionSet.Id"),
    // WorkFeedbackQuestionSet.IsDeleted
    WORKFEEDBACKQUESTIONSET_ISDELETED("WorkFeedbackQuestionSet.IsDeleted"),
    // WorkFeedbackQuestionSet.LastModifiedById
    WORKFEEDBACKQUESTIONSET_LASTMODIFIEDBYID("WorkFeedbackQuestionSet.LastModifiedById"),
    // WorkFeedbackQuestionSet.LastModifiedDate
    WORKFEEDBACKQUESTIONSET_LASTMODIFIEDDATE("WorkFeedbackQuestionSet.LastModifiedDate"),
    // WorkFeedbackQuestionSet.Name
    WORKFEEDBACKQUESTIONSET_NAME("WorkFeedbackQuestionSet.Name"),
    // WorkFeedbackQuestionSet.OwnerId
    WORKFEEDBACKQUESTIONSET_OWNERID("WorkFeedbackQuestionSet.OwnerId"),
    // WorkFeedbackQuestionSet.PerformanceCycleId
    WORKFEEDBACKQUESTIONSET_PERFORMANCECYCLEID("WorkFeedbackQuestionSet.PerformanceCycleId"),
    // WorkFeedbackQuestionSet.SystemModstamp
    WORKFEEDBACKQUESTIONSET_SYSTEMMODSTAMP("WorkFeedbackQuestionSet.SystemModstamp"),
    // WorkFeedbackRequest.AdHocFeedback
    WORKFEEDBACKREQUEST_ADHOCFEEDBACK("WorkFeedbackRequest.AdHocFeedback"),
    // WorkFeedbackRequest.AdHocQuestion
    WORKFEEDBACKREQUEST_ADHOCQUESTION("WorkFeedbackRequest.AdHocQuestion"),
    // WorkFeedbackRequest.CreatedById
    WORKFEEDBACKREQUEST_CREATEDBYID("WorkFeedbackRequest.CreatedById"),
    // WorkFeedbackRequest.CreatedDate
    WORKFEEDBACKREQUEST_CREATEDDATE("WorkFeedbackRequest.CreatedDate"),
    // WorkFeedbackRequest.Description
    WORKFEEDBACKREQUEST_DESCRIPTION("WorkFeedbackRequest.Description"),
    // WorkFeedbackRequest.FeedbackRequestState
    WORKFEEDBACKREQUEST_FEEDBACKREQUESTSTATE("WorkFeedbackRequest.FeedbackRequestState"),
    // WorkFeedbackRequest.FeedbackType
    WORKFEEDBACKREQUEST_FEEDBACKTYPE("WorkFeedbackRequest.FeedbackType"),
    // WorkFeedbackRequest.Id
    WORKFEEDBACKREQUEST_ID("WorkFeedbackRequest.Id"),
    // WorkFeedbackRequest.IsDeleted
    WORKFEEDBACKREQUEST_ISDELETED("WorkFeedbackRequest.IsDeleted"),
    // WorkFeedbackRequest.IsShareWithSubject
    WORKFEEDBACKREQUEST_ISSHAREWITHSUBJECT("WorkFeedbackRequest.IsShareWithSubject"),
    // WorkFeedbackRequest.IsUnreadByOwner
    WORKFEEDBACKREQUEST_ISUNREADBYOWNER("WorkFeedbackRequest.IsUnreadByOwner"),
    // WorkFeedbackRequest.IsUnsolicited
    WORKFEEDBACKREQUEST_ISUNSOLICITED("WorkFeedbackRequest.IsUnsolicited"),
    // WorkFeedbackRequest.LastModifiedById
    WORKFEEDBACKREQUEST_LASTMODIFIEDBYID("WorkFeedbackRequest.LastModifiedById"),
    // WorkFeedbackRequest.LastModifiedDate
    WORKFEEDBACKREQUEST_LASTMODIFIEDDATE("WorkFeedbackRequest.LastModifiedDate"),
    // WorkFeedbackRequest.LastReferencedDate
    WORKFEEDBACKREQUEST_LASTREFERENCEDDATE("WorkFeedbackRequest.LastReferencedDate"),
    // WorkFeedbackRequest.LastRemindDate
    WORKFEEDBACKREQUEST_LASTREMINDDATE("WorkFeedbackRequest.LastRemindDate"),
    // WorkFeedbackRequest.LastSharedDate
    WORKFEEDBACKREQUEST_LASTSHAREDDATE("WorkFeedbackRequest.LastSharedDate"),
    // WorkFeedbackRequest.LastViewedDate
    WORKFEEDBACKREQUEST_LASTVIEWEDDATE("WorkFeedbackRequest.LastViewedDate"),
    // WorkFeedbackRequest.Name
    WORKFEEDBACKREQUEST_NAME("WorkFeedbackRequest.Name"),
    // WorkFeedbackRequest.OwnerId
    WORKFEEDBACKREQUEST_OWNERID("WorkFeedbackRequest.OwnerId"),
    // WorkFeedbackRequest.PerformanceCycleId
    WORKFEEDBACKREQUEST_PERFORMANCECYCLEID("WorkFeedbackRequest.PerformanceCycleId"),
    // WorkFeedbackRequest.QuestionSetId
    WORKFEEDBACKREQUEST_QUESTIONSETID("WorkFeedbackRequest.QuestionSetId"),
    // WorkFeedbackRequest.RecipientId
    WORKFEEDBACKREQUEST_RECIPIENTID("WorkFeedbackRequest.RecipientId"),
    // WorkFeedbackRequest.RelatedObjectId
    WORKFEEDBACKREQUEST_RELATEDOBJECTID("WorkFeedbackRequest.RelatedObjectId"),
    // WorkFeedbackRequest.SharingScope
    WORKFEEDBACKREQUEST_SHARINGSCOPE("WorkFeedbackRequest.SharingScope"),
    // WorkFeedbackRequest.SubjectId
    WORKFEEDBACKREQUEST_SUBJECTID("WorkFeedbackRequest.SubjectId"),
    // WorkFeedbackRequest.SubmitFeedbackToId
    WORKFEEDBACKREQUEST_SUBMITFEEDBACKTOID("WorkFeedbackRequest.SubmitFeedbackToId"),
    // WorkFeedbackRequest.SubmittedDate
    WORKFEEDBACKREQUEST_SUBMITTEDDATE("WorkFeedbackRequest.SubmittedDate"),
    // WorkFeedbackRequest.SystemModstamp
    WORKFEEDBACKREQUEST_SYSTEMMODSTAMP("WorkFeedbackRequest.SystemModstamp"),
    // WorkFeedbackRequest.TemplateId
    WORKFEEDBACKREQUEST_TEMPLATEID("WorkFeedbackRequest.TemplateId"),
    // WorkFeedbackTemplate.CreatedById
    WORKFEEDBACKTEMPLATE_CREATEDBYID("WorkFeedbackTemplate.CreatedById"),
    // WorkFeedbackTemplate.CreatedDate
    WORKFEEDBACKTEMPLATE_CREATEDDATE("WorkFeedbackTemplate.CreatedDate"),
    // WorkFeedbackTemplate.Id
    WORKFEEDBACKTEMPLATE_ID("WorkFeedbackTemplate.Id"),
    // WorkFeedbackTemplate.IsDeleted
    WORKFEEDBACKTEMPLATE_ISDELETED("WorkFeedbackTemplate.IsDeleted"),
    // WorkFeedbackTemplate.LastModifiedById
    WORKFEEDBACKTEMPLATE_LASTMODIFIEDBYID("WorkFeedbackTemplate.LastModifiedById"),
    // WorkFeedbackTemplate.LastModifiedDate
    WORKFEEDBACKTEMPLATE_LASTMODIFIEDDATE("WorkFeedbackTemplate.LastModifiedDate"),
    // WorkFeedbackTemplate.LastReferencedDate
    WORKFEEDBACKTEMPLATE_LASTREFERENCEDDATE("WorkFeedbackTemplate.LastReferencedDate"),
    // WorkFeedbackTemplate.LastViewedDate
    WORKFEEDBACKTEMPLATE_LASTVIEWEDDATE("WorkFeedbackTemplate.LastViewedDate"),
    // WorkFeedbackTemplate.Name
    WORKFEEDBACKTEMPLATE_NAME("WorkFeedbackTemplate.Name"),
    // WorkFeedbackTemplate.OwnerId
    WORKFEEDBACKTEMPLATE_OWNERID("WorkFeedbackTemplate.OwnerId"),
    // WorkFeedbackTemplate.QuestionSetId
    WORKFEEDBACKTEMPLATE_QUESTIONSETID("WorkFeedbackTemplate.QuestionSetId"),
    // WorkFeedbackTemplate.SystemModstamp
    WORKFEEDBACKTEMPLATE_SYSTEMMODSTAMP("WorkFeedbackTemplate.SystemModstamp"),
    // WorkPerformanceCycle.ActivityFrom
    WORKPERFORMANCECYCLE_ACTIVITYFROM("WorkPerformanceCycle.ActivityFrom"),
    // WorkPerformanceCycle.ActivityTo
    WORKPERFORMANCECYCLE_ACTIVITYTO("WorkPerformanceCycle.ActivityTo"),
    // WorkPerformanceCycle.CreatedById
    WORKPERFORMANCECYCLE_CREATEDBYID("WorkPerformanceCycle.CreatedById"),
    // WorkPerformanceCycle.CreatedDate
    WORKPERFORMANCECYCLE_CREATEDDATE("WorkPerformanceCycle.CreatedDate"),
    // WorkPerformanceCycle.CurrentTask
    WORKPERFORMANCECYCLE_CURRENTTASK("WorkPerformanceCycle.CurrentTask"),
    // WorkPerformanceCycle.Id
    WORKPERFORMANCECYCLE_ID("WorkPerformanceCycle.Id"),
    // WorkPerformanceCycle.IsDeleted
    WORKPERFORMANCECYCLE_ISDELETED("WorkPerformanceCycle.IsDeleted"),
    // WorkPerformanceCycle.LastManagerRequestsSharedDate
    WORKPERFORMANCECYCLE_LASTMANAGERREQUESTSSHAREDDATE("WorkPerformanceCycle.LastManagerRequestsSharedDate"),
    // WorkPerformanceCycle.LastModifiedById
    WORKPERFORMANCECYCLE_LASTMODIFIEDBYID("WorkPerformanceCycle.LastModifiedById"),
    // WorkPerformanceCycle.LastModifiedDate
    WORKPERFORMANCECYCLE_LASTMODIFIEDDATE("WorkPerformanceCycle.LastModifiedDate"),
    // WorkPerformanceCycle.LastReferencedDate
    WORKPERFORMANCECYCLE_LASTREFERENCEDDATE("WorkPerformanceCycle.LastReferencedDate"),
    // WorkPerformanceCycle.LastViewedDate
    WORKPERFORMANCECYCLE_LASTVIEWEDDATE("WorkPerformanceCycle.LastViewedDate"),
    // WorkPerformanceCycle.Name
    WORKPERFORMANCECYCLE_NAME("WorkPerformanceCycle.Name"),
    // WorkPerformanceCycle.OwnerId
    WORKPERFORMANCECYCLE_OWNERID("WorkPerformanceCycle.OwnerId"),
    // WorkPerformanceCycle.State
    WORKPERFORMANCECYCLE_STATE("WorkPerformanceCycle.State"),
    // WorkPerformanceCycle.SystemModstamp
    WORKPERFORMANCECYCLE_SYSTEMMODSTAMP("WorkPerformanceCycle.SystemModstamp");

    final String value;

    private AggregateFieldEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static AggregateFieldEnum fromValue(String value) {
        for (AggregateFieldEnum e : AggregateFieldEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
