/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist CurrentTask
 */
public enum CurrentTaskEnum {

    // Deploying
    DEPLOYING("Deploying"),
    // Finishing
    FINISHING("Finishing"),
    // Sharing
    SHARING("Sharing");

    final String value;

    private CurrentTaskEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static CurrentTaskEnum fromValue(String value) {
        for (CurrentTaskEnum e : CurrentTaskEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
