/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DefaultLocaleSidKey
 */
public enum DefaultLocaleSidKeyEnum {

    // ar_AE
    AR_AE("ar_AE"),
    // ar_BH
    AR_BH("ar_BH"),
    // ar_DZ
    AR_DZ("ar_DZ"),
    // ar_EG
    AR_EG("ar_EG"),
    // ar_IQ
    AR_IQ("ar_IQ"),
    // ar_JO
    AR_JO("ar_JO"),
    // ar_KW
    AR_KW("ar_KW"),
    // ar_LB
    AR_LB("ar_LB"),
    // ar_LY
    AR_LY("ar_LY"),
    // ar_MA
    AR_MA("ar_MA"),
    // ar_OM
    AR_OM("ar_OM"),
    // ar_QA
    AR_QA("ar_QA"),
    // ar_SA
    AR_SA("ar_SA"),
    // ar_SD
    AR_SD("ar_SD"),
    // ar_SY
    AR_SY("ar_SY"),
    // ar_TN
    AR_TN("ar_TN"),
    // ar_YE
    AR_YE("ar_YE"),
    // az_AZ
    AZ_AZ("az_AZ"),
    // be_BY
    BE_BY("be_BY"),
    // bg_BG
    BG_BG("bg_BG"),
    // bn_BD
    BN_BD("bn_BD"),
    // bs_BA
    BS_BA("bs_BA"),
    // ca_ES
    CA_ES("ca_ES"),
    // cs_CZ
    CS_CZ("cs_CZ"),
    // cy_GB
    CY_GB("cy_GB"),
    // da_DK
    DA_DK("da_DK"),
    // de_AT
    DE_AT("de_AT"),
    // de_CH
    DE_CH("de_CH"),
    // de_DE
    DE_DE("de_DE"),
    // de_LU
    DE_LU("de_LU"),
    // el_GR
    EL_GR("el_GR"),
    // en_AU
    EN_AU("en_AU"),
    // en_BB
    EN_BB("en_BB"),
    // en_BM
    EN_BM("en_BM"),
    // en_CA
    EN_CA("en_CA"),
    // en_GB
    EN_GB("en_GB"),
    // en_GH
    EN_GH("en_GH"),
    // en_HK
    EN_HK("en_HK"),
    // en_ID
    EN_ID("en_ID"),
    // en_IE
    EN_IE("en_IE"),
    // en_IN
    EN_IN("en_IN"),
    // en_MY
    EN_MY("en_MY"),
    // en_NG
    EN_NG("en_NG"),
    // en_NZ
    EN_NZ("en_NZ"),
    // en_PH
    EN_PH("en_PH"),
    // en_PK
    EN_PK("en_PK"),
    // en_SG
    EN_SG("en_SG"),
    // en_US
    EN_US("en_US"),
    // en_ZA
    EN_ZA("en_ZA"),
    // es_AR
    ES_AR("es_AR"),
    // es_BO
    ES_BO("es_BO"),
    // es_CL
    ES_CL("es_CL"),
    // es_CO
    ES_CO("es_CO"),
    // es_CR
    ES_CR("es_CR"),
    // es_DO
    ES_DO("es_DO"),
    // es_EC
    ES_EC("es_EC"),
    // es_ES
    ES_ES("es_ES"),
    // es_GT
    ES_GT("es_GT"),
    // es_HN
    ES_HN("es_HN"),
    // es_MX
    ES_MX("es_MX"),
    // es_NI
    ES_NI("es_NI"),
    // es_PA
    ES_PA("es_PA"),
    // es_PE
    ES_PE("es_PE"),
    // es_PR
    ES_PR("es_PR"),
    // es_PY
    ES_PY("es_PY"),
    // es_SV
    ES_SV("es_SV"),
    // es_US
    ES_US("es_US"),
    // es_UY
    ES_UY("es_UY"),
    // es_VE
    ES_VE("es_VE"),
    // et_EE
    ET_EE("et_EE"),
    // eu_ES
    EU_ES("eu_ES"),
    // fi_FI
    FI_FI("fi_FI"),
    // fr_BE
    FR_BE("fr_BE"),
    // fr_CA
    FR_CA("fr_CA"),
    // fr_CH
    FR_CH("fr_CH"),
    // fr_FR
    FR_FR("fr_FR"),
    // fr_LU
    FR_LU("fr_LU"),
    // fr_MC
    FR_MC("fr_MC"),
    // ga_IE
    GA_IE("ga_IE"),
    // hi_IN
    HI_IN("hi_IN"),
    // hr_HR
    HR_HR("hr_HR"),
    // hu_HU
    HU_HU("hu_HU"),
    // hy_AM
    HY_AM("hy_AM"),
    // in_ID
    IN_ID("in_ID"),
    // is_IS
    IS_IS("is_IS"),
    // it_CH
    IT_CH("it_CH"),
    // it_IT
    IT_IT("it_IT"),
    // iw_IL
    IW_IL("iw_IL"),
    // ja_JP
    JA_JP("ja_JP"),
    // ka_GE
    KA_GE("ka_GE"),
    // kk_KZ
    KK_KZ("kk_KZ"),
    // km_KH
    KM_KH("km_KH"),
    // ko_KR
    KO_KR("ko_KR"),
    // ky_KG
    KY_KG("ky_KG"),
    // lb_LU
    LB_LU("lb_LU"),
    // lt_LT
    LT_LT("lt_LT"),
    // lv_LV
    LV_LV("lv_LV"),
    // mk_MK
    MK_MK("mk_MK"),
    // ms_BN
    MS_BN("ms_BN"),
    // ms_MY
    MS_MY("ms_MY"),
    // mt_MT
    MT_MT("mt_MT"),
    // nl_BE
    NL_BE("nl_BE"),
    // nl_NL
    NL_NL("nl_NL"),
    // nl_SR
    NL_SR("nl_SR"),
    // no_NO
    NO_NO("no_NO"),
    // pl_PL
    PL_PL("pl_PL"),
    // pt_AO
    PT_AO("pt_AO"),
    // pt_BR
    PT_BR("pt_BR"),
    // pt_PT
    PT_PT("pt_PT"),
    // rm_CH
    RM_CH("rm_CH"),
    // ro_MD
    RO_MD("ro_MD"),
    // ro_RO
    RO_RO("ro_RO"),
    // ru_RU
    RU_RU("ru_RU"),
    // sh_BA
    SH_BA("sh_BA"),
    // sh_CS
    SH_CS("sh_CS"),
    // sh_ME
    SH_ME("sh_ME"),
    // sk_SK
    SK_SK("sk_SK"),
    // sl_SI
    SL_SI("sl_SI"),
    // sq_AL
    SQ_AL("sq_AL"),
    // sr_BA
    SR_BA("sr_BA"),
    // sr_CS
    SR_CS("sr_CS"),
    // sv_SE
    SV_SE("sv_SE"),
    // ta_IN
    TA_IN("ta_IN"),
    // tg_TJ
    TG_TJ("tg_TJ"),
    // th_TH
    TH_TH("th_TH"),
    // tl_PH
    TL_PH("tl_PH"),
    // tr_TR
    TR_TR("tr_TR"),
    // uk_UA
    UK_UA("uk_UA"),
    // ur_PK
    UR_PK("ur_PK"),
    // vi_VN
    VI_VN("vi_VN"),
    // zh_CN
    ZH_CN("zh_CN"),
    // zh_CN_PINYIN
    ZH_CN_PINYIN("zh_CN_PINYIN"),
    // zh_CN_STROKE
    ZH_CN_STROKE("zh_CN_STROKE"),
    // zh_HK
    ZH_HK("zh_HK"),
    // zh_HK_STROKE
    ZH_HK_STROKE("zh_HK_STROKE"),
    // zh_MO
    ZH_MO("zh_MO"),
    // zh_SG
    ZH_SG("zh_SG"),
    // zh_TW
    ZH_TW("zh_TW"),
    // zh_TW_STROKE
    ZH_TW_STROKE("zh_TW_STROKE");

    final String value;

    private DefaultLocaleSidKeyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DefaultLocaleSidKeyEnum fromValue(String value) {
        for (DefaultLocaleSidKeyEnum e : DefaultLocaleSidKeyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
