/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject DuplicateRecordItem
 */
@XStreamAlias("DuplicateRecordItem")
public class DuplicateRecordItem extends AbstractSObjectBase {

    // DuplicateRecordSetId
    private String DuplicateRecordSetId;

    @JsonProperty("DuplicateRecordSetId")
    public String getDuplicateRecordSetId() {
        return this.DuplicateRecordSetId;
    }

    @JsonProperty("DuplicateRecordSetId")
    public void setDuplicateRecordSetId(String DuplicateRecordSetId) {
        this.DuplicateRecordSetId = DuplicateRecordSetId;
    }

    // RecordId
    private String RecordId;

    @JsonProperty("RecordId")
    public String getRecordId() {
        return this.RecordId;
    }

    @JsonProperty("RecordId")
    public void setRecordId(String RecordId) {
        this.RecordId = RecordId;
    }

}
