/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist FeedbackType
 */
public enum FeedbackTypeEnum {

    // CycleManager
    CYCLEMANAGER("CycleManager"),
    // CyclePeer
    CYCLEPEER("CyclePeer"),
    // CycleSelf
    CYCLESELF("CycleSelf"),
    // CycleSkipLevel
    CYCLESKIPLEVEL("CycleSkipLevel"),
    // OnTopic
    ONTOPIC("OnTopic"),
    // Personal
    PERSONAL("Personal"),
    // UnsolicitedToManager
    UNSOLICITEDTOMANAGER("UnsolicitedToManager"),
    // UnsolicitedToUser
    UNSOLICITEDTOUSER("UnsolicitedToUser"),
    // UnsolicitedToUserandManager
    UNSOLICITEDTOUSERANDMANAGER("UnsolicitedToUserandManager"),
    // Unspecified
    UNSPECIFIED("Unspecified");

    final String value;

    private FeedbackTypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FeedbackTypeEnum fromValue(String value) {
        for (FeedbackTypeEnum e : FeedbackTypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
