/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist FeedbackRequestState
 */
public enum FeedbackRequestStateEnum {

    // Declined
    DECLINED("Declined"),
    // Draft
    DRAFT("Draft"),
    // Submitted
    SUBMITTED("Submitted");

    final String value;

    private FeedbackRequestStateEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FeedbackRequestStateEnum fromValue(String value) {
        for (FeedbackRequestStateEnum e : FeedbackRequestStateEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
