/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist SharingScope
 */
public enum SharingScopeEnum {

    // Manager
    MANAGER("Manager"),
    // Nobody
    NOBODY("Nobody"),
    // Subject
    SUBJECT("Subject"),
    // SubjectAndManager
    SUBJECTANDMANAGER("SubjectAndManager");

    final String value;

    private SharingScopeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static SharingScopeEnum fromValue(String value) {
        for (SharingScopeEnum e : SharingScopeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
