/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject TopicAssignment
 */
@XStreamAlias("TopicAssignment")
public class TopicAssignment extends AbstractSObjectBase {

    // TopicId
    private String TopicId;

    @JsonProperty("TopicId")
    public String getTopicId() {
        return this.TopicId;
    }

    @JsonProperty("TopicId")
    public void setTopicId(String TopicId) {
        this.TopicId = TopicId;
    }

    // EntityId
    private String EntityId;

    @JsonProperty("EntityId")
    public String getEntityId() {
        return this.EntityId;
    }

    @JsonProperty("EntityId")
    public void setEntityId(String EntityId) {
        this.EntityId = EntityId;
    }

    // EntityKeyPrefix
    private String EntityKeyPrefix;

    @JsonProperty("EntityKeyPrefix")
    public String getEntityKeyPrefix() {
        return this.EntityKeyPrefix;
    }

    @JsonProperty("EntityKeyPrefix")
    public void setEntityKeyPrefix(String EntityKeyPrefix) {
        this.EntityKeyPrefix = EntityKeyPrefix;
    }

    // EntityType
    private String EntityType;

    @JsonProperty("EntityType")
    public String getEntityType() {
        return this.EntityType;
    }

    @JsonProperty("EntityType")
    public void setEntityType(String EntityType) {
        this.EntityType = EntityType;
    }

}
