/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Tue May 31 11:45:50 CST 2016
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject WorkFeedback
 */
@XStreamAlias("WorkFeedback")
public class WorkFeedback extends AbstractSObjectBase {

    // RequestId
    private String RequestId;

    @JsonProperty("RequestId")
    public String getRequestId() {
        return this.RequestId;
    }

    @JsonProperty("RequestId")
    public void setRequestId(String RequestId) {
        this.RequestId = RequestId;
    }

    // QuestionId
    private String QuestionId;

    @JsonProperty("QuestionId")
    public String getQuestionId() {
        return this.QuestionId;
    }

    @JsonProperty("QuestionId")
    public void setQuestionId(String QuestionId) {
        this.QuestionId = QuestionId;
    }

    // Feedback
    private String Feedback;

    @JsonProperty("Feedback")
    public String getFeedback() {
        return this.Feedback;
    }

    @JsonProperty("Feedback")
    public void setFeedback(String Feedback) {
        this.Feedback = Feedback;
    }

}
